#!/bin/bash

LOG_FILE="/dev/null"

function CreateUser()
{
  useradd "$1" -s /bin/sh >> ${LOG_FILE} 2>&1
  if [ $? -ne 0 ]; then
   	echo "CreateUser $1 failed!"
  fi
}

CreateUser xpum

if [ -n "${RPM_INSTALL_PREFIX}" ]; then
  sed -e "s:@CPACK_PACKAGING_INSTALL_PREFIX@:${RPM_INSTALL_PREFIX}:g" /usr/lib/systemd/system/xpum.service > /usr/lib/systemd/system/xpum.service.n
  mv -f /usr/lib/systemd/system/xpum.service.n /usr/lib/systemd/system/xpum.service

  sed -e "s:@CPACK_PACKAGING_INSTALL_PREFIX@:${RPM_INSTALL_PREFIX}:g" /usr/lib/systemd/system/xpum_rest.service > /usr/lib/systemd/system/xpum_rest.service.n
  mv -f /usr/lib/systemd/system/xpum_rest.service.n /usr/lib/systemd/system/xpum_rest.service 

  chown -R xpum ${RPM_INSTALL_PREFIX}
  chmod +x ${RPM_INSTALL_PREFIX}/keytool.sh
else
  chown -R xpum /opt/xpum
  chmod +x /opt/xpum/keytool.sh
fi

systemctl daemon-reload >> ${LOG_FILE} 2>&1 
systemctl enable xpum >> ${LOG_FILE} 2>&1 
systemctl start xpum
