#!/bin/bash

LOG_FILE="/dev/null"

function RemoveUser()
{
  group=$( userdel -rf ${1} 2>&1 | grep "group ${1} not removed" )    
  if [ -n "$group" ]; then
	 	groupdel xpum -f >> ${LOG_FILE} 2>&1	
	fi
}

systemctl stop xpum >> ${LOG_FILE} 2>&1 
systemctl disable xpum >> ${LOG_FILE} 2>&1 
systemctl stop xpum_rest >> ${LOG_FILE} 2>&1 
systemctl disable xpum_rest >> ${LOG_FILE} 2>&1 
systemctl daemon-reload >> ${LOG_FILE} 2>&1 
RemoveUser xpum
