#!/bin/bash

LOG_FILE="/dev/null"

function RemoveUser()
{
  group=$( userdel -rf ${1} 2>&1 | grep "group ${1} not removed" )    
  if [ -n "$group" ]; then
	 	groupdel xpum -f >> ${LOG_FILE} 2>&1	
	fi
}

if [ -d ${SERVICE_PATH} ]; then
  export SERVICE_PATH=${SERVICE_PATH}
else
  export SERVICE_PATH=/etc/systemd/system
fi

systemctl stop xpum >> ${LOG_FILE} 2>&1 
systemctl disable xpum >> ${LOG_FILE} 2>&1 
systemctl stop xpum_rest >> ${LOG_FILE} 2>&1 
systemctl disable xpum_rest >> ${LOG_FILE} 2>&1 
rm -rf ${SERVICE_PATH}/xpum.service
rm -rf ${SERVICE_PATH}/xpum_rest.service
systemctl daemon-reload
RemoveUser xpum
