//
// Copyright (C) 2026 Intel Corporation
//
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: exporter/api/deviceinfo/v1alpha1/deviceinfo.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceInfo_WatchDeviceHealth_FullMethodName = "/deviceinfo.DeviceInfo/WatchDeviceHealth"
)

// DeviceInfoClient is the client API for DeviceInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeviceInfo service provides info for XPU devices.
type DeviceInfoClient interface {
	// WatchDeviceHealth returns a stream of health metrics for all devices.
	WatchDeviceHealth(ctx context.Context, in *WatchDeviceHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceHealthResponse], error)
}

type deviceInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceInfoClient(cc grpc.ClientConnInterface) DeviceInfoClient {
	return &deviceInfoClient{cc}
}

func (c *deviceInfoClient) WatchDeviceHealth(ctx context.Context, in *WatchDeviceHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceHealthResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceInfo_ServiceDesc.Streams[0], DeviceInfo_WatchDeviceHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchDeviceHealthRequest, DeviceHealthResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceInfo_WatchDeviceHealthClient = grpc.ServerStreamingClient[DeviceHealthResponse]

// DeviceInfoServer is the server API for DeviceInfo service.
// All implementations must embed UnimplementedDeviceInfoServer
// for forward compatibility.
//
// DeviceInfo service provides info for XPU devices.
type DeviceInfoServer interface {
	// WatchDeviceHealth returns a stream of health metrics for all devices.
	WatchDeviceHealth(*WatchDeviceHealthRequest, grpc.ServerStreamingServer[DeviceHealthResponse]) error
	mustEmbedUnimplementedDeviceInfoServer()
}

// UnimplementedDeviceInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceInfoServer struct{}

func (UnimplementedDeviceInfoServer) WatchDeviceHealth(*WatchDeviceHealthRequest, grpc.ServerStreamingServer[DeviceHealthResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchDeviceHealth not implemented")
}
func (UnimplementedDeviceInfoServer) mustEmbedUnimplementedDeviceInfoServer() {}
func (UnimplementedDeviceInfoServer) testEmbeddedByValue()                    {}

// UnsafeDeviceInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceInfoServer will
// result in compilation errors.
type UnsafeDeviceInfoServer interface {
	mustEmbedUnimplementedDeviceInfoServer()
}

func RegisterDeviceInfoServer(s grpc.ServiceRegistrar, srv DeviceInfoServer) {
	// If the following call panics, it indicates UnimplementedDeviceInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceInfo_ServiceDesc, srv)
}

func _DeviceInfo_WatchDeviceHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchDeviceHealthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceInfoServer).WatchDeviceHealth(m, &grpc.GenericServerStream[WatchDeviceHealthRequest, DeviceHealthResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceInfo_WatchDeviceHealthServer = grpc.ServerStreamingServer[DeviceHealthResponse]

// DeviceInfo_ServiceDesc is the grpc.ServiceDesc for DeviceInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deviceinfo.DeviceInfo",
	HandlerType: (*DeviceInfoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchDeviceHealth",
			Handler:       _DeviceInfo_WatchDeviceHealth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "exporter/api/deviceinfo/v1alpha1/deviceinfo.proto",
}
