/* 
 *  Copyright (C) 2021-2022 Intel Corporation
 *  SPDX-License-Identifier: MIT
 *  @file device_capability.h
 */

#pragma once

namespace xpum {
enum class DeviceCapability : int {
    METRIC_POWER,
    METRIC_FREQUENCY,
    METRIC_TEMPERATURE,
    METRIC_ENERGY,
    METRIC_MEMORY_USED,
    METRIC_MEMORY_UTILIZATION,
    METRIC_MEMORY_BANDWIDTH,
    METRIC_MEMORY_READ,
    METRIC_MEMORY_WRITE,
    METRIC_MEMORY_READ_THROUGHPUT,
    METRIC_MEMORY_WRITE_THROUGHPUT,
    METRIC_COMPUTATION,
    METRIC_ENGINE_GROUP_COMPUTE_ALL_UTILIZATION,
    METRIC_ENGINE_GROUP_MEDIA_ALL_UTILIZATION,
    METRIC_ENGINE_GROUP_COPY_ALL_UTILIZATION,
    METRIC_ENGINE_GROUP_RENDER_ALL_UTILIZATION,
    METRIC_ENGINE_GROUP_3D_ALL_UTILIZATION,
    METRIC_EU_ACTIVE_STALL_IDLE,
    METRIC_RAS_ERROR,
    METRIC_REQUEST_FREQUENCY,
    METRIC_MEMORY_TEMPERATURE,
    METRIC_FREQUENCY_THROTTLE,
    METRIC_PCIE_READ_THROUGHPUT,
    METRIC_PCIE_WRITE_THROUGHPUT,
    METRIC_PCIE_READ,
    METRIC_PCIE_WRITE,
    METRIC_ENGINE_UTILIZATION,
    METRIC_FABRIC_THROUGHPUT,

    DEVICE_CAPABILITY_MAX,
};
} // end namespace xpum
