#pragma once

enum class DeviceCapability : int {
    POWER,
    FREQUENCY,
    TEMPERATURE,
    MEMORY,
    ENGINE_UTILIZATION,

    METRIC_POWER,
    METRIC_FREQUENCY,
    METRIC_TEMPERATURE,
    METRIC_ENERGY,
    METRIC_MEMORY_USED,
    METRIC_MEMORY_READ,
    METRIC_MEMORY_WRITE,
    METRIC_COMPUTATION,

    METRIC_RAS_ERROR_CAT_RESET,
    METRIC_RAS_ERROR_CAT_PROGRAMMING_ERRORS,
    METRIC_RAS_ERROR_CAT_DRIVER_ERRORS,
    METRIC_RAS_ERROR_CAT_CACHE_ERRORS_CORRECTABLE,
    METRIC_RAS_ERROR_CAT_CACHE_ERRORS_UNCORRECTABLE,
    METRIC_RAS_ERROR_CAT_DISPLAY_ERRORS_CORRECTABLE,
    METRIC_RAS_ERROR_CAT_DISPLAY_ERRORS_UNCORRECTABLE,
};