#pragma once

enum MeasurementType {
    POWER = 0,
    FREQUENCY,
    TEMPERATURE,
    MEMORY,
    ENGINE_UTILIZATION,
    METRIC_POWER,
    METRIC_ENERGY,
    METRIC_FREQUENCY,
    METRIC_TEMPERATURE,
    METRIC_MEMORY_USED,
    METRIC_MEMORY_READ,
    METRIC_MEMORY_WRITE,
    METRIC_COMPUTATION
};