version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: dev
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directories:
      - "/xpumd"
      - "/xpumd/common"
      - "/xpumd/exporter/intelxpuinfo"
      - "/xpumd/exporter/intelxpuinfo/api"
      - "/xpumd/processor/intelxpustatus"
      - "/xpumd/receiver/intelcrashlog"
      - "/xpumd/receiver/intelxpu"
      - "/xpumd/test/integration"
      - "/xpumd/tools"
    schedule:
      interval: "weekly"
    groups:
      otel-collector:
        patterns:
          - "go.opentelemetry.io/collector/*"
        group-by: "dependency-name"
      non-otel-collector:
        group-by: "dependency-name"
  - package-ecosystem: "gomod"
    directories:
      - "/xpumd/level-zero-go"
      - "/xpumd/level-zero-go/examples"
      - "/xpumd/level-zero-go/hack"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "github.com/xlab/c-for-go"
    groups:
      level-zero-go:
        group-by: "dependency-name"
