# Copyright (C) 2023-2024 Intel Corporation
# SPDX-License-Identifier: MIT

# SR-IOV config file

# VGPU_SCHEDULER has three options: Flexible_30fps_GPUTimeSlicing, Fixed_30fps_GPUTimeSlicing, Flexible_BurstableQoS_GPUTimeSlicing.
# For details about VGPU_SCHEDULER, please refer to the link: https://github.com/intel/xpumanager/blob/master/core/src/vgpu/vgpu_manager.cpp

# BMG DT6- default values. They are mostly obtained after observing the auto provisioning numbers.
NAME=e211DEF,e216DEF
VF_LMEM=25367150592 #~24 GB Equally divided to each vgpu
VF_LMEM_ECC=21500002304 #~20 GB Equally divided to each vgpu
VF_CONTEXTS=1024 # Each vgpu will be given this many contexts
VF_DOORBELLS=240 #Equally divided to each vgpu
VF_GGTT=4026531840 #~3.75 GB Equally divided to each vgpu
VGPU_SCHEDULER=Flexible_BurstableQoS_GPUTimeSlicing
DRIVERS_AUTOPROBE=0 #Same as default configuration
