# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: MIT

# SR-IOV config file
#
# VGPU_SCHEDULER has three options: Flexible_30fps_GPUTimeSlicing, Fixed_30fps_GPUTimeSlicing, Flexible_BurstableQoS_GPUTimeSlicing.
# For details about VGPU_SCHEDULER, please refer to the link: https://github.com/intel/xpumanager/blob/master/core/src/vgpu/vgpu_manager.cpp
#
# BMG DT6- default values
NAME=e211DEF,e216DEF
VF_LMEM=25367150592 #~24 GB Equally divided to each vgpu
VF_LMEM_ECC=21500002304 #~20 GB Equally divided to each vgpu
VF_CONTEXTS=1024 # Each vgpu will be given this many contexts
VF_DOORBELLS=240 #Equally divided to each vgpu
VF_GGTT=4026531840 #~3.75 GB Equally divided to each vgpu
VGPU_SCHEDULER=Flexible_BurstableQoS_GPUTimeSlicing
DRIVERS_AUTOPROBE=0 #Same as default configuration
#
# BMG 0xE222 default values
NAME=e222DEF
VF_LMEM=33285996544  #31 GB Equally divided to each vgpu
VF_LMEM_ECC=28293097062 #26.35 GB Equally divided to each vgpu
VF_CONTEXTS=1024 #Each vgpu will be given this many contexts
VF_DOORBELLS=256 #Equally divided to each vgpu
VF_GGTT=4171825152 #3.88 GB Equally divided to each vgpu
VGPU_SCHEDULER=Flexible_BurstableQoS_GPUTimeSlicing
DRIVERS_AUTOPROBE=0 #Same as default configuration
#
# BMG E223 default values
NAME=e223DEF
VF_LMEM=29771169792 #~28 GB Equally divided to each vgpu
VF_LMEM_ECC=21500002304 #~20 GB Equally divided to each vgpu
VF_CONTEXTS=1024 # Each vgpu will be given this many contexts
VF_DOORBELLS=256 #Equally divided to each vgpu
VF_GGTT=4155076608 #~3.87 GB Equally divided to each vgpu
VGPU_SCHEDULER=Flexible_BurstableQoS_GPUTimeSlicing
DRIVERS_AUTOPROBE=0 #Same as default configuration
#
# BMG E212 default values
NAME=e212DEF
VF_LMEM=16911433728 #~16 GB Equally divided to each vgpu
VF_LMEM_ECC=14768144384 #~14 GB Equally divided to each vgpu
VF_CONTEXTS=1024 # Each vgpu will be given this many contexts
VF_DOORBELLS=256 #Equally divided to each vgpu
VF_GGTT=4155076608 #~3.87 GB Equally divided to each vgpu
VGPU_SCHEDULER=Flexible_BurstableQoS_GPUTimeSlicing
DRIVERS_AUTOPROBE=0 #Same as default configuration
