receivers:
  # The custom Level-Zero Sysman receiver.
  sysman:
    # Log level (debug, info, warn, error)
    log_level: info
    # Metrics data collection interval.
    # Must be at least twice the sample_interval.
    collection_interval: 30s
    # Initial start delay for metrics collection, any non positive value is assumed to be immediately.
    initial_delay: 1s
    # Metrics collection timeout.
    timeout: 0
    # Sample interval for the high-frequency metrics.
    sample_interval: 1s

exporters:
  prometheus:
    endpoint: "0.0.0.0:8080"

processors:

extensions:

service:
  pipelines:
    metrics:
      receivers: [sysman]
      exporters: [prometheus]
