# Log level (debug, info, warn, error)
logLevel: info

# Metrics data collection interval
collectInterval: 30s

# Configuration for exporters
# - By default none are enabled, please select a suitable one
exporters:
  # Configuration for the stdout exporter
  stdout:
    # Enable this exporter
    enabled: false
  # Configuration for the Prometheus exporter
  prometheus:
    # Enable this exporter
    enabled: false
  # Configuration for the OTLP gRPC exporter
  grpc:
    # Enable this exporter
    enabled: false
    # OTLP/gRPC collector endpoint. If empty, taken from
    # OTEL_EXPORTER_OTLP_ENDPOINT or OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
    # environment variable, or localhost:4317 by default.
    endpoint: ""
    # Use insecure connection (no TLS)
    insecure: false
  # Configuration for the OTLP HTTP exporter
  http:
    # Enable this exporter
    enabled: false
    # OTLP/HTTP collector endpoint. If empty, taken from
    # OTEL_EXPORTER_OTLP_ENDPOINT or OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
    # environment variable, or localhost:4318 by default.
    endpoint: ""
    # Use insecure connection (no TLS)
    insecure: false
