#!/bin/bash

LOG_FILE="/dev/null"

echo "install=${CPACK_PACKAGING_INSTALL_PREFIX}"
#export
#read -p "debug..."
function CreateUser()
{
  useradd "$1" -s /bin/sh >> ${LOG_FILE} 2>&1
  if [ $? -ne 0 ]; then
   	echo "CreateUser $1 failed!"
  fi
}

echo "Create user xpum"
CreateUser xpum
chown -R xpum /opt/intel/xpum
chmod +x /opt/intel/xpum/rest/xpum_rest.sh

if [ -f /usr/lib/systemd/system/xpum.service ]; then
  echo "Install xpum service..."
  systemctl daemon-reload >> ${LOG_FILE} 2>&1 
  systemctl enable xpum >> ${LOG_FILE} 2>&1 
  echo "Start xpum service..."
  systemctl start xpum
fi
