#!/bin/bash

LOG_FILE="/dev/null"
echo "Remove xpum daemon..."
systemctl stop xpum >> LOG_FILE 2>&1 
systemctl disable xpum >> LOG_FILE 2>&1 
rm - f /usr/lib/systemd/system/xpum.service >> LOG_FILE 2>&1 
systemctl daemon-reload >> LOG_FILE 2>&1 