apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: intel-xpumanager
  name: intel-xpumanager
  namespace: default
spec:
  selector:
    matchLabels:
      app: intel-xpumanager
  template:
    metadata:
      labels:
        app: intel-xpumanager
    spec:
      containers:
      - args:
        - /usr/local/xpum/py/DGM.py
        command:
        - /usr/bin/python3
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SPDLOG_LEVEL
          value: trace
        image: ccr-registry.caas.intel.com/dms/intel-xpumanager:20210902.100747-1ef2cb7f
        imagePullPolicy: IfNotPresent
        name: intel-xpumanager
        ports:
        - containerPort: 30000
          name: metrics
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /dev/dri
          name: devfs
          readOnly: true
        - mountPath: /sys/class/drm
          name: sysfs
          readOnly: true
        - mountPath: /var/lib/kubelet/device-plugins
          name: kubeletsockets
        - mountPath: /var/lib/kubelet/pod-resources
          name: kubeletpodres
      imagePullSecrets:
      - name: docker-config-secret
      nodeSelector:
        intel-gpu: "true"
        kubernetes.io/arch: amd64
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /dev/dri
          type: ""
        name: devfs
      - hostPath:
          path: /sys/class/drm
          type: ""
        name: sysfs
      - hostPath:
          path: /var/lib/kubelet/device-plugins
          type: ""
        name: kubeletsockets
      - hostPath:
          path: /var/lib/kubelet/pod-resources
          type: ""
        name: kubeletpodres
