{
 "title": "Intel XPU Manager Exporter",
 "tags": [ "xpum" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(xpum_power_watts, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "xpum_gpu_ratio{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "GPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "xpum_gpu_frequency_mhz{node=\"$Node\"}*1000000"
    }
   ]
  },
  {
   "title": "GPU Temeperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "xpum_gpu_temeperature_celsius{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "xpum_power_watts{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "xpum_energy_joules_total{node=\"$Node\"}/1000"
    }
   ]
  },
  {
   "title": "Memory Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xpum_memory_write_bytes_total{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xpum_memory_used_bytes{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Memory Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xpum_memory_read_bytes_total{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Cache Errors Correctable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "xpum_cache_errors_correctable_total{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Cache Errors Uncorrectable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "xpum_cache_errors_uncorrectable_total{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Display Errors Correctable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "xpum_display_errors_correctable_total{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Display Errors Uncorrectable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "xpum_display_errors_uncorrectable_total{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Driver Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "xpum_driver_errors_total{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Programming Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "xpum_programming_errors_total{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Reset Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "xpum_resets_total{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Issue Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "xpum_issue_efficiency_ratio{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Occupation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "xpum_occupation_ratio{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Engine Group Compute All Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "xpum_engine_group_compute_all_ratio{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Execution Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "xpum_execution_efficiency_ratio{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Non Occupation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "xpum_non_occupation_ratio{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Engine Group Copy All Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "xpum_engine_group_copy_all_ratio{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "xpum_memory_bandwidth_ratio{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "xpum_memory_ratio{node=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Engine Group Media All Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "xpum_engine_group_media_all_ratio{node=\"$Node\"}"
    }
   ]
  }
 ]
}