// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/scraper/scrapertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := scrapertest.NewNopSettings(scrapertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0
			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwEnergyDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.sensor_location-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwErrorsDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", AttributeHwTypeFrequency, AttributeErrorTypeCorrectable, "error.category-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwFrequencyDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.frequency.domain-val", AttributeAggregationMin)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwFrequencyLimitDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.frequency.domain-val", "hw.limit_type-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwFrequencyRequestDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.frequency.domain-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwFrequencySamplesDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.frequency.domain-val", AttributeSampleStatusCollected)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwFrequencyThrottleStatusDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.frequency.domain-val", "com.intel.speed.throttle_reason-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwGpuBandwidthLimitDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwGpuBandwidthUtilizationDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwGpuInfoDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "pci.vendor_id-val", "pci.device_id-val", "hw.model-val", "hw.serial_number-val", "hw.vendor-val", "hw.firmware_version-val", AttributeHwGpuTypeDiscrete, 25, "pci.lanes-val", "pci.link_gen-val", false, AttributeHwMemoryEccAvailable)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwGpuIoDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", AttributeNetworkIoDirectionReceive)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwGpuIoRateDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwGpuUtilizationDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.gpu.task-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwMemoryBandwidthLimitDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.memory.location-val", "hw.memory.type-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwMemoryBandwidthUtilizationDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.memory.location-val", "hw.memory.type-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwMemoryFreeDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.memory.location-val", "hw.memory.type-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwMemoryIoDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.memory.location-val", "hw.memory.type-val", AttributeNetworkIoDirectionReceive)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwMemoryIoRateDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.memory.location-val", "hw.memory.type-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwMemorySizeDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.memory.location-val", "hw.memory.type-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwMemoryUsageDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.memory.location-val", "hw.memory.type-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwMemoryUtilizationDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.memory.location-val", "hw.memory.type-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwPowerDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.sensor_location-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwPowerLimitDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.sensor_location-val", "com.intel.power.limit.level-val", "com.intel.power.limit.source-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwStatusDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.state-val", AttributeHwTypeFrequency)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwTemperatureDataPoint(ts, 1, "hw.id-val", "hw.name-val", "pci.bdf-val", "com.intel.subdevice_id-val", "hw.sensor_location-val", AttributeStatisticMin)

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "hw.energy":
					assert.False(t, validatedMetrics["hw.energy"], "Found a duplicate in the metrics slice: hw.energy")
					validatedMetrics["hw.energy"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Energy consumed by the hardware component.", mi.Description())
					assert.Equal(t, "J", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwSensorLocationAttrVal, ok := dp.Attributes().Get("hw.sensor_location")
					assert.True(t, ok)
					assert.Equal(t, "hw.sensor_location-val", hwSensorLocationAttrVal.Str())
				case "hw.errors":
					assert.False(t, validatedMetrics["hw.errors"], "Found a duplicate in the metrics slice: hw.errors")
					validatedMetrics["hw.errors"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of GPU errors. Correctable `error.type` error metrics are reported only when non-zero.", mi.Description())
					assert.Equal(t, "{error}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwTypeAttrVal, ok := dp.Attributes().Get("hw.type")
					assert.True(t, ok)
					assert.Equal(t, "frequency", hwTypeAttrVal.Str())
					errorTypeAttrVal, ok := dp.Attributes().Get("error.type")
					assert.True(t, ok)
					assert.Equal(t, "correctable", errorTypeAttrVal.Str())
					errorCategoryAttrVal, ok := dp.Attributes().Get("error.category")
					assert.True(t, ok)
					assert.Equal(t, "error.category-val", errorCategoryAttrVal.Str())
				case "hw.frequency":
					assert.False(t, validatedMetrics["hw.frequency"], "Found a duplicate in the metrics slice: hw.frequency")
					validatedMetrics["hw.frequency"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Operating frequency of the hardware component.", mi.Description())
					assert.Equal(t, "Hz", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwFrequencyDomainAttrVal, ok := dp.Attributes().Get("hw.frequency.domain")
					assert.True(t, ok)
					assert.Equal(t, "hw.frequency.domain-val", hwFrequencyDomainAttrVal.Str())
					aggregationAttrVal, ok := dp.Attributes().Get("aggregation")
					assert.True(t, ok)
					assert.Equal(t, "min", aggregationAttrVal.Str())
				case "hw.frequency.limit":
					assert.False(t, validatedMetrics["hw.frequency.limit"], "Found a duplicate in the metrics slice: hw.frequency.limit")
					validatedMetrics["hw.frequency.limit"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Frequency limit in Hertz.", mi.Description())
					assert.Equal(t, "Hz", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwFrequencyDomainAttrVal, ok := dp.Attributes().Get("hw.frequency.domain")
					assert.True(t, ok)
					assert.Equal(t, "hw.frequency.domain-val", hwFrequencyDomainAttrVal.Str())
					hwLimitTypeAttrVal, ok := dp.Attributes().Get("hw.limit_type")
					assert.True(t, ok)
					assert.Equal(t, "hw.limit_type-val", hwLimitTypeAttrVal.Str())
				case "hw.frequency.request":
					assert.False(t, validatedMetrics["hw.frequency.request"], "Found a duplicate in the metrics slice: hw.frequency.request")
					validatedMetrics["hw.frequency.request"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Requested operating frequency.", mi.Description())
					assert.Equal(t, "Hz", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwFrequencyDomainAttrVal, ok := dp.Attributes().Get("hw.frequency.domain")
					assert.True(t, ok)
					assert.Equal(t, "hw.frequency.domain-val", hwFrequencyDomainAttrVal.Str())
				case "hw.frequency.samples":
					assert.False(t, validatedMetrics["hw.frequency.samples"], "Found a duplicate in the metrics slice: hw.frequency.samples")
					validatedMetrics["hw.frequency.samples"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of frequency samples during the last collection interval.", mi.Description())
					assert.Equal(t, "{count}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwFrequencyDomainAttrVal, ok := dp.Attributes().Get("hw.frequency.domain")
					assert.True(t, ok)
					assert.Equal(t, "hw.frequency.domain-val", hwFrequencyDomainAttrVal.Str())
					sampleStatusAttrVal, ok := dp.Attributes().Get("sample.status")
					assert.True(t, ok)
					assert.Equal(t, "collected", sampleStatusAttrVal.Str())
				case "hw.frequency.throttle_status":
					assert.False(t, validatedMetrics["hw.frequency.throttle_status"], "Found a duplicate in the metrics slice: hw.frequency.throttle_status")
					validatedMetrics["hw.frequency.throttle_status"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Hardware component frequency throttle status.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.False(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwFrequencyDomainAttrVal, ok := dp.Attributes().Get("hw.frequency.domain")
					assert.True(t, ok)
					assert.Equal(t, "hw.frequency.domain-val", hwFrequencyDomainAttrVal.Str())
					comIntelSpeedThrottleReasonAttrVal, ok := dp.Attributes().Get("com.intel.speed.throttle_reason")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.speed.throttle_reason-val", comIntelSpeedThrottleReasonAttrVal.Str())
				case "hw.gpu.bandwidth.limit":
					assert.False(t, validatedMetrics["hw.gpu.bandwidth.limit"], "Found a duplicate in the metrics slice: hw.gpu.bandwidth.limit")
					validatedMetrics["hw.gpu.bandwidth.limit"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Maximum (read+write) PCI bandwidth in bytes/sec for the GPU device.", mi.Description())
					assert.Equal(t, "By/s", mi.Unit())
					assert.False(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
				case "hw.gpu.bandwidth.utilization":
					assert.False(t, validatedMetrics["hw.gpu.bandwidth.utilization"], "Found a duplicate in the metrics slice: hw.gpu.bandwidth.utilization")
					validatedMetrics["hw.gpu.bandwidth.utilization"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "GPU device (read+write) PCI bandwidth utilization ratio.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
				case "hw.gpu.info":
					assert.False(t, validatedMetrics["hw.gpu.info"], "Found a duplicate in the metrics slice: hw.gpu.info")
					validatedMetrics["hw.gpu.info"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Information about the GPU device.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.False(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					pciVendorIDAttrVal, ok := dp.Attributes().Get("pci.vendor_id")
					assert.True(t, ok)
					assert.Equal(t, "pci.vendor_id-val", pciVendorIDAttrVal.Str())
					pciDeviceIDAttrVal, ok := dp.Attributes().Get("pci.device_id")
					assert.True(t, ok)
					assert.Equal(t, "pci.device_id-val", pciDeviceIDAttrVal.Str())
					hwModelAttrVal, ok := dp.Attributes().Get("hw.model")
					assert.True(t, ok)
					assert.Equal(t, "hw.model-val", hwModelAttrVal.Str())
					hwSerialNumberAttrVal, ok := dp.Attributes().Get("hw.serial_number")
					assert.True(t, ok)
					assert.Equal(t, "hw.serial_number-val", hwSerialNumberAttrVal.Str())
					hwVendorAttrVal, ok := dp.Attributes().Get("hw.vendor")
					assert.True(t, ok)
					assert.Equal(t, "hw.vendor-val", hwVendorAttrVal.Str())
					hwFirmwareVersionAttrVal, ok := dp.Attributes().Get("hw.firmware_version")
					assert.True(t, ok)
					assert.Equal(t, "hw.firmware_version-val", hwFirmwareVersionAttrVal.Str())
					hwGpuTypeAttrVal, ok := dp.Attributes().Get("hw.gpu.type")
					assert.True(t, ok)
					assert.Equal(t, "discrete", hwGpuTypeAttrVal.Str())
					comIntelSubdeviceCountAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_count")
					assert.True(t, ok)
					assert.EqualValues(t, 25, comIntelSubdeviceCountAttrVal.Int())
					pciLanesAttrVal, ok := dp.Attributes().Get("pci.lanes")
					assert.True(t, ok)
					assert.Equal(t, "pci.lanes-val", pciLanesAttrVal.Str())
					pciLinkGenAttrVal, ok := dp.Attributes().Get("pci.link_gen")
					assert.True(t, ok)
					assert.Equal(t, "pci.link_gen-val", pciLinkGenAttrVal.Str())
					hwMemoryDemandPagingAttrVal, ok := dp.Attributes().Get("hw.memory.demand_paging")
					assert.True(t, ok)
					assert.False(t, hwMemoryDemandPagingAttrVal.Bool())
					hwMemoryEccAttrVal, ok := dp.Attributes().Get("hw.memory.ecc")
					assert.True(t, ok)
					assert.Equal(t, "available", hwMemoryEccAttrVal.Str())
				case "hw.gpu.io":
					assert.False(t, validatedMetrics["hw.gpu.io"], "Found a duplicate in the metrics slice: hw.gpu.io")
					validatedMetrics["hw.gpu.io"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Bytes received / transmitted over PCI bus by the GPU device.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					networkIoDirectionAttrVal, ok := dp.Attributes().Get("network.io.direction")
					assert.True(t, ok)
					assert.Equal(t, "receive", networkIoDirectionAttrVal.Str())
				case "hw.gpu.io.rate":
					assert.False(t, validatedMetrics["hw.gpu.io.rate"], "Found a duplicate in the metrics slice: hw.gpu.io.rate")
					validatedMetrics["hw.gpu.io.rate"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Current (read+write) PCI bandwidth usage in bytes/sec for the GPU device.", mi.Description())
					assert.Equal(t, "By/s", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
				case "hw.gpu.utilization":
					assert.False(t, validatedMetrics["hw.gpu.utilization"], "Found a duplicate in the metrics slice: hw.gpu.utilization")
					validatedMetrics["hw.gpu.utilization"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "GPU engine / task pipeline utilization ratio.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwGpuTaskAttrVal, ok := dp.Attributes().Get("hw.gpu.task")
					assert.True(t, ok)
					assert.Equal(t, "hw.gpu.task-val", hwGpuTaskAttrVal.Str())
				case "hw.memory.bandwidth.limit":
					assert.False(t, validatedMetrics["hw.memory.bandwidth.limit"], "Found a duplicate in the metrics slice: hw.memory.bandwidth.limit")
					validatedMetrics["hw.memory.bandwidth.limit"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Maximum total memory (read+write) bandwidth in bytes/sec.", mi.Description())
					assert.Equal(t, "By/s", mi.Unit())
					assert.False(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwMemoryLocationAttrVal, ok := dp.Attributes().Get("hw.memory.location")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.location-val", hwMemoryLocationAttrVal.Str())
					hwMemoryTypeAttrVal, ok := dp.Attributes().Get("hw.memory.type")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.type-val", hwMemoryTypeAttrVal.Str())
				case "hw.memory.bandwidth.utilization":
					assert.False(t, validatedMetrics["hw.memory.bandwidth.utilization"], "Found a duplicate in the metrics slice: hw.memory.bandwidth.utilization")
					validatedMetrics["hw.memory.bandwidth.utilization"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Memory bandwidth (read+write) utilization ratio.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwMemoryLocationAttrVal, ok := dp.Attributes().Get("hw.memory.location")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.location-val", hwMemoryLocationAttrVal.Str())
					hwMemoryTypeAttrVal, ok := dp.Attributes().Get("hw.memory.type")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.type-val", hwMemoryTypeAttrVal.Str())
				case "hw.memory.free":
					assert.False(t, validatedMetrics["hw.memory.free"], "Found a duplicate in the metrics slice: hw.memory.free")
					validatedMetrics["hw.memory.free"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Free memory. Reported only when `hw.memory.size` (and memory usage metrics) are unavailable.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					assert.False(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwMemoryLocationAttrVal, ok := dp.Attributes().Get("hw.memory.location")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.location-val", hwMemoryLocationAttrVal.Str())
					hwMemoryTypeAttrVal, ok := dp.Attributes().Get("hw.memory.type")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.type-val", hwMemoryTypeAttrVal.Str())
				case "hw.memory.io":
					assert.False(t, validatedMetrics["hw.memory.io"], "Found a duplicate in the metrics slice: hw.memory.io")
					validatedMetrics["hw.memory.io"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Bytes read from / written to memory.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwMemoryLocationAttrVal, ok := dp.Attributes().Get("hw.memory.location")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.location-val", hwMemoryLocationAttrVal.Str())
					hwMemoryTypeAttrVal, ok := dp.Attributes().Get("hw.memory.type")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.type-val", hwMemoryTypeAttrVal.Str())
					networkIoDirectionAttrVal, ok := dp.Attributes().Get("network.io.direction")
					assert.True(t, ok)
					assert.Equal(t, "receive", networkIoDirectionAttrVal.Str())
				case "hw.memory.io.rate":
					assert.False(t, validatedMetrics["hw.memory.io.rate"], "Found a duplicate in the metrics slice: hw.memory.io.rate")
					validatedMetrics["hw.memory.io.rate"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Current memory bandwidth (read+write) usage in bytes/sec.", mi.Description())
					assert.Equal(t, "By/s", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwMemoryLocationAttrVal, ok := dp.Attributes().Get("hw.memory.location")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.location-val", hwMemoryLocationAttrVal.Str())
					hwMemoryTypeAttrVal, ok := dp.Attributes().Get("hw.memory.type")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.type-val", hwMemoryTypeAttrVal.Str())
				case "hw.memory.size":
					assert.False(t, validatedMetrics["hw.memory.size"], "Found a duplicate in the metrics slice: hw.memory.size")
					validatedMetrics["hw.memory.size"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Physical size of the memory.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					assert.False(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwMemoryLocationAttrVal, ok := dp.Attributes().Get("hw.memory.location")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.location-val", hwMemoryLocationAttrVal.Str())
					hwMemoryTypeAttrVal, ok := dp.Attributes().Get("hw.memory.type")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.type-val", hwMemoryTypeAttrVal.Str())
				case "hw.memory.usage":
					assert.False(t, validatedMetrics["hw.memory.usage"], "Found a duplicate in the metrics slice: hw.memory.usage")
					validatedMetrics["hw.memory.usage"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Memory used.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					assert.False(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwMemoryLocationAttrVal, ok := dp.Attributes().Get("hw.memory.location")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.location-val", hwMemoryLocationAttrVal.Str())
					hwMemoryTypeAttrVal, ok := dp.Attributes().Get("hw.memory.type")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.type-val", hwMemoryTypeAttrVal.Str())
				case "hw.memory.utilization":
					assert.False(t, validatedMetrics["hw.memory.utilization"], "Found a duplicate in the metrics slice: hw.memory.utilization")
					validatedMetrics["hw.memory.utilization"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Memory utilization ratio.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwMemoryLocationAttrVal, ok := dp.Attributes().Get("hw.memory.location")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.location-val", hwMemoryLocationAttrVal.Str())
					hwMemoryTypeAttrVal, ok := dp.Attributes().Get("hw.memory.type")
					assert.True(t, ok)
					assert.Equal(t, "hw.memory.type-val", hwMemoryTypeAttrVal.Str())
				case "hw.power":
					assert.False(t, validatedMetrics["hw.power"], "Found a duplicate in the metrics slice: hw.power")
					validatedMetrics["hw.power"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Instantaneous power usage of the hardware component.", mi.Description())
					assert.Equal(t, "W", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwSensorLocationAttrVal, ok := dp.Attributes().Get("hw.sensor_location")
					assert.True(t, ok)
					assert.Equal(t, "hw.sensor_location-val", hwSensorLocationAttrVal.Str())
				case "hw.power.limit":
					assert.False(t, validatedMetrics["hw.power.limit"], "Found a duplicate in the metrics slice: hw.power.limit")
					validatedMetrics["hw.power.limit"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Power usage limit for the hardware component.", mi.Description())
					assert.Equal(t, "W", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwSensorLocationAttrVal, ok := dp.Attributes().Get("hw.sensor_location")
					assert.True(t, ok)
					assert.Equal(t, "hw.sensor_location-val", hwSensorLocationAttrVal.Str())
					comIntelPowerLimitLevelAttrVal, ok := dp.Attributes().Get("com.intel.power.limit.level")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.power.limit.level-val", comIntelPowerLimitLevelAttrVal.Str())
					comIntelPowerLimitSourceAttrVal, ok := dp.Attributes().Get("com.intel.power.limit.source")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.power.limit.source-val", comIntelPowerLimitSourceAttrVal.Str())
				case "hw.status":
					assert.False(t, validatedMetrics["hw.status"], "Found a duplicate in the metrics slice: hw.status")
					validatedMetrics["hw.status"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Known hardware component states. Problem state reporting starts after issue becomes known / active for the first time (to greatly reduce number of state metrics). Unknown state is reported only if state was known before.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.False(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwStateAttrVal, ok := dp.Attributes().Get("hw.state")
					assert.True(t, ok)
					assert.Equal(t, "hw.state-val", hwStateAttrVal.Str())
					hwTypeAttrVal, ok := dp.Attributes().Get("hw.type")
					assert.True(t, ok)
					assert.Equal(t, "frequency", hwTypeAttrVal.Str())
				case "hw.temperature":
					assert.False(t, validatedMetrics["hw.temperature"], "Found a duplicate in the metrics slice: hw.temperature")
					validatedMetrics["hw.temperature"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Temperature of the hardware component in degrees Celsius.", mi.Description())
					assert.Equal(t, "Cel", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
					assert.True(t, ok)
					assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
					assert.True(t, ok)
					assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					pciBdfAttrVal, ok := dp.Attributes().Get("pci.bdf")
					assert.True(t, ok)
					assert.Equal(t, "pci.bdf-val", pciBdfAttrVal.Str())
					comIntelSubdeviceIDAttrVal, ok := dp.Attributes().Get("com.intel.subdevice_id")
					assert.True(t, ok)
					assert.Equal(t, "com.intel.subdevice_id-val", comIntelSubdeviceIDAttrVal.Str())
					hwSensorLocationAttrVal, ok := dp.Attributes().Get("hw.sensor_location")
					assert.True(t, ok)
					assert.Equal(t, "hw.sensor_location-val", hwSensorLocationAttrVal.Str())
					statisticAttrVal, ok := dp.Attributes().Get("statistic")
					assert.True(t, ok)
					assert.Equal(t, "min", statisticAttrVal.Str())
				}
			}
		})
	}
}
