// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					HwEnergy: MetricConfig{
						Enabled: true,
					},
					HwErrors: MetricConfig{
						Enabled: true,
					},
					HwFrequency: MetricConfig{
						Enabled: true,
					},
					HwFrequencyLimit: MetricConfig{
						Enabled: true,
					},
					HwFrequencyRequest: MetricConfig{
						Enabled: true,
					},
					HwFrequencySamples: MetricConfig{
						Enabled: true,
					},
					HwFrequencyThrottleStatus: MetricConfig{
						Enabled: true,
					},
					HwGpuBandwidthLimit: MetricConfig{
						Enabled: true,
					},
					HwGpuBandwidthUtilization: MetricConfig{
						Enabled: true,
					},
					HwGpuInfo: MetricConfig{
						Enabled: true,
					},
					HwGpuIo: MetricConfig{
						Enabled: true,
					},
					HwGpuIoRate: MetricConfig{
						Enabled: true,
					},
					HwGpuUtilization: MetricConfig{
						Enabled: true,
					},
					HwMemoryBandwidthLimit: MetricConfig{
						Enabled: true,
					},
					HwMemoryBandwidthUtilization: MetricConfig{
						Enabled: true,
					},
					HwMemoryFree: MetricConfig{
						Enabled: true,
					},
					HwMemoryIo: MetricConfig{
						Enabled: true,
					},
					HwMemoryIoRate: MetricConfig{
						Enabled: true,
					},
					HwMemorySize: MetricConfig{
						Enabled: true,
					},
					HwMemoryUsage: MetricConfig{
						Enabled: true,
					},
					HwMemoryUtilization: MetricConfig{
						Enabled: true,
					},
					HwPower: MetricConfig{
						Enabled: true,
					},
					HwPowerLimit: MetricConfig{
						Enabled: true,
					},
					HwStatus: MetricConfig{
						Enabled: true,
					},
					HwTemperature: MetricConfig{
						Enabled: true,
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					HwEnergy: MetricConfig{
						Enabled: false,
					},
					HwErrors: MetricConfig{
						Enabled: false,
					},
					HwFrequency: MetricConfig{
						Enabled: false,
					},
					HwFrequencyLimit: MetricConfig{
						Enabled: false,
					},
					HwFrequencyRequest: MetricConfig{
						Enabled: false,
					},
					HwFrequencySamples: MetricConfig{
						Enabled: false,
					},
					HwFrequencyThrottleStatus: MetricConfig{
						Enabled: false,
					},
					HwGpuBandwidthLimit: MetricConfig{
						Enabled: false,
					},
					HwGpuBandwidthUtilization: MetricConfig{
						Enabled: false,
					},
					HwGpuInfo: MetricConfig{
						Enabled: false,
					},
					HwGpuIo: MetricConfig{
						Enabled: false,
					},
					HwGpuIoRate: MetricConfig{
						Enabled: false,
					},
					HwGpuUtilization: MetricConfig{
						Enabled: false,
					},
					HwMemoryBandwidthLimit: MetricConfig{
						Enabled: false,
					},
					HwMemoryBandwidthUtilization: MetricConfig{
						Enabled: false,
					},
					HwMemoryFree: MetricConfig{
						Enabled: false,
					},
					HwMemoryIo: MetricConfig{
						Enabled: false,
					},
					HwMemoryIoRate: MetricConfig{
						Enabled: false,
					},
					HwMemorySize: MetricConfig{
						Enabled: false,
					},
					HwMemoryUsage: MetricConfig{
						Enabled: false,
					},
					HwMemoryUtilization: MetricConfig{
						Enabled: false,
					},
					HwPower: MetricConfig{
						Enabled: false,
					},
					HwPowerLimit: MetricConfig{
						Enabled: false,
					},
					HwStatus: MetricConfig{
						Enabled: false,
					},
					HwTemperature: MetricConfig{
						Enabled: false,
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
