// Copyright (C) 2019-2025 Intel Corporation
//
// SPDX-License-Identifier: MIT
//

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 08:49:30 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package levelzero

/*
#cgo pkg-config: level-zero
#include "ze_api.h"
#include "zes_api.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

type ZeDriverHandle C.ze_driver_handle_t

type ZeDeviceHandle C.ze_device_handle_t

type ZesDriverHandle C.ze_driver_handle_t

type ZesDeviceHandle C.ze_device_handle_t

type ZesSchedHandle C.zes_sched_handle_t

type ZesPerfHandle C.zes_perf_handle_t

type ZesPwrHandle C.zes_pwr_handle_t

type ZesFreqHandle C.zes_freq_handle_t

type ZesEngineHandle C.zes_engine_handle_t

type ZesStandbyHandle C.zes_standby_handle_t

type ZesFirmwareHandle C.zes_firmware_handle_t

type ZesMemHandle C.zes_mem_handle_t

type ZesFabricPortHandle C.zes_fabric_port_handle_t

type ZesTempHandle C.zes_temp_handle_t

type ZesPsuHandle C.zes_psu_handle_t

type ZesFanHandle C.zes_fan_handle_t

type ZesLedHandle C.zes_led_handle_t

type ZesRasHandle C.zes_ras_handle_t

type ZesDiagHandle C.zes_diag_handle_t

type ZesOverclockHandle C.zes_overclock_handle_t

type ZesVfHandle C.zes_vf_handle_t
