// Copyright (C) 2019-2025 Intel Corporation
//
// SPDX-License-Identifier: MIT
//

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package levelzero

/*
#cgo pkg-config: level-zero
#include "ze_api.h"
#include "zes_api.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// ZeDeviceUuid as declared in levelzero/ze_api.h:527
type ZeDeviceUuid struct {
	Id             [16]byte
	refa3888c5f    *C.ze_device_uuid_t
	allocsa3888c5f interface{}
}

// ZeDeviceProperties as declared in levelzero/ze_api.h:531
type ZeDeviceProperties struct {
	PNext                    unsafe.Pointer
	VendorId                 uint32
	DeviceId                 uint32
	Flags                    uint32
	SubdeviceId              uint32
	CoreClockRate            uint32
	MaxMemAllocSize          uint64
	MaxHardwareContexts      uint32
	MaxCommandQueuePriority  uint32
	NumThreadsPerEU          uint32
	PhysicalEUSimdWidth      uint32
	NumEUsPerSubslice        uint32
	NumSubslicesPerSlice     uint32
	NumSlices                uint32
	TimerResolution          uint64
	TimestampValidBits       uint32
	KernelTimestampValidBits uint32
	Uuid                     ZeDeviceUuid
	Name                     [256]byte
	refc53d3fb4              *C.ze_device_properties_t
	allocsc53d3fb4           interface{}
}

// ZesDriverExtensionProperties as declared in levelzero/zes_api.h:242
type ZesDriverExtensionProperties struct {
	Name           [256]byte
	Version        uint32
	ref42ed1ab0    *C.zes_driver_extension_properties_t
	allocs42ed1ab0 interface{}
}

// ZesDeviceState as declared in levelzero/zes_api.h:246
type ZesDeviceState struct {
	PNext          unsafe.Pointer
	Reset          ZesResetReasonFlags
	Repaired       ZesRepairStatus
	reff8086b4a    *C.zes_device_state_t
	allocsf8086b4a interface{}
}

// ZesResetProperties as declared in levelzero/zes_api.h:250
type ZesResetProperties struct {
	PNext          unsafe.Pointer
	Force          byte
	ResetType      ZesResetType
	refd3539db9    *C.zes_reset_properties_t
	allocsd3539db9 interface{}
}

// ZesUuid as declared in levelzero/zes_api.h:254
type ZesUuid struct {
	Id             [16]byte
	refea316ae7    *C.zes_uuid_t
	allocsea316ae7 interface{}
}

// ZesDeviceProperties as declared in levelzero/zes_api.h:258
type ZesDeviceProperties struct {
	PNext          unsafe.Pointer
	Core           ZeDeviceProperties
	NumSubdevices  uint32
	SerialNumber   [64]byte
	BoardNumber    [64]byte
	BrandName      [64]byte
	ModelName      [64]byte
	VendorName     [64]byte
	DriverVersion  [64]byte
	ref3c72ec10    *C.zes_device_properties_t
	allocs3c72ec10 interface{}
}

// ZesDeviceExtProperties as declared in levelzero/zes_api.h:262
type ZesDeviceExtProperties struct {
	PNext          unsafe.Pointer
	Uuid           ZesUuid
	Type           ZesDeviceType
	Flags          ZesDevicePropertyFlags
	ref8dc85d46    *C.zes_device_ext_properties_t
	allocs8dc85d46 interface{}
}

// ZesProcessState as declared in levelzero/zes_api.h:266
type ZesProcessState struct {
	PNext          unsafe.Pointer
	ProcessId      uint32
	MemSize        uint64
	SharedSize     uint64
	Engines        ZesEngineTypeFlags
	ref86d3f75d    *C.zes_process_state_t
	allocs86d3f75d interface{}
}

// ZesPciAddress as declared in levelzero/zes_api.h:270
type ZesPciAddress struct {
	Domain        uint32
	Bus           uint32
	Device        uint32
	Function      uint32
	refe61e2de    *C.zes_pci_address_t
	allocse61e2de interface{}
}

// ZesPciSpeed as declared in levelzero/zes_api.h:274
type ZesPciSpeed struct {
	Gen            int32
	Width          int32
	MaxBandwidth   int64
	refe1060402    *C.zes_pci_speed_t
	allocse1060402 interface{}
}

// ZesPciProperties as declared in levelzero/zes_api.h:278
type ZesPciProperties struct {
	PNext                 unsafe.Pointer
	Address               ZesPciAddress
	MaxSpeed              ZesPciSpeed
	HaveBandwidthCounters byte
	HavePacketCounters    byte
	HaveReplayCounters    byte
	ref6809198b           *C.zes_pci_properties_t
	allocs6809198b        interface{}
}

// ZesPciState as declared in levelzero/zes_api.h:282
type ZesPciState struct {
	PNext           unsafe.Pointer
	Status          ZesPciLinkStatus
	QualityIssues   ZesPciLinkQualIssueFlags
	StabilityIssues ZesPciLinkStabIssueFlags
	Speed           ZesPciSpeed
	ref6670ba19     *C.zes_pci_state_t
	allocs6670ba19  interface{}
}

// ZesPciBarProperties as declared in levelzero/zes_api.h:286
type ZesPciBarProperties struct {
	PNext          unsafe.Pointer
	Type           ZesPciBarType
	Index          uint32
	Base           uint64
	Size           uint64
	refc36084eb    *C.zes_pci_bar_properties_t
	allocsc36084eb interface{}
}

// ZesPciBarProperties12 as declared in levelzero/zes_api.h:290
type ZesPciBarProperties12 struct {
	PNext                 unsafe.Pointer
	Type                  ZesPciBarType
	Index                 uint32
	Base                  uint64
	Size                  uint64
	ResizableBarSupported byte
	ResizableBarEnabled   byte
	refef4f5f59           *C.zes_pci_bar_properties_1_2_t
	allocsef4f5f59        interface{}
}

// ZesPciStats as declared in levelzero/zes_api.h:294
type ZesPciStats struct {
	Timestamp      uint64
	ReplayCounter  uint64
	PacketCounter  uint64
	RxCounter      uint64
	TxCounter      uint64
	Speed          ZesPciSpeed
	ref7edb65db    *C.zes_pci_stats_t
	allocs7edb65db interface{}
}

// ZesOverclockProperties as declared in levelzero/zes_api.h:298
type ZesOverclockProperties struct {
	PNext             unsafe.Pointer
	DomainType        ZesOverclockDomain
	AvailableControls uint32
	VFProgramType     ZesVfProgramType
	NumberOfVFPoints  uint32
	reff90ac3e3       *C.zes_overclock_properties_t
	allocsf90ac3e3    interface{}
}

// ZesControlProperty as declared in levelzero/zes_api.h:302
type ZesControlProperty struct {
	MinValue       float64
	MaxValue       float64
	StepValue      float64
	RefValue       float64
	DefaultValue   float64
	ref4d5f69ce    *C.zes_control_property_t
	allocs4d5f69ce interface{}
}

// ZesVfProperty as declared in levelzero/zes_api.h:306
type ZesVfProperty struct {
	MinFreq        float64
	MaxFreq        float64
	StepFreq       float64
	MinVolt        float64
	MaxVolt        float64
	StepVolt       float64
	ref4f4b8df0    *C.zes_vf_property_t
	allocs4f4b8df0 interface{}
}

// ZesDiagTest as declared in levelzero/zes_api.h:310
type ZesDiagTest struct {
	Index          uint32
	Name           [64]byte
	refff23739f    *C.zes_diag_test_t
	allocsff23739f interface{}
}

// ZesDiagProperties as declared in levelzero/zes_api.h:314
type ZesDiagProperties struct {
	PNext          unsafe.Pointer
	OnSubdevice    byte
	SubdeviceId    uint32
	Name           [64]byte
	HaveTests      byte
	ref486274a8    *C.zes_diag_properties_t
	allocs486274a8 interface{}
}

// ZesDeviceEccDesc as declared in levelzero/zes_api.h:318
type ZesDeviceEccDesc struct {
	PNext          unsafe.Pointer
	State          ZesDeviceEccState
	reffad09552    *C.zes_device_ecc_desc_t
	allocsfad09552 interface{}
}

// ZesDeviceEccProperties as declared in levelzero/zes_api.h:322
type ZesDeviceEccProperties struct {
	PNext          unsafe.Pointer
	CurrentState   ZesDeviceEccState
	PendingState   ZesDeviceEccState
	PendingAction  ZesDeviceAction
	ref1421f25b    *C.zes_device_ecc_properties_t
	allocs1421f25b interface{}
}

// ZesEngineProperties as declared in levelzero/zes_api.h:326
type ZesEngineProperties struct {
	PNext          unsafe.Pointer
	Type           ZesEngineGroup
	OnSubdevice    byte
	SubdeviceId    uint32
	ref7abe3f14    *C.zes_engine_properties_t
	allocs7abe3f14 interface{}
}

// ZesEngineStats as declared in levelzero/zes_api.h:330
type ZesEngineStats struct {
	ActiveTime     uint64
	Timestamp      uint64
	reff826c07e    *C.zes_engine_stats_t
	allocsf826c07e interface{}
}

// ZesFabricPortId as declared in levelzero/zes_api.h:334
type ZesFabricPortId struct {
	FabricId       uint32
	AttachId       uint32
	PortNumber     byte
	refb477fafb    *C.zes_fabric_port_id_t
	allocsb477fafb interface{}
}

// ZesFabricPortSpeed as declared in levelzero/zes_api.h:338
type ZesFabricPortSpeed struct {
	BitRate        int64
	Width          int32
	ref1baa2cad    *C.zes_fabric_port_speed_t
	allocs1baa2cad interface{}
}

// ZesFabricPortProperties as declared in levelzero/zes_api.h:342
type ZesFabricPortProperties struct {
	PNext          unsafe.Pointer
	Model          [256]byte
	OnSubdevice    byte
	SubdeviceId    uint32
	PortId         ZesFabricPortId
	MaxRxSpeed     ZesFabricPortSpeed
	MaxTxSpeed     ZesFabricPortSpeed
	refc1c93b2e    *C.zes_fabric_port_properties_t
	allocsc1c93b2e interface{}
}

// ZesFabricLinkType as declared in levelzero/zes_api.h:346
type ZesFabricLinkType struct {
	Desc          [256]byte
	ref5a2f1b2    *C.zes_fabric_link_type_t
	allocs5a2f1b2 interface{}
}

// ZesFabricPortConfig as declared in levelzero/zes_api.h:350
type ZesFabricPortConfig struct {
	PNext          unsafe.Pointer
	Enabled        byte
	Beaconing      byte
	ref433ee952    *C.zes_fabric_port_config_t
	allocs433ee952 interface{}
}

// ZesFabricPortState as declared in levelzero/zes_api.h:354
type ZesFabricPortState struct {
	PNext          unsafe.Pointer
	Status         ZesFabricPortStatus
	QualityIssues  ZesFabricPortQualIssueFlags
	FailureReasons ZesFabricPortFailureFlags
	RemotePortId   ZesFabricPortId
	RxSpeed        ZesFabricPortSpeed
	TxSpeed        ZesFabricPortSpeed
	ref9cdc92b6    *C.zes_fabric_port_state_t
	allocs9cdc92b6 interface{}
}

// ZesFabricPortThroughput as declared in levelzero/zes_api.h:358
type ZesFabricPortThroughput struct {
	Timestamp      uint64
	RxCounter      uint64
	TxCounter      uint64
	ref2a50efad    *C.zes_fabric_port_throughput_t
	allocs2a50efad interface{}
}

// ZesFabricPortErrorCounters as declared in levelzero/zes_api.h:362
type ZesFabricPortErrorCounters struct {
	PNext            unsafe.Pointer
	LinkFailureCount uint64
	FwCommErrorCount uint64
	FwErrorCount     uint64
	LinkDegradeCount uint64
	ref55fea7eb      *C.zes_fabric_port_error_counters_t
	allocs55fea7eb   interface{}
}

// ZesFanSpeed as declared in levelzero/zes_api.h:366
type ZesFanSpeed struct {
	Speed          int32
	Units          ZesFanSpeedUnits
	refc7d1b77e    *C.zes_fan_speed_t
	allocsc7d1b77e interface{}
}

// ZesFanTempSpeed as declared in levelzero/zes_api.h:370
type ZesFanTempSpeed struct {
	Temperature    uint32
	Speed          ZesFanSpeed
	ref65b83149    *C.zes_fan_temp_speed_t
	allocs65b83149 interface{}
}

// ZesFanSpeedTable as declared in levelzero/zes_api.h:374
type ZesFanSpeedTable struct {
	NumPoints      int32
	Table          [32]ZesFanTempSpeed
	ref5df80a33    *C.zes_fan_speed_table_t
	allocs5df80a33 interface{}
}

// ZesFanProperties as declared in levelzero/zes_api.h:378
type ZesFanProperties struct {
	PNext          unsafe.Pointer
	OnSubdevice    byte
	SubdeviceId    uint32
	CanControl     byte
	SupportedModes uint32
	SupportedUnits uint32
	MaxRPM         int32
	MaxPoints      int32
	ref10f455a0    *C.zes_fan_properties_t
	allocs10f455a0 interface{}
}

// ZesFanConfig as declared in levelzero/zes_api.h:382
type ZesFanConfig struct {
	PNext          unsafe.Pointer
	Mode           ZesFanSpeedMode
	SpeedFixed     ZesFanSpeed
	SpeedTable     ZesFanSpeedTable
	ref5c3811a7    *C.zes_fan_config_t
	allocs5c3811a7 interface{}
}

// ZesFirmwareProperties as declared in levelzero/zes_api.h:386
type ZesFirmwareProperties struct {
	PNext          unsafe.Pointer
	OnSubdevice    byte
	SubdeviceId    uint32
	CanControl     byte
	Name           [64]byte
	Version        [64]byte
	ref7dc19db1    *C.zes_firmware_properties_t
	allocs7dc19db1 interface{}
}

// ZesFreqProperties as declared in levelzero/zes_api.h:390
type ZesFreqProperties struct {
	PNext                    unsafe.Pointer
	Type                     ZesFreqDomain
	OnSubdevice              byte
	SubdeviceId              uint32
	CanControl               byte
	IsThrottleEventSupported byte
	Min                      float64
	Max                      float64
	ref34aee3f5              *C.zes_freq_properties_t
	allocs34aee3f5           interface{}
}

// ZesFreqRange as declared in levelzero/zes_api.h:394
type ZesFreqRange struct {
	Min            float64
	Max            float64
	ref2fe9f0de    *C.zes_freq_range_t
	allocs2fe9f0de interface{}
}

// ZesFreqState as declared in levelzero/zes_api.h:398
type ZesFreqState struct {
	PNext           unsafe.Pointer
	CurrentVoltage  float64
	Request         float64
	Tdp             float64
	Efficient       float64
	Actual          float64
	ThrottleReasons ZesFreqThrottleReasonFlags
	ref1a7907e2     *C.zes_freq_state_t
	allocs1a7907e2  interface{}
}

// ZesFreqThrottleTime as declared in levelzero/zes_api.h:402
type ZesFreqThrottleTime struct {
	ThrottleTime   uint64
	Timestamp      uint64
	refafcd8de8    *C.zes_freq_throttle_time_t
	allocsafcd8de8 interface{}
}

// ZesOcCapabilities as declared in levelzero/zes_api.h:406
type ZesOcCapabilities struct {
	PNext                      unsafe.Pointer
	IsOcSupported              byte
	MaxFactoryDefaultFrequency float64
	MaxFactoryDefaultVoltage   float64
	MaxOcFrequency             float64
	MinOcVoltageOffset         float64
	MaxOcVoltageOffset         float64
	MaxOcVoltage               float64
	IsTjMaxSupported           byte
	IsIccMaxSupported          byte
	IsHighVoltModeCapable      byte
	IsHighVoltModeEnabled      byte
	IsExtendedModeSupported    byte
	IsFixedModeSupported       byte
	ref74a303f1                *C.zes_oc_capabilities_t
	allocs74a303f1             interface{}
}

// ZesLedProperties as declared in levelzero/zes_api.h:410
type ZesLedProperties struct {
	PNext          unsafe.Pointer
	OnSubdevice    byte
	SubdeviceId    uint32
	CanControl     byte
	HaveRGB        byte
	refbc0c5074    *C.zes_led_properties_t
	allocsbc0c5074 interface{}
}

// ZesLedColor as declared in levelzero/zes_api.h:414
type ZesLedColor struct {
	Red            float64
	Green          float64
	Blue           float64
	ref56e3b449    *C.zes_led_color_t
	allocs56e3b449 interface{}
}

// ZesLedState as declared in levelzero/zes_api.h:418
type ZesLedState struct {
	PNext          unsafe.Pointer
	IsOn           byte
	Color          ZesLedColor
	ref3ecd7b05    *C.zes_led_state_t
	allocs3ecd7b05 interface{}
}

// ZesMemProperties as declared in levelzero/zes_api.h:422
type ZesMemProperties struct {
	PNext          unsafe.Pointer
	Type           ZesMemType
	OnSubdevice    byte
	SubdeviceId    uint32
	Location       ZesMemLoc
	PhysicalSize   uint64
	BusWidth       int32
	NumChannels    int32
	refbc323ea5    *C.zes_mem_properties_t
	allocsbc323ea5 interface{}
}

// ZesMemState as declared in levelzero/zes_api.h:426
type ZesMemState struct {
	PNext          unsafe.Pointer
	Health         ZesMemHealth
	Free           uint64
	Size           uint64
	ref53e0129e    *C.zes_mem_state_t
	allocs53e0129e interface{}
}

// ZesMemBandwidth as declared in levelzero/zes_api.h:430
type ZesMemBandwidth struct {
	ReadCounter    uint64
	WriteCounter   uint64
	MaxBandwidth   uint64
	Timestamp      uint64
	ref48c8c552    *C.zes_mem_bandwidth_t
	allocs48c8c552 interface{}
}

// ZesMemExtBandwidth as declared in levelzero/zes_api.h:434
type ZesMemExtBandwidth struct {
	MemoryTimestampValidBits uint32
	refda62138a              *C.zes_mem_ext_bandwidth_t
	allocsda62138a           interface{}
}

// ZesPerfProperties as declared in levelzero/zes_api.h:438
type ZesPerfProperties struct {
	PNext          unsafe.Pointer
	OnSubdevice    byte
	SubdeviceId    uint32
	Engines        ZesEngineTypeFlags
	ref43090d92    *C.zes_perf_properties_t
	allocs43090d92 interface{}
}

// ZesPowerProperties as declared in levelzero/zes_api.h:442
type ZesPowerProperties struct {
	PNext                      unsafe.Pointer
	OnSubdevice                byte
	SubdeviceId                uint32
	CanControl                 byte
	IsEnergyThresholdSupported byte
	DefaultLimit               int32
	MinLimit                   int32
	MaxLimit                   int32
	refc8582e52                *C.zes_power_properties_t
	allocsc8582e52             interface{}
}

// ZesPowerEnergyCounter as declared in levelzero/zes_api.h:446
type ZesPowerEnergyCounter struct {
	Energy         uint64
	Timestamp      uint64
	ref5bb58ddb    *C.zes_power_energy_counter_t
	allocs5bb58ddb interface{}
}

// ZesPowerSustainedLimit as declared in levelzero/zes_api.h:450
type ZesPowerSustainedLimit struct {
	Enabled        byte
	Power          int32
	Interval       int32
	ref79c02686    *C.zes_power_sustained_limit_t
	allocs79c02686 interface{}
}

// ZesPowerBurstLimit as declared in levelzero/zes_api.h:454
type ZesPowerBurstLimit struct {
	Enabled        byte
	Power          int32
	refee14a1c1    *C.zes_power_burst_limit_t
	allocsee14a1c1 interface{}
}

// ZesPowerPeakLimit as declared in levelzero/zes_api.h:458
type ZesPowerPeakLimit struct {
	PowerAC        int32
	PowerDC        int32
	ref5974a59b    *C.zes_power_peak_limit_t
	allocs5974a59b interface{}
}

// ZesEnergyThreshold as declared in levelzero/zes_api.h:462
type ZesEnergyThreshold struct {
	Enable         byte
	Threshold      float64
	ProcessId      uint32
	refbdb1eed1    *C.zes_energy_threshold_t
	allocsbdb1eed1 interface{}
}

// ZesPsuProperties as declared in levelzero/zes_api.h:466
type ZesPsuProperties struct {
	PNext          unsafe.Pointer
	OnSubdevice    byte
	SubdeviceId    uint32
	HaveFan        byte
	AmpLimit       int32
	ref602c2b85    *C.zes_psu_properties_t
	allocs602c2b85 interface{}
}

// ZesPsuState as declared in levelzero/zes_api.h:470
type ZesPsuState struct {
	PNext         unsafe.Pointer
	VoltStatus    ZesPsuVoltageStatus
	FanFailed     byte
	Temperature   int32
	Current       int32
	refb2a8a94    *C.zes_psu_state_t
	allocsb2a8a94 interface{}
}

// ZesRasProperties as declared in levelzero/zes_api.h:474
type ZesRasProperties struct {
	PNext          unsafe.Pointer
	Type           ZesRasErrorType
	OnSubdevice    byte
	SubdeviceId    uint32
	reff3aa6b8e    *C.zes_ras_properties_t
	allocsf3aa6b8e interface{}
}

// ZesRasState as declared in levelzero/zes_api.h:478
type ZesRasState struct {
	PNext         unsafe.Pointer
	Category      [7]uint64
	ref3071b0a    *C.zes_ras_state_t
	allocs3071b0a interface{}
}

// ZesRasConfig as declared in levelzero/zes_api.h:482
type ZesRasConfig struct {
	PNext              unsafe.Pointer
	TotalThreshold     uint64
	DetailedThresholds ZesRasState
	ref8176cd7c        *C.zes_ras_config_t
	allocs8176cd7c     interface{}
}

// ZesSchedProperties as declared in levelzero/zes_api.h:486
type ZesSchedProperties struct {
	PNext          unsafe.Pointer
	OnSubdevice    byte
	SubdeviceId    uint32
	CanControl     byte
	Engines        ZesEngineTypeFlags
	SupportedModes uint32
	ref417bb51f    *C.zes_sched_properties_t
	allocs417bb51f interface{}
}

// ZesSchedTimeoutProperties as declared in levelzero/zes_api.h:490
type ZesSchedTimeoutProperties struct {
	PNext           unsafe.Pointer
	WatchdogTimeout uint64
	refd89c4473     *C.zes_sched_timeout_properties_t
	allocsd89c4473  interface{}
}

// ZesSchedTimesliceProperties as declared in levelzero/zes_api.h:494
type ZesSchedTimesliceProperties struct {
	PNext          unsafe.Pointer
	Interval       uint64
	YieldTimeout   uint64
	refd80f7e74    *C.zes_sched_timeslice_properties_t
	allocsd80f7e74 interface{}
}

// ZesStandbyProperties as declared in levelzero/zes_api.h:498
type ZesStandbyProperties struct {
	PNext          unsafe.Pointer
	Type           ZesStandbyType
	OnSubdevice    byte
	SubdeviceId    uint32
	ref91648fd8    *C.zes_standby_properties_t
	allocs91648fd8 interface{}
}

// ZesTempProperties as declared in levelzero/zes_api.h:502
type ZesTempProperties struct {
	PNext                   unsafe.Pointer
	Type                    ZesTempSensors
	OnSubdevice             byte
	SubdeviceId             uint32
	MaxTemperature          float64
	IsCriticalTempSupported byte
	IsThreshold1Supported   byte
	IsThreshold2Supported   byte
	refbe9b0155             *C.zes_temp_properties_t
	allocsbe9b0155          interface{}
}

// ZesTempThreshold as declared in levelzero/zes_api.h:506
type ZesTempThreshold struct {
	EnableLowToHigh byte
	EnableHighToLow byte
	Threshold       float64
	ref6418eb9b     *C.zes_temp_threshold_t
	allocs6418eb9b  interface{}
}

// ZesTempConfig as declared in levelzero/zes_api.h:510
type ZesTempConfig struct {
	PNext          unsafe.Pointer
	EnableCritical byte
	Threshold1     ZesTempThreshold
	Threshold2     ZesTempThreshold
	refd66444b3    *C.zes_temp_config_t
	allocsd66444b3 interface{}
}

// ZesDeviceEccDefaultPropertiesExt as declared in levelzero/zes_api.h:514
type ZesDeviceEccDefaultPropertiesExt struct {
	PNext          unsafe.Pointer
	DefaultState   ZesDeviceEccState
	ref7d624515    *C.zes_device_ecc_default_properties_ext_t
	allocs7d624515 interface{}
}

// ZesPowerLimitExtDesc as declared in levelzero/zes_api.h:518
type ZesPowerLimitExtDesc struct {
	PNext               unsafe.Pointer
	Level               ZesPowerLevel
	Source              ZesPowerSource
	LimitUnit           ZesLimitUnit
	EnabledStateLocked  byte
	Enabled             byte
	IntervalValueLocked byte
	Interval            int32
	LimitValueLocked    byte
	Limit               int32
	refe722286a         *C.zes_power_limit_ext_desc_t
	allocse722286a      interface{}
}

// ZesPowerExtProperties as declared in levelzero/zes_api.h:522
type ZesPowerExtProperties struct {
	PNext          unsafe.Pointer
	Domain         ZesPowerDomain
	DefaultLimit   []ZesPowerLimitExtDesc
	reffb4575f3    *C.zes_power_ext_properties_t
	allocsfb4575f3 interface{}
}

// ZesEngineExtProperties as declared in levelzero/zes_api.h:526
type ZesEngineExtProperties struct {
	PNext                          unsafe.Pointer
	CountOfVirtualFunctionInstance uint32
	ref75953d9f                    *C.zes_engine_ext_properties_t
	allocs75953d9f                 interface{}
}

// ZesRasStateExp as declared in levelzero/zes_api.h:530
type ZesRasStateExp struct {
	Category       ZesRasErrorCategoryExp
	ErrorCounter   uint64
	ref45731e3b    *C.zes_ras_state_exp_t
	allocs45731e3b interface{}
}

// ZesMemPageOfflineStateExp as declared in levelzero/zes_api.h:534
type ZesMemPageOfflineStateExp struct {
	PNext                unsafe.Pointer
	MemoryPageOffline    uint32
	MaxMemoryPageOffline uint32
	refbe0e2118          *C.zes_mem_page_offline_state_exp_t
	allocsbe0e2118       interface{}
}

// ZesMemBandwidthCounterBitsExpProperties as declared in levelzero/zes_api.h:538
type ZesMemBandwidthCounterBitsExpProperties struct {
	PNext          unsafe.Pointer
	ValidBitsCount uint32
	refb32ab94b    *C.zes_mem_bandwidth_counter_bits_exp_properties_t
	allocsb32ab94b interface{}
}

// ZesPowerDomainExpProperties as declared in levelzero/zes_api.h:542
type ZesPowerDomainExpProperties struct {
	PNext          unsafe.Pointer
	PowerDomain    ZesPowerDomain
	refc98520d6    *C.zes_power_domain_exp_properties_t
	allocsc98520d6 interface{}
}

// ZesSubdeviceExpProperties as declared in levelzero/zes_api.h:546
type ZesSubdeviceExpProperties struct {
	PNext          unsafe.Pointer
	SubdeviceId    uint32
	Uuid           ZesUuid
	ref67c1f53b    *C.zes_subdevice_exp_properties_t
	allocs67c1f53b interface{}
}

// ZesVfExpProperties as declared in levelzero/zes_api.h:550
type ZesVfExpProperties struct {
	PNext          unsafe.Pointer
	Address        ZesPciAddress
	Uuid           ZesUuid
	Flags          ZesVfInfoUtilExpFlags
	ref21b202d6    *C.zes_vf_exp_properties_t
	allocs21b202d6 interface{}
}

// ZesVfUtilMemExp as declared in levelzero/zes_api.h:554
type ZesVfUtilMemExp struct {
	PNext          unsafe.Pointer
	MemTypeFlags   ZesVfInfoMemTypeExpFlags
	Free           uint64
	Size           uint64
	Timestamp      uint64
	ref362f756d    *C.zes_vf_util_mem_exp_t
	allocs362f756d interface{}
}

// ZesVfUtilEngineExp as declared in levelzero/zes_api.h:558
type ZesVfUtilEngineExp struct {
	PNext                unsafe.Pointer
	Type                 ZesEngineGroup
	ActiveCounterValue   uint64
	SamplingCounterValue uint64
	Timestamp            uint64
	ref1b973c5c          *C.zes_vf_util_engine_exp_t
	allocs1b973c5c       interface{}
}

// ZesVfExpCapabilities as declared in levelzero/zes_api.h:562
type ZesVfExpCapabilities struct {
	PNext           unsafe.Pointer
	Address         ZesPciAddress
	VfDeviceMemSize uint32
	VfID            uint32
	refb00c375      *C.zes_vf_exp_capabilities_t
	allocsb00c375   interface{}
}

// ZesVfExp2Capabilities as declared in levelzero/zes_api.h:566
type ZesVfExp2Capabilities struct {
	PNext           unsafe.Pointer
	Address         ZesPciAddress
	VfDeviceMemSize uint64
	VfID            uint32
	ref2e849f6b     *C.zes_vf_exp2_capabilities_t
	allocs2e849f6b  interface{}
}

// ZesVfUtilMemExp2 as declared in levelzero/zes_api.h:570
type ZesVfUtilMemExp2 struct {
	PNext          unsafe.Pointer
	VfMemLocation  ZesMemLoc
	VfMemUtilized  uint64
	ref8020cd22    *C.zes_vf_util_mem_exp2_t
	allocs8020cd22 interface{}
}

// ZesVfUtilEngineExp2 as declared in levelzero/zes_api.h:574
type ZesVfUtilEngineExp2 struct {
	PNext                unsafe.Pointer
	VfEngineType         ZesEngineGroup
	ActiveCounterValue   uint64
	SamplingCounterValue uint64
	refd1d37551          *C.zes_vf_util_engine_exp2_t
	allocsd1d37551       interface{}
}

// ZesInitFlags type as declared in levelzero/zes_api.h:586
type ZesInitFlags uint32

// ZesEngineTypeFlags type as declared in levelzero/zes_api.h:792
type ZesEngineTypeFlags uint32

// ZesResetReasonFlags type as declared in levelzero/zes_api.h:818
type ZesResetReasonFlags uint32

// ZesDevicePropertyFlags type as declared in levelzero/zes_api.h:888
type ZesDevicePropertyFlags uint32

// ZesPciLinkQualIssueFlags type as declared in levelzero/zes_api.h:1185
type ZesPciLinkQualIssueFlags uint32

// ZesPciLinkStabIssueFlags type as declared in levelzero/zes_api.h:1196
type ZesPciLinkStabIssueFlags uint32

// ZesEventTypeFlags type as declared in levelzero/zes_api.h:2551
type ZesEventTypeFlags uint32

// ZesFabricPortQualIssueFlags type as declared in levelzero/zes_api.h:2735
type ZesFabricPortQualIssueFlags uint32

// ZesFabricPortFailureFlags type as declared in levelzero/zes_api.h:2746
type ZesFabricPortFailureFlags uint32

// ZesFreqThrottleReasonFlags type as declared in levelzero/zes_api.h:3665
type ZesFreqThrottleReasonFlags uint32

// ZesVfInfoMemTypeExpFlags type as declared in levelzero/zes_api.h:7126
type ZesVfInfoMemTypeExpFlags uint32

// ZesVfInfoUtilExpFlags type as declared in levelzero/zes_api.h:7137
type ZesVfInfoUtilExpFlags uint32
