// Code generated by "stringer -type=ZesDeviceEccState -trimprefix=ZES_DEVICE_ECC_STATE_ -output=zz_ZesDeviceEccState_string.go const.go"; DO NOT EDIT.

package levelzero

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZES_DEVICE_ECC_STATE_UNAVAILABLE-0]
	_ = x[ZES_DEVICE_ECC_STATE_ENABLED-1]
	_ = x[ZES_DEVICE_ECC_STATE_DISABLED-2]
	_ = x[ZES_DEVICE_ECC_STATE_FORCE_UINT32-2147483647]
}

const (
	_ZesDeviceEccState_name_0 = "UNAVAILABLEENABLEDDISABLED"
	_ZesDeviceEccState_name_1 = "FORCE_UINT32"
)

var (
	_ZesDeviceEccState_index_0 = [...]uint8{0, 11, 18, 26}
)

func (i ZesDeviceEccState) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _ZesDeviceEccState_name_0[_ZesDeviceEccState_index_0[i]:_ZesDeviceEccState_index_0[i+1]]
	case i == 2147483647:
		return _ZesDeviceEccState_name_1
	default:
		return "ZesDeviceEccState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
