// Code generated by "stringer -type=ZesOverclockControl -trimprefix=ZES_OVERCLOCK_CONTROL_ -output=zz_ZesOverclockControl_string.go const.go"; DO NOT EDIT.

package levelzero

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZES_OVERCLOCK_CONTROL_VF-1]
	_ = x[ZES_OVERCLOCK_CONTROL_FREQ_OFFSET-2]
	_ = x[ZES_OVERCLOCK_CONTROL_VMAX_OFFSET-4]
	_ = x[ZES_OVERCLOCK_CONTROL_FREQ-8]
	_ = x[ZES_OVERCLOCK_CONTROL_VOLT_LIMIT-16]
	_ = x[ZES_OVERCLOCK_CONTROL_POWER_SUSTAINED_LIMIT-32]
	_ = x[ZES_OVERCLOCK_CONTROL_POWER_BURST_LIMIT-64]
	_ = x[ZES_OVERCLOCK_CONTROL_POWER_PEAK_LIMIT-128]
	_ = x[ZES_OVERCLOCK_CONTROL_ICCMAX_LIMIT-256]
	_ = x[ZES_OVERCLOCK_CONTROL_TEMP_LIMIT-512]
	_ = x[ZES_OVERCLOCK_CONTROL_ITD_DISABLE-1024]
	_ = x[ZES_OVERCLOCK_CONTROL_ACM_DISABLE-2048]
	_ = x[ZES_OVERCLOCK_CONTROL_END_MARKER-2147483647]
}

const _ZesOverclockControl_name = "VFFREQ_OFFSETVMAX_OFFSETFREQVOLT_LIMITPOWER_SUSTAINED_LIMITPOWER_BURST_LIMITPOWER_PEAK_LIMITICCMAX_LIMITTEMP_LIMITITD_DISABLEACM_DISABLEEND_MARKER"

var _ZesOverclockControl_map = map[ZesOverclockControl]string{
	1:          _ZesOverclockControl_name[0:2],
	2:          _ZesOverclockControl_name[2:13],
	4:          _ZesOverclockControl_name[13:24],
	8:          _ZesOverclockControl_name[24:28],
	16:         _ZesOverclockControl_name[28:38],
	32:         _ZesOverclockControl_name[38:59],
	64:         _ZesOverclockControl_name[59:76],
	128:        _ZesOverclockControl_name[76:92],
	256:        _ZesOverclockControl_name[92:104],
	512:        _ZesOverclockControl_name[104:114],
	1024:       _ZesOverclockControl_name[114:125],
	2048:       _ZesOverclockControl_name[125:136],
	2147483647: _ZesOverclockControl_name[136:146],
}

func (i ZesOverclockControl) String() string {
	if str, ok := _ZesOverclockControl_map[i]; ok {
		return str
	}
	return "ZesOverclockControl(" + strconv.FormatInt(int64(i), 10) + ")"
}
