// Code generated by "stringer -type=ZesOverclockDomain -trimprefix=ZES_OVERCLOCK_DOMAIN_ -output=zz_ZesOverclockDomain_string.go const.go"; DO NOT EDIT.

package levelzero

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZES_OVERCLOCK_DOMAIN_CARD-1]
	_ = x[ZES_OVERCLOCK_DOMAIN_PACKAGE-2]
	_ = x[ZES_OVERCLOCK_DOMAIN_GPU_ALL-4]
	_ = x[ZES_OVERCLOCK_DOMAIN_GPU_RENDER_COMPUTE-8]
	_ = x[ZES_OVERCLOCK_DOMAIN_GPU_RENDER-16]
	_ = x[ZES_OVERCLOCK_DOMAIN_GPU_COMPUTE-32]
	_ = x[ZES_OVERCLOCK_DOMAIN_GPU_MEDIA-64]
	_ = x[ZES_OVERCLOCK_DOMAIN_VRAM-128]
	_ = x[ZES_OVERCLOCK_DOMAIN_ADM-256]
	_ = x[ZES_OVERCLOCK_DOMAIN_END_MARKER-2147483647]
}

const (
	_ZesOverclockDomain_name_0 = "CARDPACKAGE"
	_ZesOverclockDomain_name_1 = "GPU_ALL"
	_ZesOverclockDomain_name_2 = "GPU_RENDER_COMPUTE"
	_ZesOverclockDomain_name_3 = "GPU_RENDER"
	_ZesOverclockDomain_name_4 = "GPU_COMPUTE"
	_ZesOverclockDomain_name_5 = "GPU_MEDIA"
	_ZesOverclockDomain_name_6 = "VRAM"
	_ZesOverclockDomain_name_7 = "ADM"
	_ZesOverclockDomain_name_8 = "END_MARKER"
)

var (
	_ZesOverclockDomain_index_0 = [...]uint8{0, 4, 11}
)

func (i ZesOverclockDomain) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ZesOverclockDomain_name_0[_ZesOverclockDomain_index_0[i]:_ZesOverclockDomain_index_0[i+1]]
	case i == 4:
		return _ZesOverclockDomain_name_1
	case i == 8:
		return _ZesOverclockDomain_name_2
	case i == 16:
		return _ZesOverclockDomain_name_3
	case i == 32:
		return _ZesOverclockDomain_name_4
	case i == 64:
		return _ZesOverclockDomain_name_5
	case i == 128:
		return _ZesOverclockDomain_name_6
	case i == 256:
		return _ZesOverclockDomain_name_7
	case i == 2147483647:
		return _ZesOverclockDomain_name_8
	default:
		return "ZesOverclockDomain(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
