// Code generated by "stringer -type=ZesFirmwareSecurityExpVersion -trimprefix=ZES_FIRMWARE_SECURITY_EXP_VERSION_ -output=zz_ZesFirmwareSecurityExpVersion_string.go const.go"; DO NOT EDIT.

package levelzero

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZES_FIRMWARE_SECURITY_EXP_VERSION_1_0-65536]
	_ = x[ZES_FIRMWARE_SECURITY_EXP_VERSION_CURRENT-65536]
	_ = x[ZES_FIRMWARE_SECURITY_EXP_VERSION_END_MARKER-2147483647]
}

const (
	_ZesFirmwareSecurityExpVersion_name_0 = "1_0"
	_ZesFirmwareSecurityExpVersion_name_1 = "END_MARKER"
)

func (i ZesFirmwareSecurityExpVersion) String() string {
	switch {
	case i == 65536:
		return _ZesFirmwareSecurityExpVersion_name_0
	case i == 2147483647:
		return _ZesFirmwareSecurityExpVersion_name_1
	default:
		return "ZesFirmwareSecurityExpVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
