// Code generated by "stringer -type=ZesVfArrayType -trimprefix=ZES_VF_ARRAY_TYPE_ -output=zz_ZesVfArrayType_string.go const.go"; DO NOT EDIT.

package levelzero

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZES_VF_ARRAY_TYPE_USER_VF_ARRAY-0]
	_ = x[ZES_VF_ARRAY_TYPE_DEFAULT_VF_ARRAY-1]
	_ = x[ZES_VF_ARRAY_TYPE_LIVE_VF_ARRAY-2]
	_ = x[ZES_VF_ARRAY_TYPE_FORCE_UINT32-2147483647]
}

const (
	_ZesVfArrayType_name_0 = "USER_VF_ARRAYDEFAULT_VF_ARRAYLIVE_VF_ARRAY"
	_ZesVfArrayType_name_1 = "FORCE_UINT32"
)

var (
	_ZesVfArrayType_index_0 = [...]uint8{0, 13, 29, 42}
)

func (i ZesVfArrayType) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _ZesVfArrayType_name_0[_ZesVfArrayType_index_0[i]:_ZesVfArrayType_index_0[i+1]]
	case i == 2147483647:
		return _ZesVfArrayType_name_1
	default:
		return "ZesVfArrayType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
