// Code generated by "stringer -type=ZesPowerSource -trimprefix=ZES_POWER_SOURCE_ -output=zz_ZesPowerSource_string.go const.go"; DO NOT EDIT.

package levelzero

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZES_POWER_SOURCE_ANY-0]
	_ = x[ZES_POWER_SOURCE_MAINS-1]
	_ = x[ZES_POWER_SOURCE_BATTERY-2]
	_ = x[ZES_POWER_SOURCE_FORCE_UINT32-2147483647]
}

const (
	_ZesPowerSource_name_0 = "ANYMAINSBATTERY"
	_ZesPowerSource_name_1 = "FORCE_UINT32"
)

var (
	_ZesPowerSource_index_0 = [...]uint8{0, 3, 8, 15}
)

func (i ZesPowerSource) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _ZesPowerSource_name_0[_ZesPowerSource_index_0[i]:_ZesPowerSource_index_0[i+1]]
	case i == 2147483647:
		return _ZesPowerSource_name_1
	default:
		return "ZesPowerSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
