// Code generated by "stringer -type=ZesOverclockMode -trimprefix=ZES_OVERCLOCK_MODE_ -output=zz_ZesOverclockMode_string.go const.go"; DO NOT EDIT.

package levelzero

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZES_OVERCLOCK_MODE_MODE_OFF-0]
	_ = x[ZES_OVERCLOCK_MODE_MODE_STOCK-2]
	_ = x[ZES_OVERCLOCK_MODE_MODE_ON-3]
	_ = x[ZES_OVERCLOCK_MODE_MODE_UNAVAILABLE-4]
	_ = x[ZES_OVERCLOCK_MODE_MODE_DISABLED-5]
	_ = x[ZES_OVERCLOCK_MODE_FORCE_UINT32-2147483647]
}

const (
	_ZesOverclockMode_name_0 = "MODE_OFF"
	_ZesOverclockMode_name_1 = "MODE_STOCKMODE_ONMODE_UNAVAILABLEMODE_DISABLED"
	_ZesOverclockMode_name_2 = "FORCE_UINT32"
)

var (
	_ZesOverclockMode_index_1 = [...]uint8{0, 10, 17, 33, 46}
)

func (i ZesOverclockMode) String() string {
	switch {
	case i == 0:
		return _ZesOverclockMode_name_0
	case 2 <= i && i <= 5:
		i -= 2
		return _ZesOverclockMode_name_1[_ZesOverclockMode_index_1[i]:_ZesOverclockMode_index_1[i+1]]
	case i == 2147483647:
		return _ZesOverclockMode_name_2
	default:
		return "ZesOverclockMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
