// Code generated by "stringer -type=ZesEngineActivityExtVersion -trimprefix=ZES_ENGINE_ACTIVITY_EXT_VERSION_ -output=zz_ZesEngineActivityExtVersion_string.go const.go"; DO NOT EDIT.

package levelzero

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZES_ENGINE_ACTIVITY_EXT_VERSION_1_0-65536]
	_ = x[ZES_ENGINE_ACTIVITY_EXT_VERSION_CURRENT-65536]
	_ = x[ZES_ENGINE_ACTIVITY_EXT_VERSION_FORCE_UINT32-2147483647]
}

const (
	_ZesEngineActivityExtVersion_name_0 = "1_0"
	_ZesEngineActivityExtVersion_name_1 = "FORCE_UINT32"
)

func (i ZesEngineActivityExtVersion) String() string {
	switch {
	case i == 65536:
		return _ZesEngineActivityExtVersion_name_0
	case i == 2147483647:
		return _ZesEngineActivityExtVersion_name_1
	default:
		return "ZesEngineActivityExtVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
