// Code generated by "stringer -type=ZesPciBarType -trimprefix=ZES_PCI_BAR_TYPE_ -output=zz_ZesPciBarType_string.go const.go"; DO NOT EDIT.

package levelzero

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZES_PCI_BAR_TYPE_MMIO-0]
	_ = x[ZES_PCI_BAR_TYPE_ROM-1]
	_ = x[ZES_PCI_BAR_TYPE_MEM-2]
	_ = x[ZES_PCI_BAR_TYPE_END_MARKER-2147483647]
}

const (
	_ZesPciBarType_name_0 = "MMIOROMMEM"
	_ZesPciBarType_name_1 = "END_MARKER"
)

var (
	_ZesPciBarType_index_0 = [...]uint8{0, 4, 7, 10}
)

func (i ZesPciBarType) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _ZesPciBarType_name_0[_ZesPciBarType_index_0[i]:_ZesPciBarType_index_0[i+1]]
	case i == 2147483647:
		return _ZesPciBarType_name_1
	default:
		return "ZesPciBarType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
