// Code generated by "stringer -type=ZesPowerLimitsExtVersion -trimprefix=ZES_POWER_LIMITS_EXT_VERSION_ -output=zz_ZesPowerLimitsExtVersion_string.go const.go"; DO NOT EDIT.

package levelzero

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZES_POWER_LIMITS_EXT_VERSION_1_0-65536]
	_ = x[ZES_POWER_LIMITS_EXT_VERSION_CURRENT-65536]
	_ = x[ZES_POWER_LIMITS_EXT_VERSION_END_MARKER-2147483647]
}

const (
	_ZesPowerLimitsExtVersion_name_0 = "1_0"
	_ZesPowerLimitsExtVersion_name_1 = "END_MARKER"
)

func (i ZesPowerLimitsExtVersion) String() string {
	switch {
	case i == 65536:
		return _ZesPowerLimitsExtVersion_name_0
	case i == 2147483647:
		return _ZesPowerLimitsExtVersion_name_1
	default:
		return "ZesPowerLimitsExtVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
