// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/intel/xpumanager/xpumd/extension/inteldevicewatch")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/intel/xpumanager/xpumd/extension/inteldevicewatch")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                      metric.Meter
	mu                         sync.Mutex
	registrations              []metric.Registration
	DeviceWatchDeviceChanges   metric.Int64Counter
	DeviceWatchDevices         metric.Int64Gauge
	DeviceWatchExitsRequested  metric.Int64Counter
	DeviceWatchExitsSuppressed metric.Int64Counter
	DeviceWatchScanErrors      metric.Int64Counter
	DeviceWatchScans           metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.DeviceWatchDeviceChanges, err = builder.meter.Int64Counter(
		"otelcol_device_watch_device_changes",
		metric.WithDescription("Number of settled changes detected in the device set. [Development]"),
		metric.WithUnit("{change}"),
	)
	errs = errors.Join(errs, err)
	builder.DeviceWatchDevices, err = builder.meter.Int64Gauge(
		"otelcol_device_watch_devices",
		metric.WithDescription("Number of devices per device state, as observed by the latest scan. [Development]"),
		metric.WithUnit("{device}"),
	)
	errs = errors.Join(errs, err)
	builder.DeviceWatchExitsRequested, err = builder.meter.Int64Counter(
		"otelcol_device_watch_exits_requested",
		metric.WithDescription("Number of collector shutdowns requested because the device set changed. [Development]"),
		metric.WithUnit("{exit}"),
	)
	errs = errors.Join(errs, err)
	builder.DeviceWatchExitsSuppressed, err = builder.meter.Int64Counter(
		"otelcol_device_watch_exits_suppressed",
		metric.WithDescription("Number of shutdowns not requested although the device set changed. [Development]"),
		metric.WithUnit("{exit}"),
	)
	errs = errors.Join(errs, err)
	builder.DeviceWatchScanErrors, err = builder.meter.Int64Counter(
		"otelcol_device_watch_scan_errors",
		metric.WithDescription("Number of device inventory scans that failed, wholly or partially. [Development]"),
		metric.WithUnit("{error}"),
	)
	errs = errors.Join(errs, err)
	builder.DeviceWatchScans, err = builder.meter.Int64Counter(
		"otelcol_device_watch_scans",
		metric.WithDescription("Number of device inventory scans performed. [Development]"),
		metric.WithUnit("{scan}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
