#
# Copyright (C) 2021-2023 Intel Corporation
# SPDX-License-Identifier: MIT
# @file jenkins-server.yaml
#

!!!!!!! Must uncomment Secret and use real PASSWORD for "PLACEHOLDER"!!!!!!!
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: xpum-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-admin
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: xpum-cluster
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-path
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-path
  claimRef:
    name: jenkins-pv-claim
    namespace: xpum-cluster
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: xpum-cluster
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 40Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: xpum-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
            fsGroup: 1000
            runAsUser: 1000
      serviceAccountName: jenkins-admin
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk17
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        resources:
          limits:
            cpu: 2
            memory: "8Gi"
        env:
        - name: JAVA_OPTS
          value: "-XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC"
        - name: TZ
          value: PRC
        ports:
        - name: jenkins-web
          containerPort: 8080
        - name: jenkins-jnlp
          containerPort: 50000
        livenessProbe:
          httpGet:
            path: /login
            port: jenkins-web
          failureThreshold: 3
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /login
            port: jenkins-web
          failureThreshold: 12
          periodSeconds: 10
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: xpum-cluster
spec:
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    targetPort: 8080
    port: 8080
    nodePort: 30346
  - name: jnlp
    protocol: TCP
    targetPort: 50000
    port: 50000
    nodePort: 32757
  selector:
    app: jenkins-server
---
apiVersion: v1
# kind: Secret
metadata:
  name: sign-secret
  namespace: xpum-cluster
type: kubernetes.io/basic-auth
stringData:
  username: sys_xpum
  password: PLACEHOLDER
---
apiVersion: v1
# kind: Secret
metadata:
 name: docker-config-secret
 namespace: xpum-cluster
data:
  ## cat ~/.docker/config.json | base64
 .dockerconfigjson: "PLACEHOLDER"
type: kubernetes.io/dockerconfigjson