#
# Copyright (C) 2021-2022 Intel Corporation
# SPDX-License-Identifier: MIT
# @file jenkins-server.yaml
#

!!!!!!! Must uncomment Secret and use real PASSWORD for "PLACEHOLDER"!!!!!!!
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 40Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk17
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        resources:
          limits:
            cpu: 2
            memory: "8Gi"
        env:
        - name: JAVA_OPTS
          value: "-XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC"
        - name: TZ
          value: PRC
        ports:
        - name: jenkins-web
          containerPort: 8080
        - name: jenkins-jnlp
          containerPort: 50000
        livenessProbe:
          httpGet:
            path: /login
            port: jenkins-web
          failureThreshold: 3
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /login
            port: jenkins-web
          failureThreshold: 12
          periodSeconds: 10
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    targetPort: 8080
    port: 8080
    nodePort: 30346
  - name: jnlp
    protocol: TCP
    targetPort: 50000
    port: 50000
    nodePort: 32757
  selector:
    app: jenkins
---
apiVersion: v1
# kind: Secret
metadata:
  name: sign-secret
  namespace: jenkins
type: kubernetes.io/basic-auth
stringData:
  username: sys_dcm
  password: PLACEHOLDER
---
apiVersion: v1
# kind: Secret
metadata:
 name: docker-config-secret
 namespace: jenkins
data:
  ## cat ~/.docker/config.json | base64
 .dockerconfigjson: "PLACEHOLDER"
type: kubernetes.io/dockerconfigjson