#
# Copyright (C) 2021-2023 Intel Corporation
# SPDX-License-Identifier: MIT
# @file xpum-builder-pod.yaml
#

apiVersion: v1
kind: Pod
metadata:
  labels:
    worker: xpum-builder
  namespace: xpum-cluster
spec:
  containers:
    - args:
      - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/xpum/xpum-builder-sles:lz-1.8.5-20240220"
      imagePullPolicy: "Always"
      name: "xpum-builder-sles"
      resources:
        limits: 
          memory: "6Gi"
          cpu: "4"
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        privileged: false
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/xpum/xpum-builder-ubuntu-focal:lz-1.8.5-20240220"
      imagePullPolicy: "Always"
      name: "xpum-builder-ubuntu-focal"
      resources:
        limits: 
          memory: "6Gi"
          cpu: "4"
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        privileged: false
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - args:
      - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/xpum/xpum-builder-ubuntu-jammy:lz-1.8.5-20240220"
      imagePullPolicy: "Always"
      name: "xpum-builder-ubuntu-jammy"
      resources:
        limits: 
          memory: "6Gi"
          cpu: "4"
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        privileged: false
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/xpum/xpum-builder-debian:lz-1.8.5-20240220"
      imagePullPolicy: "Always"
      name: "xpum-builder-debian"
      resources:
        limits: 
          memory: "6Gi"
          cpu: "4"
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        privileged: false
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/xpum/xpum-builder-centos7-6:lz-1.8.5-20240220"
      imagePullPolicy: "Always"
      name: "xpum-builder-centos7-6"
      resources:
        limits: 
          memory: "6Gi"
          cpu: "4"
        requests:
          memory: "2Gi"
          cpu: "1"
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/xpum/xpum-builder-centos8-2:lz-1.8.5-20240220"
      imagePullPolicy: "Always"
      name: "xpum-builder-centos8-2"
      resources:
        limits: 
          memory: "6Gi"
          cpu: "4"
        requests:
          memory: "2Gi"
          cpu: "1"
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/xpum/xpum-builder-centos-stream9:lz-1.8.5-20240220"
      imagePullPolicy: "Always"
      name: "xpum-builder-centos-stream9"
      resources:
        requests:
          memory: "2Gi"
          cpu: "0.5"
        limits: 
          memory: "6Gi"
          cpu: "2"
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - env:
        - name: "JENKINS_AGENT_WORKDIR"
          value: "/home/jenkins/agent"
      image: "jenkins/inbound-agent:latest-jdk17"
      name: "jnlp"
      resources:
        limits: 
          memory: "2Gi"
          cpu: "2"
        requests:
          memory: "1Gi"
          cpu: "1"
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
  hostNetwork: false
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  volumes:
    - name: sign-secret
      secret:
        secretName: sign-secret
        items:
          - key: password
            path: password.sys_xpum
    - emptyDir:
        medium: ""
      name: "workspace-volume"
    - name: docker-config
      projected:
        sources:
        - secret:
            name: docker-config-secret
            items:
              - key: .dockerconfigjson
                path: config.json
    - name: jenkins-shared-pvc
      persistentVolumeClaim:
        claimName: jenkins-pv-claim