#
# Copyright (C) 2021-2022 Intel Corporation
# SPDX-License-Identifier: MIT
# @file xpum-builder-pod.yaml
#

apiVersion: v1
kind: Pod
metadata:
  labels:
    worker: xpum-builder
  namespace: dms-cluster
spec:
  tolerations:
  - key: jenkins-job-only
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  containers:
    - args:
      - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/dms-pub/xpum-builder-sles:lz-1.8.5-20221102"
      imagePullPolicy: "Always"
      name: "xpum-builder-sles"
      resources:
        limits: 
          memory: "6Gi"
          cpu: "2"
      securityContext:
        privileged: false
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/dms-pub/xpum-builder-ubuntu-focal:lz-1.8.5-20221102"
      imagePullPolicy: "Always"
      name: "xpum-builder-ubuntu-focal"
      resources:
        limits: 
          memory: "6Gi"
          cpu: "2"
      securityContext:
        privileged: false
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/dms-pub/xpum-builder-ubuntu-jammy:lz-1.8.5-20221102"
      imagePullPolicy: "Always"
      name: "xpum-builder-ubuntu-jammy"
      resources:
        limits: 
          memory: "6Gi"
          cpu: "2"
      securityContext:
        privileged: false
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/dms-pub/xpum-builder-centos7:lz-1.8.5-20221102"
      imagePullPolicy: "Always"
      name: "xpum-builder-centos7"
      resources:
        limits: 
          memory: "6Gi"
          cpu: "2"
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/dms-pub/xpum-builder-centos8:lz-1.8.5-20221102"
      imagePullPolicy: "Always"
      name: "xpum-builder-centos8"
      resources:
        limits: 
          memory: "6Gi"
          cpu: "2"
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
        - mountPath: "/home/jenkins/jenkins-shared-pvc"
          name: "jenkins-shared-pvc"
          readOnly: false
      workingDir: "/home/jenkins/agent"
    - name: "kaniko-1"
      image: "gcr.io/kaniko-project/executor:debug"
      imagePullPolicy: Always
      command:
      - /busybox/cat
      tty: true
      resources:
        limits: 
          memory: "2Gi"
          cpu: "1"
      securityContext:
        privileged: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: docker-config
          mountPath: /kaniko/.docker
      workingDir: "/home/jenkins/agent"
    - name: "kaniko-2"
      image: "gcr.io/kaniko-project/executor:debug"
      imagePullPolicy: Always
      command:
      - /busybox/cat
      tty: true
      resources:
        limits: 
          memory: "2Gi"
          cpu: "1"
      securityContext:
        privileged: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: docker-config
          mountPath: /kaniko/.docker
      workingDir: "/home/jenkins/agent"
    - env:
        - name: "GIT_LFS_SKIP_SMUDGE"
          value: "1"
        - name: "GIT_TRACE"
          value: "0"
        - name: "GIT_CURL_VERBOSE"
          value: "0"
        - name: "JENKINS_AGENT_WORKDIR"
          value: "/home/jenkins/agent"
        - name: "HTTP_PROXY"
          value: "http://proxy-dmz.intel.com:912"
        - name: "HTTPS_PROXY"
          value: "http://proxy-dmz.intel.com:912"
        - name: "NO_PROXY"
          value: "*.intel.com"
        - name: "http_proxy"
          value: "http://proxy-dmz.intel.com:912"
        - name: "https_proxy"
          value: "http://proxy-dmz.intel.com:912"
        - name: "no_proxy"
          value: "*.intel.com"
      image: "jenkins/inbound-agent:4.11-1"
      name: "jnlp"
      resources:
        limits: 
          memory: "2Gi"
          cpu: "2"
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
  hostNetwork: false
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  volumes:
    - emptyDir:
        medium: ""
      name: workspace-volume
    - name: jenkins-shared-pvc
      persistentVolumeClaim:
        claimName: dms-cluster-jenkins-share
    - name: docker-config
      projected:
        sources:
        - secret:
            name: regcre-amr-registry-caas-intel-com
            items:
              - key: .dockerconfigjson
                path: config.json
    - name: sign-secret
      secret:
        secretName: sign-secret
        items:
          - key: password
            path: password.sys_dcm