#
# Copyright (C) 2021-2022 Intel Corporation
# SPDX-License-Identifier: MIT
# @file xpum-builder-pod.yaml
#

apiVersion: v1
kind: Pod
metadata:
  labels:
    worker: xpum-builder
  namespace: jenkins
spec:
  tolerations:
  - key: jenkins-job-only
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: node-locale
            operator: In
            values:
            - zz1
  containers:
    - args:
      - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/dms-pub/xpum-builder-sles:lz-1.8.1-20220816"
      imagePullPolicy: "Always"
      name: "xpum-builder-sles"
      resources:
        limits: {}
        requests: {}
      securityContext:
        privileged: false
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/dms-pub/xpum-builder-ubuntu:lz-1.8.1-20220818"
      imagePullPolicy: "Always"
      name: "xpum-builder-ubuntu"
      resources:
        limits: {}
        requests: {}
      securityContext:
        privileged: false
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/dms-pub/xpum-builder-centos7:lz-1.8.1-20220816"
      imagePullPolicy: "Always"
      name: "xpum-builder-centos7"
      resources:
        limits: {}
        requests: {}
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
      workingDir: "/home/jenkins/agent"
    - args:
        - "99d"
      command:
        - "sleep"
      image: "ccr-registry.caas.intel.com/dms-pub/xpum-builder-centos8:lz-1.8.1-20220816"
      imagePullPolicy: "Always"
      name: "xpum-builder-centos8"
      resources:
        limits: {}
        requests: {}
      tty: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: sign-secret
          mountPath: "/root"
          readOnly: true
      workingDir: "/home/jenkins/agent"
    - name: "kaniko"
      image: "gcr.io/kaniko-project/executor:debug"
      imagePullPolicy: Always
      command:
      - /busybox/cat
      tty: true
      resources:
        limits: 
          memory: "2Gi"
          cpu: "2"
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        privileged: false
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
        - name: docker-config
          mountPath: /kaniko/.docker
      workingDir: "/home/jenkins/agent"
    - env:
        - name: "JENKINS_TUNNEL"
          value: ":32757"
        - name: "JENKINS_AGENT_WORKDIR"
          value: "/home/jenkins/agent"
        - name: "JENKINS_URL"
          value: "http://10.239.43.86:30346/"
      image: "jenkins/inbound-agent:4.11-1"
      name: "jnlp"
      resources:
        limits: {}
        requests:
          memory: "256Mi"
          cpu: "100m"
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
          readOnly: false
  hostNetwork: false
  nodeSelector:
    kubernetes.io/os: "linux"
    jenkins-workder: "true"
  restartPolicy: "Never"
  volumes:
    - name: sign-secret
      secret:
        secretName: sign-secret
        items:
          - key: password
            path: password.sys_dcm
    - emptyDir:
        medium: ""
      name: "workspace-volume"
    - name: docker-config
      projected:
        sources:
        - secret:
            name: regcre-ccr-registry-caas-intel-com
            items:
              - key: .dockerconfigjson
                path: config.json