# @schema additionalProperties:false
image:
  # -- Image repository
  repository: ghcr.io/marquiz/xpu-exporter/xpu-exporter
  # @schema enum: [Always, IfNotPresent, Never]
  # -- Image pull policy
  pullPolicy: Always
  # -- Image tag, defaults to Chart.AppVersion
  tag: ""

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.PodSpec/properties/imagePullSecrets
# -- [Image pull secrets](https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod)
imagePullSecrets: []

# -- Override the chart name
nameOverride: ""
# -- Override the fully qualified app name
fullnameOverride: ""

# @schema additionalProperties:false
serviceAccount:
  # -- Create service account
  create: true
  # @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta/properties/annotations
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not specified and create is true, a name is generated using the fully qualified app name.
  name: ""

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta/properties/annotations
# -- Annotations to add to the pod
podAnnotations: {}

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.PodSecurityContext
# -- [Pod security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)
podSecurityContext: {}

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.SecurityContext
# -- [Container security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container)
securityContext:
  # @schema hidden
  runAsUser: 0
  # @schema hidden
  privileged: true

# @schema additionalProperties:false
service:
  # -- Create service
  create: true
  # @schema enum: [ClusterIP, NodePort, LoadBalancer, ExternalName]
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: 8080

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements
# -- [Resource requests and limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) of the container
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.PodSpec/properties/nodeSelector
# -- Node selector for pod placement
nodeSelector: {}

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.PodSpec/properties/tolerations
# -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for the pods
tolerations: []

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.Affinity
# -- [Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) for the pods
affinity: {}

# @schema additionalProperties:false
config:
  # -- Metrics data collection interval
  # @section -- XPU Exporter Configuration
  collectInterval: 30s

  # @schema additionalProperties:false
  # -- Configuration for exporters. By default none are enabled, please select a suitable one.
  # @default --  
  # @section -- XPU Exporter Configuration
  exporters:
    # @schema additionalProperties:false
    # @section -- XPU Exporter Configuration
    stdout:
      # -- Enable stdout metrics exporter
      # @section -- XPU Exporter Configuration
      enabled: false
    # @schema additionalProperties:false
    # @section -- XPU Exporter Configuration
    prometheus:
      # -- Enable Prometheus metrics exporter
      # @section -- XPU Exporter Configuration
      enabled: false
    # @schema additionalProperties:false
    # @section -- XPU Exporter Configuration
    grpc:
      # -- Enable OTLP gRPC metrics exporter
      # @section -- XPU Exporter Configuration
      enabled: false
      # -- OTLP/gRPC collector endpoint. If empty, taken from OTEL_EXPORTER_OTLP_ENDPOINT or OTEL_EXPORTER_OTLP_METRICS_ENDPOINT environment variable, or localhost:4317 by default.
      # @section -- XPU Exporter Configuration
      endpoint: ""
      # -- Use insecure connection (no TLS)
      # @section -- XPU Exporter Configuration
      insecure: false
    # @schema additionalProperties:false
    # @section -- XPU Exporter Configuration
    http:
      # -- Enable OTLP HTTP metrics exporter
      # @section -- XPU Exporter Configuration
      enabled: false
      # -- OTLP/HTTP collector endpoint. If empty, taken from OTEL_EXPORTER_OTLP_ENDPOINT or OTEL_EXPORTER_OTLP_METRICS_ENDPOINT environment variable, or localhost:4318 by default.
      # @section -- XPU Exporter Configuration
      endpoint: ""
      # -- Use insecure connection (no TLS)
      # @section -- XPU Exporter Configuration
      insecure: false
