// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					HwEnergy: HwEnergyMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwEnergyMetricAttributeKey{HwEnergyMetricAttributeKeyHwID, HwEnergyMetricAttributeKeyHwName, HwEnergyMetricAttributeKeyPciBdf, HwEnergyMetricAttributeKeyComIntelSubdeviceID, HwEnergyMetricAttributeKeyHwSensorLocation},
					},
					HwErrors: HwErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwErrorsMetricAttributeKey{HwErrorsMetricAttributeKeyHwID, HwErrorsMetricAttributeKeyHwName, HwErrorsMetricAttributeKeyPciBdf, HwErrorsMetricAttributeKeyComIntelSubdeviceID, HwErrorsMetricAttributeKeyHwType, HwErrorsMetricAttributeKeyErrorType, HwErrorsMetricAttributeKeyErrorCategory},
					},
					HwFrequency: HwFrequencyMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwFrequencyMetricAttributeKey{HwFrequencyMetricAttributeKeyHwID, HwFrequencyMetricAttributeKeyHwName, HwFrequencyMetricAttributeKeyPciBdf, HwFrequencyMetricAttributeKeyComIntelSubdeviceID, HwFrequencyMetricAttributeKeyHwFrequencyDomain, HwFrequencyMetricAttributeKeyAggregation},
					},
					HwFrequencyLimit: HwFrequencyLimitMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwFrequencyLimitMetricAttributeKey{HwFrequencyLimitMetricAttributeKeyHwID, HwFrequencyLimitMetricAttributeKeyHwName, HwFrequencyLimitMetricAttributeKeyPciBdf, HwFrequencyLimitMetricAttributeKeyComIntelSubdeviceID, HwFrequencyLimitMetricAttributeKeyHwFrequencyDomain, HwFrequencyLimitMetricAttributeKeyHwLimitType},
					},
					HwFrequencyRequest: HwFrequencyRequestMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwFrequencyRequestMetricAttributeKey{HwFrequencyRequestMetricAttributeKeyHwID, HwFrequencyRequestMetricAttributeKeyHwName, HwFrequencyRequestMetricAttributeKeyPciBdf, HwFrequencyRequestMetricAttributeKeyComIntelSubdeviceID, HwFrequencyRequestMetricAttributeKeyHwFrequencyDomain},
					},
					HwFrequencySamples: HwFrequencySamplesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwFrequencySamplesMetricAttributeKey{HwFrequencySamplesMetricAttributeKeyHwID, HwFrequencySamplesMetricAttributeKeyHwName, HwFrequencySamplesMetricAttributeKeyPciBdf, HwFrequencySamplesMetricAttributeKeyComIntelSubdeviceID, HwFrequencySamplesMetricAttributeKeyHwFrequencyDomain, HwFrequencySamplesMetricAttributeKeySampleStatus},
					},
					HwFrequencyThrottleStatus: HwFrequencyThrottleStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwFrequencyThrottleStatusMetricAttributeKey{HwFrequencyThrottleStatusMetricAttributeKeyHwID, HwFrequencyThrottleStatusMetricAttributeKeyHwName, HwFrequencyThrottleStatusMetricAttributeKeyPciBdf, HwFrequencyThrottleStatusMetricAttributeKeyComIntelSubdeviceID, HwFrequencyThrottleStatusMetricAttributeKeyHwFrequencyDomain, HwFrequencyThrottleStatusMetricAttributeKeyComIntelSpeedThrottleReason},
					},
					HwGpuBandwidthLimit: HwGpuBandwidthLimitMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwGpuBandwidthLimitMetricAttributeKey{HwGpuBandwidthLimitMetricAttributeKeyHwID, HwGpuBandwidthLimitMetricAttributeKeyHwName, HwGpuBandwidthLimitMetricAttributeKeyPciBdf},
					},
					HwGpuBandwidthUtilization: HwGpuBandwidthUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwGpuBandwidthUtilizationMetricAttributeKey{HwGpuBandwidthUtilizationMetricAttributeKeyHwID, HwGpuBandwidthUtilizationMetricAttributeKeyHwName, HwGpuBandwidthUtilizationMetricAttributeKeyPciBdf},
					},
					HwGpuInfo: HwGpuInfoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwGpuInfoMetricAttributeKey{HwGpuInfoMetricAttributeKeyHwID, HwGpuInfoMetricAttributeKeyHwName, HwGpuInfoMetricAttributeKeyPciBdf, HwGpuInfoMetricAttributeKeyPciVendorID, HwGpuInfoMetricAttributeKeyPciDeviceID, HwGpuInfoMetricAttributeKeyHwModel, HwGpuInfoMetricAttributeKeyHwSerialNumber, HwGpuInfoMetricAttributeKeyHwVendor, HwGpuInfoMetricAttributeKeyHwFirmwareVersion, HwGpuInfoMetricAttributeKeyHwGpuType, HwGpuInfoMetricAttributeKeyComIntelSubdeviceCount, HwGpuInfoMetricAttributeKeyPciLanes, HwGpuInfoMetricAttributeKeyPciLinkGen, HwGpuInfoMetricAttributeKeyHwMemoryDemandPaging, HwGpuInfoMetricAttributeKeyHwMemoryEcc},
					},
					HwGpuIo: HwGpuIoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwGpuIoMetricAttributeKey{HwGpuIoMetricAttributeKeyHwID, HwGpuIoMetricAttributeKeyHwName, HwGpuIoMetricAttributeKeyPciBdf, HwGpuIoMetricAttributeKeyNetworkIoDirection},
					},
					HwGpuIoRate: HwGpuIoRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwGpuIoRateMetricAttributeKey{HwGpuIoRateMetricAttributeKeyHwID, HwGpuIoRateMetricAttributeKeyHwName, HwGpuIoRateMetricAttributeKeyPciBdf},
					},
					HwGpuUtilization: HwGpuUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwGpuUtilizationMetricAttributeKey{HwGpuUtilizationMetricAttributeKeyHwID, HwGpuUtilizationMetricAttributeKeyHwName, HwGpuUtilizationMetricAttributeKeyPciBdf, HwGpuUtilizationMetricAttributeKeyComIntelSubdeviceID, HwGpuUtilizationMetricAttributeKeyHwGpuTask},
					},
					HwMemoryBandwidthLimit: HwMemoryBandwidthLimitMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwMemoryBandwidthLimitMetricAttributeKey{HwMemoryBandwidthLimitMetricAttributeKeyHwID, HwMemoryBandwidthLimitMetricAttributeKeyHwName, HwMemoryBandwidthLimitMetricAttributeKeyPciBdf, HwMemoryBandwidthLimitMetricAttributeKeyComIntelSubdeviceID, HwMemoryBandwidthLimitMetricAttributeKeyHwMemoryLocation, HwMemoryBandwidthLimitMetricAttributeKeyHwMemoryType},
					},
					HwMemoryBandwidthUtilization: HwMemoryBandwidthUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwMemoryBandwidthUtilizationMetricAttributeKey{HwMemoryBandwidthUtilizationMetricAttributeKeyHwID, HwMemoryBandwidthUtilizationMetricAttributeKeyHwName, HwMemoryBandwidthUtilizationMetricAttributeKeyPciBdf, HwMemoryBandwidthUtilizationMetricAttributeKeyComIntelSubdeviceID, HwMemoryBandwidthUtilizationMetricAttributeKeyHwMemoryLocation, HwMemoryBandwidthUtilizationMetricAttributeKeyHwMemoryType},
					},
					HwMemoryFree: HwMemoryFreeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwMemoryFreeMetricAttributeKey{HwMemoryFreeMetricAttributeKeyHwID, HwMemoryFreeMetricAttributeKeyHwName, HwMemoryFreeMetricAttributeKeyPciBdf, HwMemoryFreeMetricAttributeKeyComIntelSubdeviceID, HwMemoryFreeMetricAttributeKeyHwMemoryLocation, HwMemoryFreeMetricAttributeKeyHwMemoryType},
					},
					HwMemoryIo: HwMemoryIoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwMemoryIoMetricAttributeKey{HwMemoryIoMetricAttributeKeyHwID, HwMemoryIoMetricAttributeKeyHwName, HwMemoryIoMetricAttributeKeyPciBdf, HwMemoryIoMetricAttributeKeyComIntelSubdeviceID, HwMemoryIoMetricAttributeKeyHwMemoryLocation, HwMemoryIoMetricAttributeKeyHwMemoryType, HwMemoryIoMetricAttributeKeyNetworkIoDirection},
					},
					HwMemoryIoRate: HwMemoryIoRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwMemoryIoRateMetricAttributeKey{HwMemoryIoRateMetricAttributeKeyHwID, HwMemoryIoRateMetricAttributeKeyHwName, HwMemoryIoRateMetricAttributeKeyPciBdf, HwMemoryIoRateMetricAttributeKeyComIntelSubdeviceID, HwMemoryIoRateMetricAttributeKeyHwMemoryLocation, HwMemoryIoRateMetricAttributeKeyHwMemoryType},
					},
					HwMemorySize: HwMemorySizeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwMemorySizeMetricAttributeKey{HwMemorySizeMetricAttributeKeyHwID, HwMemorySizeMetricAttributeKeyHwName, HwMemorySizeMetricAttributeKeyPciBdf, HwMemorySizeMetricAttributeKeyComIntelSubdeviceID, HwMemorySizeMetricAttributeKeyHwMemoryLocation, HwMemorySizeMetricAttributeKeyHwMemoryType},
					},
					HwMemoryUsage: HwMemoryUsageMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwMemoryUsageMetricAttributeKey{HwMemoryUsageMetricAttributeKeyHwID, HwMemoryUsageMetricAttributeKeyHwName, HwMemoryUsageMetricAttributeKeyPciBdf, HwMemoryUsageMetricAttributeKeyComIntelSubdeviceID, HwMemoryUsageMetricAttributeKeyHwMemoryLocation, HwMemoryUsageMetricAttributeKeyHwMemoryType},
					},
					HwMemoryUtilization: HwMemoryUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwMemoryUtilizationMetricAttributeKey{HwMemoryUtilizationMetricAttributeKeyHwID, HwMemoryUtilizationMetricAttributeKeyHwName, HwMemoryUtilizationMetricAttributeKeyPciBdf, HwMemoryUtilizationMetricAttributeKeyComIntelSubdeviceID, HwMemoryUtilizationMetricAttributeKeyHwMemoryLocation, HwMemoryUtilizationMetricAttributeKeyHwMemoryType},
					},
					HwPower: HwPowerMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwPowerMetricAttributeKey{HwPowerMetricAttributeKeyHwID, HwPowerMetricAttributeKeyHwName, HwPowerMetricAttributeKeyPciBdf, HwPowerMetricAttributeKeyComIntelSubdeviceID, HwPowerMetricAttributeKeyHwSensorLocation},
					},
					HwPowerLimit: HwPowerLimitMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwPowerLimitMetricAttributeKey{HwPowerLimitMetricAttributeKeyHwID, HwPowerLimitMetricAttributeKeyHwName, HwPowerLimitMetricAttributeKeyPciBdf, HwPowerLimitMetricAttributeKeyComIntelSubdeviceID, HwPowerLimitMetricAttributeKeyHwSensorLocation, HwPowerLimitMetricAttributeKeyComIntelPowerLimitLevel, HwPowerLimitMetricAttributeKeyComIntelPowerLimitSource},
					},
					HwStatus: HwStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwStatusMetricAttributeKey{HwStatusMetricAttributeKeyHwID, HwStatusMetricAttributeKeyHwName, HwStatusMetricAttributeKeyPciBdf, HwStatusMetricAttributeKeyComIntelSubdeviceID, HwStatusMetricAttributeKeyHwState, HwStatusMetricAttributeKeyHwType},
					},
					HwTemperature: HwTemperatureMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwTemperatureMetricAttributeKey{HwTemperatureMetricAttributeKeyHwID, HwTemperatureMetricAttributeKeyHwName, HwTemperatureMetricAttributeKeyPciBdf, HwTemperatureMetricAttributeKeyComIntelSubdeviceID, HwTemperatureMetricAttributeKeyHwSensorLocation, HwTemperatureMetricAttributeKeyStatistic},
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					HwEnergy: HwEnergyMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwEnergyMetricAttributeKey{HwEnergyMetricAttributeKeyHwID, HwEnergyMetricAttributeKeyHwName, HwEnergyMetricAttributeKeyPciBdf, HwEnergyMetricAttributeKeyComIntelSubdeviceID, HwEnergyMetricAttributeKeyHwSensorLocation},
					},
					HwErrors: HwErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwErrorsMetricAttributeKey{HwErrorsMetricAttributeKeyHwID, HwErrorsMetricAttributeKeyHwName, HwErrorsMetricAttributeKeyPciBdf, HwErrorsMetricAttributeKeyComIntelSubdeviceID, HwErrorsMetricAttributeKeyHwType, HwErrorsMetricAttributeKeyErrorType, HwErrorsMetricAttributeKeyErrorCategory},
					},
					HwFrequency: HwFrequencyMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwFrequencyMetricAttributeKey{HwFrequencyMetricAttributeKeyHwID, HwFrequencyMetricAttributeKeyHwName, HwFrequencyMetricAttributeKeyPciBdf, HwFrequencyMetricAttributeKeyComIntelSubdeviceID, HwFrequencyMetricAttributeKeyHwFrequencyDomain, HwFrequencyMetricAttributeKeyAggregation},
					},
					HwFrequencyLimit: HwFrequencyLimitMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwFrequencyLimitMetricAttributeKey{HwFrequencyLimitMetricAttributeKeyHwID, HwFrequencyLimitMetricAttributeKeyHwName, HwFrequencyLimitMetricAttributeKeyPciBdf, HwFrequencyLimitMetricAttributeKeyComIntelSubdeviceID, HwFrequencyLimitMetricAttributeKeyHwFrequencyDomain, HwFrequencyLimitMetricAttributeKeyHwLimitType},
					},
					HwFrequencyRequest: HwFrequencyRequestMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwFrequencyRequestMetricAttributeKey{HwFrequencyRequestMetricAttributeKeyHwID, HwFrequencyRequestMetricAttributeKeyHwName, HwFrequencyRequestMetricAttributeKeyPciBdf, HwFrequencyRequestMetricAttributeKeyComIntelSubdeviceID, HwFrequencyRequestMetricAttributeKeyHwFrequencyDomain},
					},
					HwFrequencySamples: HwFrequencySamplesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwFrequencySamplesMetricAttributeKey{HwFrequencySamplesMetricAttributeKeyHwID, HwFrequencySamplesMetricAttributeKeyHwName, HwFrequencySamplesMetricAttributeKeyPciBdf, HwFrequencySamplesMetricAttributeKeyComIntelSubdeviceID, HwFrequencySamplesMetricAttributeKeyHwFrequencyDomain, HwFrequencySamplesMetricAttributeKeySampleStatus},
					},
					HwFrequencyThrottleStatus: HwFrequencyThrottleStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwFrequencyThrottleStatusMetricAttributeKey{HwFrequencyThrottleStatusMetricAttributeKeyHwID, HwFrequencyThrottleStatusMetricAttributeKeyHwName, HwFrequencyThrottleStatusMetricAttributeKeyPciBdf, HwFrequencyThrottleStatusMetricAttributeKeyComIntelSubdeviceID, HwFrequencyThrottleStatusMetricAttributeKeyHwFrequencyDomain, HwFrequencyThrottleStatusMetricAttributeKeyComIntelSpeedThrottleReason},
					},
					HwGpuBandwidthLimit: HwGpuBandwidthLimitMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwGpuBandwidthLimitMetricAttributeKey{HwGpuBandwidthLimitMetricAttributeKeyHwID, HwGpuBandwidthLimitMetricAttributeKeyHwName, HwGpuBandwidthLimitMetricAttributeKeyPciBdf},
					},
					HwGpuBandwidthUtilization: HwGpuBandwidthUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwGpuBandwidthUtilizationMetricAttributeKey{HwGpuBandwidthUtilizationMetricAttributeKeyHwID, HwGpuBandwidthUtilizationMetricAttributeKeyHwName, HwGpuBandwidthUtilizationMetricAttributeKeyPciBdf},
					},
					HwGpuInfo: HwGpuInfoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwGpuInfoMetricAttributeKey{HwGpuInfoMetricAttributeKeyHwID, HwGpuInfoMetricAttributeKeyHwName, HwGpuInfoMetricAttributeKeyPciBdf, HwGpuInfoMetricAttributeKeyPciVendorID, HwGpuInfoMetricAttributeKeyPciDeviceID, HwGpuInfoMetricAttributeKeyHwModel, HwGpuInfoMetricAttributeKeyHwSerialNumber, HwGpuInfoMetricAttributeKeyHwVendor, HwGpuInfoMetricAttributeKeyHwFirmwareVersion, HwGpuInfoMetricAttributeKeyHwGpuType, HwGpuInfoMetricAttributeKeyComIntelSubdeviceCount, HwGpuInfoMetricAttributeKeyPciLanes, HwGpuInfoMetricAttributeKeyPciLinkGen, HwGpuInfoMetricAttributeKeyHwMemoryDemandPaging, HwGpuInfoMetricAttributeKeyHwMemoryEcc},
					},
					HwGpuIo: HwGpuIoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwGpuIoMetricAttributeKey{HwGpuIoMetricAttributeKeyHwID, HwGpuIoMetricAttributeKeyHwName, HwGpuIoMetricAttributeKeyPciBdf, HwGpuIoMetricAttributeKeyNetworkIoDirection},
					},
					HwGpuIoRate: HwGpuIoRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwGpuIoRateMetricAttributeKey{HwGpuIoRateMetricAttributeKeyHwID, HwGpuIoRateMetricAttributeKeyHwName, HwGpuIoRateMetricAttributeKeyPciBdf},
					},
					HwGpuUtilization: HwGpuUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwGpuUtilizationMetricAttributeKey{HwGpuUtilizationMetricAttributeKeyHwID, HwGpuUtilizationMetricAttributeKeyHwName, HwGpuUtilizationMetricAttributeKeyPciBdf, HwGpuUtilizationMetricAttributeKeyComIntelSubdeviceID, HwGpuUtilizationMetricAttributeKeyHwGpuTask},
					},
					HwMemoryBandwidthLimit: HwMemoryBandwidthLimitMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwMemoryBandwidthLimitMetricAttributeKey{HwMemoryBandwidthLimitMetricAttributeKeyHwID, HwMemoryBandwidthLimitMetricAttributeKeyHwName, HwMemoryBandwidthLimitMetricAttributeKeyPciBdf, HwMemoryBandwidthLimitMetricAttributeKeyComIntelSubdeviceID, HwMemoryBandwidthLimitMetricAttributeKeyHwMemoryLocation, HwMemoryBandwidthLimitMetricAttributeKeyHwMemoryType},
					},
					HwMemoryBandwidthUtilization: HwMemoryBandwidthUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwMemoryBandwidthUtilizationMetricAttributeKey{HwMemoryBandwidthUtilizationMetricAttributeKeyHwID, HwMemoryBandwidthUtilizationMetricAttributeKeyHwName, HwMemoryBandwidthUtilizationMetricAttributeKeyPciBdf, HwMemoryBandwidthUtilizationMetricAttributeKeyComIntelSubdeviceID, HwMemoryBandwidthUtilizationMetricAttributeKeyHwMemoryLocation, HwMemoryBandwidthUtilizationMetricAttributeKeyHwMemoryType},
					},
					HwMemoryFree: HwMemoryFreeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwMemoryFreeMetricAttributeKey{HwMemoryFreeMetricAttributeKeyHwID, HwMemoryFreeMetricAttributeKeyHwName, HwMemoryFreeMetricAttributeKeyPciBdf, HwMemoryFreeMetricAttributeKeyComIntelSubdeviceID, HwMemoryFreeMetricAttributeKeyHwMemoryLocation, HwMemoryFreeMetricAttributeKeyHwMemoryType},
					},
					HwMemoryIo: HwMemoryIoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwMemoryIoMetricAttributeKey{HwMemoryIoMetricAttributeKeyHwID, HwMemoryIoMetricAttributeKeyHwName, HwMemoryIoMetricAttributeKeyPciBdf, HwMemoryIoMetricAttributeKeyComIntelSubdeviceID, HwMemoryIoMetricAttributeKeyHwMemoryLocation, HwMemoryIoMetricAttributeKeyHwMemoryType, HwMemoryIoMetricAttributeKeyNetworkIoDirection},
					},
					HwMemoryIoRate: HwMemoryIoRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwMemoryIoRateMetricAttributeKey{HwMemoryIoRateMetricAttributeKeyHwID, HwMemoryIoRateMetricAttributeKeyHwName, HwMemoryIoRateMetricAttributeKeyPciBdf, HwMemoryIoRateMetricAttributeKeyComIntelSubdeviceID, HwMemoryIoRateMetricAttributeKeyHwMemoryLocation, HwMemoryIoRateMetricAttributeKeyHwMemoryType},
					},
					HwMemorySize: HwMemorySizeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwMemorySizeMetricAttributeKey{HwMemorySizeMetricAttributeKeyHwID, HwMemorySizeMetricAttributeKeyHwName, HwMemorySizeMetricAttributeKeyPciBdf, HwMemorySizeMetricAttributeKeyComIntelSubdeviceID, HwMemorySizeMetricAttributeKeyHwMemoryLocation, HwMemorySizeMetricAttributeKeyHwMemoryType},
					},
					HwMemoryUsage: HwMemoryUsageMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwMemoryUsageMetricAttributeKey{HwMemoryUsageMetricAttributeKeyHwID, HwMemoryUsageMetricAttributeKeyHwName, HwMemoryUsageMetricAttributeKeyPciBdf, HwMemoryUsageMetricAttributeKeyComIntelSubdeviceID, HwMemoryUsageMetricAttributeKeyHwMemoryLocation, HwMemoryUsageMetricAttributeKeyHwMemoryType},
					},
					HwMemoryUtilization: HwMemoryUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwMemoryUtilizationMetricAttributeKey{HwMemoryUtilizationMetricAttributeKeyHwID, HwMemoryUtilizationMetricAttributeKeyHwName, HwMemoryUtilizationMetricAttributeKeyPciBdf, HwMemoryUtilizationMetricAttributeKeyComIntelSubdeviceID, HwMemoryUtilizationMetricAttributeKeyHwMemoryLocation, HwMemoryUtilizationMetricAttributeKeyHwMemoryType},
					},
					HwPower: HwPowerMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwPowerMetricAttributeKey{HwPowerMetricAttributeKeyHwID, HwPowerMetricAttributeKeyHwName, HwPowerMetricAttributeKeyPciBdf, HwPowerMetricAttributeKeyComIntelSubdeviceID, HwPowerMetricAttributeKeyHwSensorLocation},
					},
					HwPowerLimit: HwPowerLimitMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwPowerLimitMetricAttributeKey{HwPowerLimitMetricAttributeKeyHwID, HwPowerLimitMetricAttributeKeyHwName, HwPowerLimitMetricAttributeKeyPciBdf, HwPowerLimitMetricAttributeKeyComIntelSubdeviceID, HwPowerLimitMetricAttributeKeyHwSensorLocation, HwPowerLimitMetricAttributeKeyComIntelPowerLimitLevel, HwPowerLimitMetricAttributeKeyComIntelPowerLimitSource},
					},
					HwStatus: HwStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwStatusMetricAttributeKey{HwStatusMetricAttributeKeyHwID, HwStatusMetricAttributeKeyHwName, HwStatusMetricAttributeKeyPciBdf, HwStatusMetricAttributeKeyComIntelSubdeviceID, HwStatusMetricAttributeKeyHwState, HwStatusMetricAttributeKeyHwType},
					},
					HwTemperature: HwTemperatureMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwTemperatureMetricAttributeKey{HwTemperatureMetricAttributeKeyHwID, HwTemperatureMetricAttributeKeyHwName, HwTemperatureMetricAttributeKeyPciBdf, HwTemperatureMetricAttributeKeyComIntelSubdeviceID, HwTemperatureMetricAttributeKeyHwSensorLocation, HwTemperatureMetricAttributeKeyStatistic},
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(HwEnergyMetricConfig{}, HwErrorsMetricConfig{}, HwFrequencyMetricConfig{}, HwFrequencyLimitMetricConfig{}, HwFrequencyRequestMetricConfig{}, HwFrequencySamplesMetricConfig{}, HwFrequencyThrottleStatusMetricConfig{}, HwGpuBandwidthLimitMetricConfig{}, HwGpuBandwidthUtilizationMetricConfig{}, HwGpuInfoMetricConfig{}, HwGpuIoMetricConfig{}, HwGpuIoRateMetricConfig{}, HwGpuUtilizationMetricConfig{}, HwMemoryBandwidthLimitMetricConfig{}, HwMemoryBandwidthUtilizationMetricConfig{}, HwMemoryFreeMetricConfig{}, HwMemoryIoMetricConfig{}, HwMemoryIoRateMetricConfig{}, HwMemorySizeMetricConfig{}, HwMemoryUsageMetricConfig{}, HwMemoryUtilizationMetricConfig{}, HwPowerMetricConfig{}, HwPowerLimitMetricConfig{}, HwStatusMetricConfig{}, HwTemperatureMetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestHwEnergyMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwEnergy
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwEnergyMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.energy doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.sensor_location]")

	cfg = DefaultMetricsConfig().HwEnergy
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwErrorsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwErrors
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwErrorsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.errors doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.type, error.type, error.category]")

	cfg = DefaultMetricsConfig().HwErrors
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwFrequencyMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwFrequency
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwFrequencyMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.frequency doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.frequency.domain, aggregation]")

	cfg = DefaultMetricsConfig().HwFrequency
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwFrequencyLimitMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwFrequencyLimit
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwFrequencyLimitMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.frequency.limit doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.frequency.domain, hw.limit_type]")

	cfg = DefaultMetricsConfig().HwFrequencyLimit
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwFrequencyRequestMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwFrequencyRequest
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwFrequencyRequestMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.frequency.request doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.frequency.domain]")

	cfg = DefaultMetricsConfig().HwFrequencyRequest
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwFrequencySamplesMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwFrequencySamples
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwFrequencySamplesMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.frequency.samples doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.frequency.domain, sample.status]")

	cfg = DefaultMetricsConfig().HwFrequencySamples
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwFrequencyThrottleStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwFrequencyThrottleStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwFrequencyThrottleStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.frequency.throttle_status doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.frequency.domain, com.intel.speed.throttle_reason]")

	cfg = DefaultMetricsConfig().HwFrequencyThrottleStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwGpuBandwidthLimitMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwGpuBandwidthLimit
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwGpuBandwidthLimitMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.gpu.bandwidth.limit doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf]")

	cfg = DefaultMetricsConfig().HwGpuBandwidthLimit
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwGpuBandwidthUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwGpuBandwidthUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwGpuBandwidthUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.gpu.bandwidth.utilization doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf]")

	cfg = DefaultMetricsConfig().HwGpuBandwidthUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwGpuInfoMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwGpuInfo
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwGpuInfoMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.gpu.info doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, pci.vendor_id, pci.device_id, hw.model, hw.serial_number, hw.vendor, hw.firmware_version, hw.gpu.type, com.intel.subdevice_count, pci.lanes, pci.link_gen, hw.memory.demand_paging, hw.memory.ecc]")

	cfg = DefaultMetricsConfig().HwGpuInfo
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwGpuIoMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwGpuIo
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwGpuIoMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.gpu.io doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, network.io.direction]")

	cfg = DefaultMetricsConfig().HwGpuIo
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwGpuIoRateMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwGpuIoRate
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwGpuIoRateMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.gpu.io.rate doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf]")

	cfg = DefaultMetricsConfig().HwGpuIoRate
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwGpuUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwGpuUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwGpuUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.gpu.utilization doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.gpu.task]")

	cfg = DefaultMetricsConfig().HwGpuUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwMemoryBandwidthLimitMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwMemoryBandwidthLimit
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwMemoryBandwidthLimitMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.memory.bandwidth.limit doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.memory.location, hw.memory.type]")

	cfg = DefaultMetricsConfig().HwMemoryBandwidthLimit
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwMemoryBandwidthUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwMemoryBandwidthUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwMemoryBandwidthUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.memory.bandwidth.utilization doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.memory.location, hw.memory.type]")

	cfg = DefaultMetricsConfig().HwMemoryBandwidthUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwMemoryFreeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwMemoryFree
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwMemoryFreeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.memory.free doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.memory.location, hw.memory.type]")

	cfg = DefaultMetricsConfig().HwMemoryFree
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwMemoryIoMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwMemoryIo
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwMemoryIoMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.memory.io doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.memory.location, hw.memory.type, network.io.direction]")

	cfg = DefaultMetricsConfig().HwMemoryIo
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwMemoryIoRateMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwMemoryIoRate
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwMemoryIoRateMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.memory.io.rate doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.memory.location, hw.memory.type]")

	cfg = DefaultMetricsConfig().HwMemoryIoRate
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwMemorySizeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwMemorySize
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwMemorySizeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.memory.size doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.memory.location, hw.memory.type]")

	cfg = DefaultMetricsConfig().HwMemorySize
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwMemoryUsageMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwMemoryUsage
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwMemoryUsageMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.memory.usage doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.memory.location, hw.memory.type]")

	cfg = DefaultMetricsConfig().HwMemoryUsage
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwMemoryUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwMemoryUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwMemoryUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.memory.utilization doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.memory.location, hw.memory.type]")

	cfg = DefaultMetricsConfig().HwMemoryUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwPowerMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwPower
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwPowerMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.power doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.sensor_location]")

	cfg = DefaultMetricsConfig().HwPower
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwPowerLimitMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwPowerLimit
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwPowerLimitMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.power.limit doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.sensor_location, com.intel.power.limit.level, com.intel.power.limit.source]")

	cfg = DefaultMetricsConfig().HwPowerLimit
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.status doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.state, hw.type]")

	cfg = DefaultMetricsConfig().HwStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwTemperatureMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwTemperature
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwTemperatureMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.temperature doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, pci.bdf, com.intel.subdevice_id, hw.sensor_location, statistic]")

	cfg = DefaultMetricsConfig().HwTemperature
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
