FROM intel/oneapi-runtime:centos8

COPY rpms /rpms
RUN dnf install -y /rpms/*.rpm python3 python3-devel

COPY requirements.txt /
RUN pip3 install -r /requirements.txt 

RUN dnf update -y && \
dnf remove -y kernel-devel kernel-headers

COPY build-rpm /build-rpm
RUN dnf install -y /build-rpm/*.rpm

ENTRYPOINT ["/usr/bin/python3", "/usr/local/xpum/py/DGM.py"]