// Copyright (C) 2019-2025 Intel Corporation
// 
// SPDX-License-Identifier: MIT
// 

// WARNING: This file has automatically been generated 
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "ze_api.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

