// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs ./types.go

package core

import "github.com/google/uuid"

type DeviceUuid struct {
	Id uuid.UUID
}

type DeviceProperties struct {
	stype                    uint32
	pnext                    *byte
	Type                     DeviceType
	VendorId                 uint32
	DeviceId                 uint32
	Flags                    DevicePropertyFlag
	SubdeviceId              uint32
	CoreClockRate            uint32
	MaxMemAllocSize          uint64
	MaxHardwareContexts      uint32
	MaxCommandQueuePriority  uint32
	NumThreadsPerEU          uint32
	PhysicalEUSimdWidth      uint32
	NumEUsPerSubslice        uint32
	NumSubslicesPerSlice     uint32
	NumSlices                uint32
	TimerResolution          uint64
	TimestampValidBits       uint32
	KernelTimestampValidBits uint32
	Uuid                     DeviceUuid
	Name                     StringProperty256
}
