FROM ubuntu:20.04
ADD level-zero-1.4.1.tar.gz /
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get upgrade -y && \
    apt-get install -y gcc g++ build-essential dpkg-dev curl cmake nano python3 python3-pip autoconf libtool
RUN cd /level-zero-1.4.1 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --config Release && \
    cmake --build . --config Release --target install
