FROM centos:8.3.2011
ADD level-zero-1.4.1.tar.gz /
RUN yum update -y && yum clean all && yum install -y rpm-build gcc gcc-c++ cmake make python3 glibc-static
RUN cd /level-zero-1.4.1 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --config Release && \
    cmake --build . --config Release --target install
