#!/bin/bash -ex
#
# Copyright (C) 2026 Intel Corporation
#
# SPDX-License-Identifier: MIT

set -o pipefail

ROOT_DIR=$(pwd)
PACKAGE="$1"

gotool() {
    go tool -modfile "$ROOT_DIR/hack/go.mod" "$@"
}

if [ -z "$PACKAGE" ] || [ ! -d "$PACKAGE" ]; then
    echo "ERROR: package <dir> argument missing or not a dir ('$PACKAGE')!" 1>&2
    exit 1
fi

gotool c-for-go -ccincl -nostamp "$PACKAGE.yml"

cd "$PACKAGE"
if [ -f Doxyfile ]; then
    doxygen
fi

go tool cgo -godefs -- -I../level-zero ./types.go > types.go.tmp

go -C "$ROOT_DIR/hack" run ./types-mangle \
    -in-place \
    -config "$PWD/types-mangle.yaml" \
    "$PWD/types.go.tmp"
go -C "$ROOT_DIR/hack" run ./types-mangle \
    -in-place \
    -config "$PWD/types-mangle-const.yaml" \
    "$PWD/const.go"

gotool goimports types.go.tmp > types.go
rm -f types.go.tmp

# Hack to replace uint with uint64 within auto-generated function prototypes.
# There is a bug in c-for-go (in the version that we're using) that causes it
# to translate uint64_t function arguments to uint.
sed -E '/^func / s/\buint\b/uint64/g' -i "$PACKAGE.go"

# Re-format generated files
gofmt -w types.go const.go

# Remove xml/ generated by doxygen
rm -rf xml/
cd -

go generate "./$PACKAGE/..."

rm -rf "$PACKAGE"/{cgo_helpers.go,_obj/}
