#!/bin/bash -e
#
# Copyright (C) 2026 Intel Corporation
#
# SPDX-License-Identifier: MIT

# Vendors the Intel-specific headers from a compute-runtime source tree.
#
# NOTE: the original upstream headers are not consumable as plain C (and thus not by c-for-go which we
# depend on) because the Sysman header includes the C++ only ze_stypes.h.

set -o pipefail

SCRIPT=$(basename "$0")
ROOT_DIR=$(realpath "$(dirname "$0")/..")
SRC_DIR="$1"

# Paths of the upstream headers, relative to the compute-runtime tree.
HEADER="level_zero/include/level_zero/zes_intel_gpu_sysman.h"
STYPES="level_zero/include/level_zero/ze_stypes.h"

# Own include root, holding nothing but the intel/ subdir, so that the vendored
# headers and the host-installed ones cannot shadow each other.
OUT_DIR="$ROOT_DIR/include/intel"
OUT_HEADER="$OUT_DIR/$(basename "$HEADER")"
OUT_STYPES="$OUT_DIR/$(basename "$STYPES")"

if [ -z "$SRC_DIR" ]; then
    echo "Usage: hack/$SCRIPT <compute-runtime-dir>" 1>&2
    exit 1
fi

# Record exact source revision for traceability.
if ! SHA=$(git -C "$SRC_DIR" rev-parse HEAD 2>/dev/null); then
    echo "ERROR: $SRC_DIR is not a git tree" 1>&2
    exit 1
fi

mkdir -p "$OUT_DIR"

# The Sysman header is vendored as-is, only rewriting its includes to point to our vendored headers.
sed -e 's|^#include "level_zero/ze_stypes.h"$|#include "ze_stypes.h"|' \
    -e 's|^#include <level_zero/zes_api.h>$|#include "zes_api.h"|' \
    "$SRC_DIR/$HEADER" > "$OUT_HEADER"

# Of ze_stypes.h we only need the Sysman structure types, converted to plain C.
{
    # Keep the upstream copyright block (up to the first '*/') as-is.
    sed -n '1,/\*\//p' "$SRC_DIR/$STYPES"

    cat << EOF

// WARNING: Generated by hack/$SCRIPT.
// DO NOT EDIT.
//
// Source:   intel/compute-runtime $STYPES
// Revision: $SHA
//
// Pruned and mangled copy of the Intel compute-runtime header of the same name.
// Only the Sysman structure types of the upstream header are included, converted to plain C.

#ifndef _ZE_STYPES_H
#define _ZE_STYPES_H

#include <stdint.h>
// The Sysman header uses 'bool' which the upstream headers get for free, being C++.
#include <stdbool.h>

typedef uint32_t zes_structure_type_ext_t;

EOF
    sed -nE 's|^#define (ZES_[A-Z0-9_]+) static_cast<(zes_structure_type_ext_t)>\((0x[0-9A-Fa-f]+)\)$|#define \1 ((\2)(\3))|p' \
        "$SRC_DIR/$STYPES"
    echo ""
    echo "#endif // _ZE_STYPES_H"
} > "$OUT_STYPES"

# Sanity check: ensure the vendored headers are valid C (not C++)
CC=${CC:-gcc}
if command -v "$CC" > /dev/null; then
    "$CC" -std=gnu99 -Wall -Wextra -fsyntax-only -x c -I "$ROOT_DIR/level-zero" "$OUT_HEADER" "$OUT_STYPES"
    echo "Syntax check with '$CC -std=gnu99' passed."
else
    echo "WARNING: '$CC' not found, skipping the syntax check!" 1>&2
fi

echo "Vendored headers from compute-runtime $SHA:"
for out in "$OUT_HEADER" "$OUT_STYPES"; do
    echo "  ${out#"$ROOT_DIR"/}"
done
