// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: core.proto
#ifndef GRPC_core_2eproto__INCLUDED
#define GRPC_core_2eproto__INCLUDED

#include "core.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

// services 
class XpumCoreService final {
 public:
  static constexpr char const* service_full_name() {
    return "XpumCoreService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status getVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::XpumVersionInfoArray* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::XpumVersionInfoArray>> AsyncgetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::XpumVersionInfoArray>>(AsyncgetVersionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::XpumVersionInfoArray>> PrepareAsyncgetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::XpumVersionInfoArray>>(PrepareAsyncgetVersionRaw(context, request, cq));
    }
    virtual ::grpc::Status getDeviceList(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::XpumDeviceBasicInfoArray* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::XpumDeviceBasicInfoArray>> AsyncgetDeviceList(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::XpumDeviceBasicInfoArray>>(AsyncgetDeviceListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::XpumDeviceBasicInfoArray>> PrepareAsyncgetDeviceList(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::XpumDeviceBasicInfoArray>>(PrepareAsyncgetDeviceListRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void getVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::XpumVersionInfoArray* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getDeviceList(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::XpumDeviceBasicInfoArray* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::XpumVersionInfoArray>* AsyncgetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::XpumVersionInfoArray>* PrepareAsyncgetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::XpumDeviceBasicInfoArray>* AsyncgetDeviceListRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::XpumDeviceBasicInfoArray>* PrepareAsyncgetDeviceListRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status getVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::XpumVersionInfoArray* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::XpumVersionInfoArray>> AsyncgetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::XpumVersionInfoArray>>(AsyncgetVersionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::XpumVersionInfoArray>> PrepareAsyncgetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::XpumVersionInfoArray>>(PrepareAsyncgetVersionRaw(context, request, cq));
    }
    ::grpc::Status getDeviceList(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::XpumDeviceBasicInfoArray* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::XpumDeviceBasicInfoArray>> AsyncgetDeviceList(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::XpumDeviceBasicInfoArray>>(AsyncgetDeviceListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::XpumDeviceBasicInfoArray>> PrepareAsyncgetDeviceList(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::XpumDeviceBasicInfoArray>>(PrepareAsyncgetDeviceListRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void getVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::XpumVersionInfoArray* response, std::function<void(::grpc::Status)>) override;
      void getDeviceList(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::XpumDeviceBasicInfoArray* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::XpumVersionInfoArray>* AsyncgetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::XpumVersionInfoArray>* PrepareAsyncgetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::XpumDeviceBasicInfoArray>* AsyncgetDeviceListRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::XpumDeviceBasicInfoArray>* PrepareAsyncgetDeviceListRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getVersion_;
    const ::grpc::internal::RpcMethod rpcmethod_getDeviceList_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status getVersion(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::XpumVersionInfoArray* response);
    virtual ::grpc::Status getDeviceList(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::XpumDeviceBasicInfoArray* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_getVersion() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getVersion(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::XpumVersionInfoArray* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetVersion(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::XpumVersionInfoArray>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_getDeviceList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_getDeviceList() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_getDeviceList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getDeviceList(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::XpumDeviceBasicInfoArray* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetDeviceList(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::XpumDeviceBasicInfoArray>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getVersion<WithAsyncMethod_getDeviceList<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_getVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_getVersion() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getVersion(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::XpumVersionInfoArray* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_getDeviceList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_getDeviceList() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_getDeviceList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getDeviceList(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::XpumDeviceBasicInfoArray* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_getVersion() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getVersion(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::XpumVersionInfoArray* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetVersion(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_getDeviceList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_getDeviceList() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_getDeviceList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getDeviceList(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::XpumDeviceBasicInfoArray* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetDeviceList(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_getVersion() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::google::protobuf::Empty, ::XpumVersionInfoArray>(std::bind(&WithStreamedUnaryMethod_getVersion<BaseClass>::StreamedgetVersion, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_getVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getVersion(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::XpumVersionInfoArray* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetVersion(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::XpumVersionInfoArray>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getDeviceList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_getDeviceList() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::google::protobuf::Empty, ::XpumDeviceBasicInfoArray>(std::bind(&WithStreamedUnaryMethod_getDeviceList<BaseClass>::StreamedgetDeviceList, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_getDeviceList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getDeviceList(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::XpumDeviceBasicInfoArray* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetDeviceList(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::XpumDeviceBasicInfoArray>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getVersion<WithStreamedUnaryMethod_getDeviceList<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getVersion<WithStreamedUnaryMethod_getDeviceList<Service > > StreamedService;
};


#endif  // GRPC_core_2eproto__INCLUDED
