// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

#ifndef PROTOBUF_INCLUDED_core_2eproto
#define PROTOBUF_INCLUDED_core_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_core_2eproto 

namespace protobuf_core_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_core_2eproto
class DeviceId;
class DeviceIdDefaultTypeInternal;
extern DeviceIdDefaultTypeInternal _DeviceId_default_instance_;
class GeneralEnum;
class GeneralEnumDefaultTypeInternal;
extern GeneralEnumDefaultTypeInternal _GeneralEnum_default_instance_;
class XpumDeviceBasicInfoArray;
class XpumDeviceBasicInfoArrayDefaultTypeInternal;
extern XpumDeviceBasicInfoArrayDefaultTypeInternal _XpumDeviceBasicInfoArray_default_instance_;
class XpumDeviceBasicInfoArray_XpumDeviceBasicInfo;
class XpumDeviceBasicInfoArray_XpumDeviceBasicInfoDefaultTypeInternal;
extern XpumDeviceBasicInfoArray_XpumDeviceBasicInfoDefaultTypeInternal _XpumDeviceBasicInfoArray_XpumDeviceBasicInfo_default_instance_;
class XpumVersionInfoArray;
class XpumVersionInfoArrayDefaultTypeInternal;
extern XpumVersionInfoArrayDefaultTypeInternal _XpumVersionInfoArray_default_instance_;
class XpumVersionInfoArray_XpumVersionInfo;
class XpumVersionInfoArray_XpumVersionInfoDefaultTypeInternal;
extern XpumVersionInfoArray_XpumVersionInfoDefaultTypeInternal _XpumVersionInfoArray_XpumVersionInfo_default_instance_;
namespace google {
namespace protobuf {
template<> ::DeviceId* Arena::CreateMaybeMessage<::DeviceId>(Arena*);
template<> ::GeneralEnum* Arena::CreateMaybeMessage<::GeneralEnum>(Arena*);
template<> ::XpumDeviceBasicInfoArray* Arena::CreateMaybeMessage<::XpumDeviceBasicInfoArray>(Arena*);
template<> ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo* Arena::CreateMaybeMessage<::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo>(Arena*);
template<> ::XpumVersionInfoArray* Arena::CreateMaybeMessage<::XpumVersionInfoArray>(Arena*);
template<> ::XpumVersionInfoArray_XpumVersionInfo* Arena::CreateMaybeMessage<::XpumVersionInfoArray_XpumVersionInfo>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class GeneralEnum : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GeneralEnum) */ {
 public:
  GeneralEnum();
  virtual ~GeneralEnum();

  GeneralEnum(const GeneralEnum& from);

  inline GeneralEnum& operator=(const GeneralEnum& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GeneralEnum(GeneralEnum&& from) noexcept
    : GeneralEnum() {
    *this = ::std::move(from);
  }

  inline GeneralEnum& operator=(GeneralEnum&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GeneralEnum& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GeneralEnum* internal_default_instance() {
    return reinterpret_cast<const GeneralEnum*>(
               &_GeneralEnum_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GeneralEnum* other);
  friend void swap(GeneralEnum& a, GeneralEnum& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GeneralEnum* New() const final {
    return CreateMaybeMessage<GeneralEnum>(NULL);
  }

  GeneralEnum* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GeneralEnum>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GeneralEnum& from);
  void MergeFrom(const GeneralEnum& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GeneralEnum* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::google::protobuf::uint32 value() const;
  void set_value(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:GeneralEnum)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceId : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DeviceId) */ {
 public:
  DeviceId();
  virtual ~DeviceId();

  DeviceId(const DeviceId& from);

  inline DeviceId& operator=(const DeviceId& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceId(DeviceId&& from) noexcept
    : DeviceId() {
    *this = ::std::move(from);
  }

  inline DeviceId& operator=(DeviceId&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceId& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceId* internal_default_instance() {
    return reinterpret_cast<const DeviceId*>(
               &_DeviceId_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(DeviceId* other);
  friend void swap(DeviceId& a, DeviceId& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceId* New() const final {
    return CreateMaybeMessage<DeviceId>(NULL);
  }

  DeviceId* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceId>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceId& from);
  void MergeFrom(const DeviceId& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceId* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:DeviceId)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class XpumVersionInfoArray_XpumVersionInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XpumVersionInfoArray.XpumVersionInfo) */ {
 public:
  XpumVersionInfoArray_XpumVersionInfo();
  virtual ~XpumVersionInfoArray_XpumVersionInfo();

  XpumVersionInfoArray_XpumVersionInfo(const XpumVersionInfoArray_XpumVersionInfo& from);

  inline XpumVersionInfoArray_XpumVersionInfo& operator=(const XpumVersionInfoArray_XpumVersionInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XpumVersionInfoArray_XpumVersionInfo(XpumVersionInfoArray_XpumVersionInfo&& from) noexcept
    : XpumVersionInfoArray_XpumVersionInfo() {
    *this = ::std::move(from);
  }

  inline XpumVersionInfoArray_XpumVersionInfo& operator=(XpumVersionInfoArray_XpumVersionInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XpumVersionInfoArray_XpumVersionInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XpumVersionInfoArray_XpumVersionInfo* internal_default_instance() {
    return reinterpret_cast<const XpumVersionInfoArray_XpumVersionInfo*>(
               &_XpumVersionInfoArray_XpumVersionInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(XpumVersionInfoArray_XpumVersionInfo* other);
  friend void swap(XpumVersionInfoArray_XpumVersionInfo& a, XpumVersionInfoArray_XpumVersionInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XpumVersionInfoArray_XpumVersionInfo* New() const final {
    return CreateMaybeMessage<XpumVersionInfoArray_XpumVersionInfo>(NULL);
  }

  XpumVersionInfoArray_XpumVersionInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<XpumVersionInfoArray_XpumVersionInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const XpumVersionInfoArray_XpumVersionInfo& from);
  void MergeFrom(const XpumVersionInfoArray_XpumVersionInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XpumVersionInfoArray_XpumVersionInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string versionString = 2;
  void clear_versionstring();
  static const int kVersionStringFieldNumber = 2;
  const ::std::string& versionstring() const;
  void set_versionstring(const ::std::string& value);
  #if LANG_CXX11
  void set_versionstring(::std::string&& value);
  #endif
  void set_versionstring(const char* value);
  void set_versionstring(const char* value, size_t size);
  ::std::string* mutable_versionstring();
  ::std::string* release_versionstring();
  void set_allocated_versionstring(::std::string* versionstring);

  // .GeneralEnum version = 1;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  private:
  const ::GeneralEnum& _internal_version() const;
  public:
  const ::GeneralEnum& version() const;
  ::GeneralEnum* release_version();
  ::GeneralEnum* mutable_version();
  void set_allocated_version(::GeneralEnum* version);

  // @@protoc_insertion_point(class_scope:XpumVersionInfoArray.XpumVersionInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr versionstring_;
  ::GeneralEnum* version_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class XpumVersionInfoArray : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XpumVersionInfoArray) */ {
 public:
  XpumVersionInfoArray();
  virtual ~XpumVersionInfoArray();

  XpumVersionInfoArray(const XpumVersionInfoArray& from);

  inline XpumVersionInfoArray& operator=(const XpumVersionInfoArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XpumVersionInfoArray(XpumVersionInfoArray&& from) noexcept
    : XpumVersionInfoArray() {
    *this = ::std::move(from);
  }

  inline XpumVersionInfoArray& operator=(XpumVersionInfoArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XpumVersionInfoArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XpumVersionInfoArray* internal_default_instance() {
    return reinterpret_cast<const XpumVersionInfoArray*>(
               &_XpumVersionInfoArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(XpumVersionInfoArray* other);
  friend void swap(XpumVersionInfoArray& a, XpumVersionInfoArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XpumVersionInfoArray* New() const final {
    return CreateMaybeMessage<XpumVersionInfoArray>(NULL);
  }

  XpumVersionInfoArray* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<XpumVersionInfoArray>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const XpumVersionInfoArray& from);
  void MergeFrom(const XpumVersionInfoArray& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XpumVersionInfoArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef XpumVersionInfoArray_XpumVersionInfo XpumVersionInfo;

  // accessors -------------------------------------------------------

  // repeated .XpumVersionInfoArray.XpumVersionInfo versions = 1;
  int versions_size() const;
  void clear_versions();
  static const int kVersionsFieldNumber = 1;
  ::XpumVersionInfoArray_XpumVersionInfo* mutable_versions(int index);
  ::google::protobuf::RepeatedPtrField< ::XpumVersionInfoArray_XpumVersionInfo >*
      mutable_versions();
  const ::XpumVersionInfoArray_XpumVersionInfo& versions(int index) const;
  ::XpumVersionInfoArray_XpumVersionInfo* add_versions();
  const ::google::protobuf::RepeatedPtrField< ::XpumVersionInfoArray_XpumVersionInfo >&
      versions() const;

  // string errorMsg = 2;
  void clear_errormsg();
  static const int kErrorMsgFieldNumber = 2;
  const ::std::string& errormsg() const;
  void set_errormsg(const ::std::string& value);
  #if LANG_CXX11
  void set_errormsg(::std::string&& value);
  #endif
  void set_errormsg(const char* value);
  void set_errormsg(const char* value, size_t size);
  ::std::string* mutable_errormsg();
  ::std::string* release_errormsg();
  void set_allocated_errormsg(::std::string* errormsg);

  // @@protoc_insertion_point(class_scope:XpumVersionInfoArray)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::XpumVersionInfoArray_XpumVersionInfo > versions_;
  ::google::protobuf::internal::ArenaStringPtr errormsg_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class XpumDeviceBasicInfoArray_XpumDeviceBasicInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo) */ {
 public:
  XpumDeviceBasicInfoArray_XpumDeviceBasicInfo();
  virtual ~XpumDeviceBasicInfoArray_XpumDeviceBasicInfo();

  XpumDeviceBasicInfoArray_XpumDeviceBasicInfo(const XpumDeviceBasicInfoArray_XpumDeviceBasicInfo& from);

  inline XpumDeviceBasicInfoArray_XpumDeviceBasicInfo& operator=(const XpumDeviceBasicInfoArray_XpumDeviceBasicInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XpumDeviceBasicInfoArray_XpumDeviceBasicInfo(XpumDeviceBasicInfoArray_XpumDeviceBasicInfo&& from) noexcept
    : XpumDeviceBasicInfoArray_XpumDeviceBasicInfo() {
    *this = ::std::move(from);
  }

  inline XpumDeviceBasicInfoArray_XpumDeviceBasicInfo& operator=(XpumDeviceBasicInfoArray_XpumDeviceBasicInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XpumDeviceBasicInfoArray_XpumDeviceBasicInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XpumDeviceBasicInfoArray_XpumDeviceBasicInfo* internal_default_instance() {
    return reinterpret_cast<const XpumDeviceBasicInfoArray_XpumDeviceBasicInfo*>(
               &_XpumDeviceBasicInfoArray_XpumDeviceBasicInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(XpumDeviceBasicInfoArray_XpumDeviceBasicInfo* other);
  friend void swap(XpumDeviceBasicInfoArray_XpumDeviceBasicInfo& a, XpumDeviceBasicInfoArray_XpumDeviceBasicInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XpumDeviceBasicInfoArray_XpumDeviceBasicInfo* New() const final {
    return CreateMaybeMessage<XpumDeviceBasicInfoArray_XpumDeviceBasicInfo>(NULL);
  }

  XpumDeviceBasicInfoArray_XpumDeviceBasicInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<XpumDeviceBasicInfoArray_XpumDeviceBasicInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const XpumDeviceBasicInfoArray_XpumDeviceBasicInfo& from);
  void MergeFrom(const XpumDeviceBasicInfoArray_XpumDeviceBasicInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XpumDeviceBasicInfoArray_XpumDeviceBasicInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string uuid = 3;
  void clear_uuid();
  static const int kUuidFieldNumber = 3;
  const ::std::string& uuid() const;
  void set_uuid(const ::std::string& value);
  #if LANG_CXX11
  void set_uuid(::std::string&& value);
  #endif
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  ::std::string* mutable_uuid();
  ::std::string* release_uuid();
  void set_allocated_uuid(::std::string* uuid);

  // string deviceName = 4;
  void clear_devicename();
  static const int kDeviceNameFieldNumber = 4;
  const ::std::string& devicename() const;
  void set_devicename(const ::std::string& value);
  #if LANG_CXX11
  void set_devicename(::std::string&& value);
  #endif
  void set_devicename(const char* value);
  void set_devicename(const char* value, size_t size);
  ::std::string* mutable_devicename();
  ::std::string* release_devicename();
  void set_allocated_devicename(::std::string* devicename);

  // string pcieDeviceId = 5;
  void clear_pciedeviceid();
  static const int kPcieDeviceIdFieldNumber = 5;
  const ::std::string& pciedeviceid() const;
  void set_pciedeviceid(const ::std::string& value);
  #if LANG_CXX11
  void set_pciedeviceid(::std::string&& value);
  #endif
  void set_pciedeviceid(const char* value);
  void set_pciedeviceid(const char* value, size_t size);
  ::std::string* mutable_pciedeviceid();
  ::std::string* release_pciedeviceid();
  void set_allocated_pciedeviceid(::std::string* pciedeviceid);

  // string subDeviceId = 6;
  void clear_subdeviceid();
  static const int kSubDeviceIdFieldNumber = 6;
  const ::std::string& subdeviceid() const;
  void set_subdeviceid(const ::std::string& value);
  #if LANG_CXX11
  void set_subdeviceid(::std::string&& value);
  #endif
  void set_subdeviceid(const char* value);
  void set_subdeviceid(const char* value, size_t size);
  ::std::string* mutable_subdeviceid();
  ::std::string* release_subdeviceid();
  void set_allocated_subdeviceid(::std::string* subdeviceid);

  // string pciBdfAddress = 7;
  void clear_pcibdfaddress();
  static const int kPciBdfAddressFieldNumber = 7;
  const ::std::string& pcibdfaddress() const;
  void set_pcibdfaddress(const ::std::string& value);
  #if LANG_CXX11
  void set_pcibdfaddress(::std::string&& value);
  #endif
  void set_pcibdfaddress(const char* value);
  void set_pcibdfaddress(const char* value, size_t size);
  ::std::string* mutable_pcibdfaddress();
  ::std::string* release_pcibdfaddress();
  void set_allocated_pcibdfaddress(::std::string* pcibdfaddress);

  // string vendorName = 8;
  void clear_vendorname();
  static const int kVendorNameFieldNumber = 8;
  const ::std::string& vendorname() const;
  void set_vendorname(const ::std::string& value);
  #if LANG_CXX11
  void set_vendorname(::std::string&& value);
  #endif
  void set_vendorname(const char* value);
  void set_vendorname(const char* value, size_t size);
  ::std::string* mutable_vendorname();
  ::std::string* release_vendorname();
  void set_allocated_vendorname(::std::string* vendorname);

  // .DeviceId id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  private:
  const ::DeviceId& _internal_id() const;
  public:
  const ::DeviceId& id() const;
  ::DeviceId* release_id();
  ::DeviceId* mutable_id();
  void set_allocated_id(::DeviceId* id);

  // .GeneralEnum type = 2;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  private:
  const ::GeneralEnum& _internal_type() const;
  public:
  const ::GeneralEnum& type() const;
  ::GeneralEnum* release_type();
  ::GeneralEnum* mutable_type();
  void set_allocated_type(::GeneralEnum* type);

  // @@protoc_insertion_point(class_scope:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr uuid_;
  ::google::protobuf::internal::ArenaStringPtr devicename_;
  ::google::protobuf::internal::ArenaStringPtr pciedeviceid_;
  ::google::protobuf::internal::ArenaStringPtr subdeviceid_;
  ::google::protobuf::internal::ArenaStringPtr pcibdfaddress_;
  ::google::protobuf::internal::ArenaStringPtr vendorname_;
  ::DeviceId* id_;
  ::GeneralEnum* type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class XpumDeviceBasicInfoArray : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:XpumDeviceBasicInfoArray) */ {
 public:
  XpumDeviceBasicInfoArray();
  virtual ~XpumDeviceBasicInfoArray();

  XpumDeviceBasicInfoArray(const XpumDeviceBasicInfoArray& from);

  inline XpumDeviceBasicInfoArray& operator=(const XpumDeviceBasicInfoArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  XpumDeviceBasicInfoArray(XpumDeviceBasicInfoArray&& from) noexcept
    : XpumDeviceBasicInfoArray() {
    *this = ::std::move(from);
  }

  inline XpumDeviceBasicInfoArray& operator=(XpumDeviceBasicInfoArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const XpumDeviceBasicInfoArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const XpumDeviceBasicInfoArray* internal_default_instance() {
    return reinterpret_cast<const XpumDeviceBasicInfoArray*>(
               &_XpumDeviceBasicInfoArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(XpumDeviceBasicInfoArray* other);
  friend void swap(XpumDeviceBasicInfoArray& a, XpumDeviceBasicInfoArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline XpumDeviceBasicInfoArray* New() const final {
    return CreateMaybeMessage<XpumDeviceBasicInfoArray>(NULL);
  }

  XpumDeviceBasicInfoArray* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<XpumDeviceBasicInfoArray>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const XpumDeviceBasicInfoArray& from);
  void MergeFrom(const XpumDeviceBasicInfoArray& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XpumDeviceBasicInfoArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef XpumDeviceBasicInfoArray_XpumDeviceBasicInfo XpumDeviceBasicInfo;

  // accessors -------------------------------------------------------

  // repeated .XpumDeviceBasicInfoArray.XpumDeviceBasicInfo info = 1;
  int info_size() const;
  void clear_info();
  static const int kInfoFieldNumber = 1;
  ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo* mutable_info(int index);
  ::google::protobuf::RepeatedPtrField< ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo >*
      mutable_info();
  const ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo& info(int index) const;
  ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo* add_info();
  const ::google::protobuf::RepeatedPtrField< ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo >&
      info() const;

  // string errorMsg = 2;
  void clear_errormsg();
  static const int kErrorMsgFieldNumber = 2;
  const ::std::string& errormsg() const;
  void set_errormsg(const ::std::string& value);
  #if LANG_CXX11
  void set_errormsg(::std::string&& value);
  #endif
  void set_errormsg(const char* value);
  void set_errormsg(const char* value, size_t size);
  ::std::string* mutable_errormsg();
  ::std::string* release_errormsg();
  void set_allocated_errormsg(::std::string* errormsg);

  // @@protoc_insertion_point(class_scope:XpumDeviceBasicInfoArray)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo > info_;
  ::google::protobuf::internal::ArenaStringPtr errormsg_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GeneralEnum

// uint32 value = 1;
inline void GeneralEnum::clear_value() {
  value_ = 0u;
}
inline ::google::protobuf::uint32 GeneralEnum::value() const {
  // @@protoc_insertion_point(field_get:GeneralEnum.value)
  return value_;
}
inline void GeneralEnum::set_value(::google::protobuf::uint32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:GeneralEnum.value)
}

// -------------------------------------------------------------------

// DeviceId

// uint32 id = 1;
inline void DeviceId::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 DeviceId::id() const {
  // @@protoc_insertion_point(field_get:DeviceId.id)
  return id_;
}
inline void DeviceId::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:DeviceId.id)
}

// -------------------------------------------------------------------

// XpumVersionInfoArray_XpumVersionInfo

// .GeneralEnum version = 1;
inline bool XpumVersionInfoArray_XpumVersionInfo::has_version() const {
  return this != internal_default_instance() && version_ != NULL;
}
inline void XpumVersionInfoArray_XpumVersionInfo::clear_version() {
  if (GetArenaNoVirtual() == NULL && version_ != NULL) {
    delete version_;
  }
  version_ = NULL;
}
inline const ::GeneralEnum& XpumVersionInfoArray_XpumVersionInfo::_internal_version() const {
  return *version_;
}
inline const ::GeneralEnum& XpumVersionInfoArray_XpumVersionInfo::version() const {
  const ::GeneralEnum* p = version_;
  // @@protoc_insertion_point(field_get:XpumVersionInfoArray.XpumVersionInfo.version)
  return p != NULL ? *p : *reinterpret_cast<const ::GeneralEnum*>(
      &::_GeneralEnum_default_instance_);
}
inline ::GeneralEnum* XpumVersionInfoArray_XpumVersionInfo::release_version() {
  // @@protoc_insertion_point(field_release:XpumVersionInfoArray.XpumVersionInfo.version)
  
  ::GeneralEnum* temp = version_;
  version_ = NULL;
  return temp;
}
inline ::GeneralEnum* XpumVersionInfoArray_XpumVersionInfo::mutable_version() {
  
  if (version_ == NULL) {
    auto* p = CreateMaybeMessage<::GeneralEnum>(GetArenaNoVirtual());
    version_ = p;
  }
  // @@protoc_insertion_point(field_mutable:XpumVersionInfoArray.XpumVersionInfo.version)
  return version_;
}
inline void XpumVersionInfoArray_XpumVersionInfo::set_allocated_version(::GeneralEnum* version) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete version_;
  }
  if (version) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      version = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, version, submessage_arena);
    }
    
  } else {
    
  }
  version_ = version;
  // @@protoc_insertion_point(field_set_allocated:XpumVersionInfoArray.XpumVersionInfo.version)
}

// string versionString = 2;
inline void XpumVersionInfoArray_XpumVersionInfo::clear_versionstring() {
  versionstring_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XpumVersionInfoArray_XpumVersionInfo::versionstring() const {
  // @@protoc_insertion_point(field_get:XpumVersionInfoArray.XpumVersionInfo.versionString)
  return versionstring_.GetNoArena();
}
inline void XpumVersionInfoArray_XpumVersionInfo::set_versionstring(const ::std::string& value) {
  
  versionstring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XpumVersionInfoArray.XpumVersionInfo.versionString)
}
#if LANG_CXX11
inline void XpumVersionInfoArray_XpumVersionInfo::set_versionstring(::std::string&& value) {
  
  versionstring_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XpumVersionInfoArray.XpumVersionInfo.versionString)
}
#endif
inline void XpumVersionInfoArray_XpumVersionInfo::set_versionstring(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  versionstring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XpumVersionInfoArray.XpumVersionInfo.versionString)
}
inline void XpumVersionInfoArray_XpumVersionInfo::set_versionstring(const char* value, size_t size) {
  
  versionstring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XpumVersionInfoArray.XpumVersionInfo.versionString)
}
inline ::std::string* XpumVersionInfoArray_XpumVersionInfo::mutable_versionstring() {
  
  // @@protoc_insertion_point(field_mutable:XpumVersionInfoArray.XpumVersionInfo.versionString)
  return versionstring_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XpumVersionInfoArray_XpumVersionInfo::release_versionstring() {
  // @@protoc_insertion_point(field_release:XpumVersionInfoArray.XpumVersionInfo.versionString)
  
  return versionstring_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XpumVersionInfoArray_XpumVersionInfo::set_allocated_versionstring(::std::string* versionstring) {
  if (versionstring != NULL) {
    
  } else {
    
  }
  versionstring_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), versionstring);
  // @@protoc_insertion_point(field_set_allocated:XpumVersionInfoArray.XpumVersionInfo.versionString)
}

// -------------------------------------------------------------------

// XpumVersionInfoArray

// repeated .XpumVersionInfoArray.XpumVersionInfo versions = 1;
inline int XpumVersionInfoArray::versions_size() const {
  return versions_.size();
}
inline void XpumVersionInfoArray::clear_versions() {
  versions_.Clear();
}
inline ::XpumVersionInfoArray_XpumVersionInfo* XpumVersionInfoArray::mutable_versions(int index) {
  // @@protoc_insertion_point(field_mutable:XpumVersionInfoArray.versions)
  return versions_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::XpumVersionInfoArray_XpumVersionInfo >*
XpumVersionInfoArray::mutable_versions() {
  // @@protoc_insertion_point(field_mutable_list:XpumVersionInfoArray.versions)
  return &versions_;
}
inline const ::XpumVersionInfoArray_XpumVersionInfo& XpumVersionInfoArray::versions(int index) const {
  // @@protoc_insertion_point(field_get:XpumVersionInfoArray.versions)
  return versions_.Get(index);
}
inline ::XpumVersionInfoArray_XpumVersionInfo* XpumVersionInfoArray::add_versions() {
  // @@protoc_insertion_point(field_add:XpumVersionInfoArray.versions)
  return versions_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::XpumVersionInfoArray_XpumVersionInfo >&
XpumVersionInfoArray::versions() const {
  // @@protoc_insertion_point(field_list:XpumVersionInfoArray.versions)
  return versions_;
}

// string errorMsg = 2;
inline void XpumVersionInfoArray::clear_errormsg() {
  errormsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XpumVersionInfoArray::errormsg() const {
  // @@protoc_insertion_point(field_get:XpumVersionInfoArray.errorMsg)
  return errormsg_.GetNoArena();
}
inline void XpumVersionInfoArray::set_errormsg(const ::std::string& value) {
  
  errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XpumVersionInfoArray.errorMsg)
}
#if LANG_CXX11
inline void XpumVersionInfoArray::set_errormsg(::std::string&& value) {
  
  errormsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XpumVersionInfoArray.errorMsg)
}
#endif
inline void XpumVersionInfoArray::set_errormsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XpumVersionInfoArray.errorMsg)
}
inline void XpumVersionInfoArray::set_errormsg(const char* value, size_t size) {
  
  errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XpumVersionInfoArray.errorMsg)
}
inline ::std::string* XpumVersionInfoArray::mutable_errormsg() {
  
  // @@protoc_insertion_point(field_mutable:XpumVersionInfoArray.errorMsg)
  return errormsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XpumVersionInfoArray::release_errormsg() {
  // @@protoc_insertion_point(field_release:XpumVersionInfoArray.errorMsg)
  
  return errormsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XpumVersionInfoArray::set_allocated_errormsg(::std::string* errormsg) {
  if (errormsg != NULL) {
    
  } else {
    
  }
  errormsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), errormsg);
  // @@protoc_insertion_point(field_set_allocated:XpumVersionInfoArray.errorMsg)
}

// -------------------------------------------------------------------

// XpumDeviceBasicInfoArray_XpumDeviceBasicInfo

// .DeviceId id = 1;
inline bool XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::has_id() const {
  return this != internal_default_instance() && id_ != NULL;
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::clear_id() {
  if (GetArenaNoVirtual() == NULL && id_ != NULL) {
    delete id_;
  }
  id_ = NULL;
}
inline const ::DeviceId& XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::_internal_id() const {
  return *id_;
}
inline const ::DeviceId& XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::id() const {
  const ::DeviceId* p = id_;
  // @@protoc_insertion_point(field_get:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.id)
  return p != NULL ? *p : *reinterpret_cast<const ::DeviceId*>(
      &::_DeviceId_default_instance_);
}
inline ::DeviceId* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::release_id() {
  // @@protoc_insertion_point(field_release:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.id)
  
  ::DeviceId* temp = id_;
  id_ = NULL;
  return temp;
}
inline ::DeviceId* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::mutable_id() {
  
  if (id_ == NULL) {
    auto* p = CreateMaybeMessage<::DeviceId>(GetArenaNoVirtual());
    id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.id)
  return id_;
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_allocated_id(::DeviceId* id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete id_;
  }
  if (id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, id, submessage_arena);
    }
    
  } else {
    
  }
  id_ = id;
  // @@protoc_insertion_point(field_set_allocated:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.id)
}

// .GeneralEnum type = 2;
inline bool XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::has_type() const {
  return this != internal_default_instance() && type_ != NULL;
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::clear_type() {
  if (GetArenaNoVirtual() == NULL && type_ != NULL) {
    delete type_;
  }
  type_ = NULL;
}
inline const ::GeneralEnum& XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::_internal_type() const {
  return *type_;
}
inline const ::GeneralEnum& XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::type() const {
  const ::GeneralEnum* p = type_;
  // @@protoc_insertion_point(field_get:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.type)
  return p != NULL ? *p : *reinterpret_cast<const ::GeneralEnum*>(
      &::_GeneralEnum_default_instance_);
}
inline ::GeneralEnum* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::release_type() {
  // @@protoc_insertion_point(field_release:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.type)
  
  ::GeneralEnum* temp = type_;
  type_ = NULL;
  return temp;
}
inline ::GeneralEnum* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::mutable_type() {
  
  if (type_ == NULL) {
    auto* p = CreateMaybeMessage<::GeneralEnum>(GetArenaNoVirtual());
    type_ = p;
  }
  // @@protoc_insertion_point(field_mutable:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.type)
  return type_;
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_allocated_type(::GeneralEnum* type) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete type_;
  }
  if (type) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      type = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, type, submessage_arena);
    }
    
  } else {
    
  }
  type_ = type;
  // @@protoc_insertion_point(field_set_allocated:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.type)
}

// string uuid = 3;
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::clear_uuid() {
  uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::uuid() const {
  // @@protoc_insertion_point(field_get:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.uuid)
  return uuid_.GetNoArena();
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_uuid(const ::std::string& value) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.uuid)
}
#if LANG_CXX11
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_uuid(::std::string&& value) {
  
  uuid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.uuid)
}
#endif
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.uuid)
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_uuid(const char* value, size_t size) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.uuid)
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::mutable_uuid() {
  
  // @@protoc_insertion_point(field_mutable:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.uuid)
  return uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::release_uuid() {
  // @@protoc_insertion_point(field_release:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.uuid)
  
  return uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_allocated_uuid(::std::string* uuid) {
  if (uuid != NULL) {
    
  } else {
    
  }
  uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uuid);
  // @@protoc_insertion_point(field_set_allocated:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.uuid)
}

// string deviceName = 4;
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::clear_devicename() {
  devicename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::devicename() const {
  // @@protoc_insertion_point(field_get:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.deviceName)
  return devicename_.GetNoArena();
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_devicename(const ::std::string& value) {
  
  devicename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.deviceName)
}
#if LANG_CXX11
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_devicename(::std::string&& value) {
  
  devicename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.deviceName)
}
#endif
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_devicename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  devicename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.deviceName)
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_devicename(const char* value, size_t size) {
  
  devicename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.deviceName)
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::mutable_devicename() {
  
  // @@protoc_insertion_point(field_mutable:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.deviceName)
  return devicename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::release_devicename() {
  // @@protoc_insertion_point(field_release:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.deviceName)
  
  return devicename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_allocated_devicename(::std::string* devicename) {
  if (devicename != NULL) {
    
  } else {
    
  }
  devicename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), devicename);
  // @@protoc_insertion_point(field_set_allocated:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.deviceName)
}

// string pcieDeviceId = 5;
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::clear_pciedeviceid() {
  pciedeviceid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::pciedeviceid() const {
  // @@protoc_insertion_point(field_get:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pcieDeviceId)
  return pciedeviceid_.GetNoArena();
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_pciedeviceid(const ::std::string& value) {
  
  pciedeviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pcieDeviceId)
}
#if LANG_CXX11
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_pciedeviceid(::std::string&& value) {
  
  pciedeviceid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pcieDeviceId)
}
#endif
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_pciedeviceid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  pciedeviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pcieDeviceId)
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_pciedeviceid(const char* value, size_t size) {
  
  pciedeviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pcieDeviceId)
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::mutable_pciedeviceid() {
  
  // @@protoc_insertion_point(field_mutable:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pcieDeviceId)
  return pciedeviceid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::release_pciedeviceid() {
  // @@protoc_insertion_point(field_release:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pcieDeviceId)
  
  return pciedeviceid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_allocated_pciedeviceid(::std::string* pciedeviceid) {
  if (pciedeviceid != NULL) {
    
  } else {
    
  }
  pciedeviceid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pciedeviceid);
  // @@protoc_insertion_point(field_set_allocated:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pcieDeviceId)
}

// string subDeviceId = 6;
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::clear_subdeviceid() {
  subdeviceid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::subdeviceid() const {
  // @@protoc_insertion_point(field_get:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.subDeviceId)
  return subdeviceid_.GetNoArena();
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_subdeviceid(const ::std::string& value) {
  
  subdeviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.subDeviceId)
}
#if LANG_CXX11
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_subdeviceid(::std::string&& value) {
  
  subdeviceid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.subDeviceId)
}
#endif
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_subdeviceid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  subdeviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.subDeviceId)
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_subdeviceid(const char* value, size_t size) {
  
  subdeviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.subDeviceId)
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::mutable_subdeviceid() {
  
  // @@protoc_insertion_point(field_mutable:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.subDeviceId)
  return subdeviceid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::release_subdeviceid() {
  // @@protoc_insertion_point(field_release:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.subDeviceId)
  
  return subdeviceid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_allocated_subdeviceid(::std::string* subdeviceid) {
  if (subdeviceid != NULL) {
    
  } else {
    
  }
  subdeviceid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), subdeviceid);
  // @@protoc_insertion_point(field_set_allocated:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.subDeviceId)
}

// string pciBdfAddress = 7;
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::clear_pcibdfaddress() {
  pcibdfaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::pcibdfaddress() const {
  // @@protoc_insertion_point(field_get:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pciBdfAddress)
  return pcibdfaddress_.GetNoArena();
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_pcibdfaddress(const ::std::string& value) {
  
  pcibdfaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pciBdfAddress)
}
#if LANG_CXX11
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_pcibdfaddress(::std::string&& value) {
  
  pcibdfaddress_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pciBdfAddress)
}
#endif
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_pcibdfaddress(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  pcibdfaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pciBdfAddress)
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_pcibdfaddress(const char* value, size_t size) {
  
  pcibdfaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pciBdfAddress)
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::mutable_pcibdfaddress() {
  
  // @@protoc_insertion_point(field_mutable:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pciBdfAddress)
  return pcibdfaddress_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::release_pcibdfaddress() {
  // @@protoc_insertion_point(field_release:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pciBdfAddress)
  
  return pcibdfaddress_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_allocated_pcibdfaddress(::std::string* pcibdfaddress) {
  if (pcibdfaddress != NULL) {
    
  } else {
    
  }
  pcibdfaddress_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pcibdfaddress);
  // @@protoc_insertion_point(field_set_allocated:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.pciBdfAddress)
}

// string vendorName = 8;
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::clear_vendorname() {
  vendorname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::vendorname() const {
  // @@protoc_insertion_point(field_get:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.vendorName)
  return vendorname_.GetNoArena();
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_vendorname(const ::std::string& value) {
  
  vendorname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.vendorName)
}
#if LANG_CXX11
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_vendorname(::std::string&& value) {
  
  vendorname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.vendorName)
}
#endif
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_vendorname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  vendorname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.vendorName)
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_vendorname(const char* value, size_t size) {
  
  vendorname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.vendorName)
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::mutable_vendorname() {
  
  // @@protoc_insertion_point(field_mutable:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.vendorName)
  return vendorname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::release_vendorname() {
  // @@protoc_insertion_point(field_release:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.vendorName)
  
  return vendorname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XpumDeviceBasicInfoArray_XpumDeviceBasicInfo::set_allocated_vendorname(::std::string* vendorname) {
  if (vendorname != NULL) {
    
  } else {
    
  }
  vendorname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), vendorname);
  // @@protoc_insertion_point(field_set_allocated:XpumDeviceBasicInfoArray.XpumDeviceBasicInfo.vendorName)
}

// -------------------------------------------------------------------

// XpumDeviceBasicInfoArray

// repeated .XpumDeviceBasicInfoArray.XpumDeviceBasicInfo info = 1;
inline int XpumDeviceBasicInfoArray::info_size() const {
  return info_.size();
}
inline void XpumDeviceBasicInfoArray::clear_info() {
  info_.Clear();
}
inline ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo* XpumDeviceBasicInfoArray::mutable_info(int index) {
  // @@protoc_insertion_point(field_mutable:XpumDeviceBasicInfoArray.info)
  return info_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo >*
XpumDeviceBasicInfoArray::mutable_info() {
  // @@protoc_insertion_point(field_mutable_list:XpumDeviceBasicInfoArray.info)
  return &info_;
}
inline const ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo& XpumDeviceBasicInfoArray::info(int index) const {
  // @@protoc_insertion_point(field_get:XpumDeviceBasicInfoArray.info)
  return info_.Get(index);
}
inline ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo* XpumDeviceBasicInfoArray::add_info() {
  // @@protoc_insertion_point(field_add:XpumDeviceBasicInfoArray.info)
  return info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::XpumDeviceBasicInfoArray_XpumDeviceBasicInfo >&
XpumDeviceBasicInfoArray::info() const {
  // @@protoc_insertion_point(field_list:XpumDeviceBasicInfoArray.info)
  return info_;
}

// string errorMsg = 2;
inline void XpumDeviceBasicInfoArray::clear_errormsg() {
  errormsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XpumDeviceBasicInfoArray::errormsg() const {
  // @@protoc_insertion_point(field_get:XpumDeviceBasicInfoArray.errorMsg)
  return errormsg_.GetNoArena();
}
inline void XpumDeviceBasicInfoArray::set_errormsg(const ::std::string& value) {
  
  errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:XpumDeviceBasicInfoArray.errorMsg)
}
#if LANG_CXX11
inline void XpumDeviceBasicInfoArray::set_errormsg(::std::string&& value) {
  
  errormsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:XpumDeviceBasicInfoArray.errorMsg)
}
#endif
inline void XpumDeviceBasicInfoArray::set_errormsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:XpumDeviceBasicInfoArray.errorMsg)
}
inline void XpumDeviceBasicInfoArray::set_errormsg(const char* value, size_t size) {
  
  errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:XpumDeviceBasicInfoArray.errorMsg)
}
inline ::std::string* XpumDeviceBasicInfoArray::mutable_errormsg() {
  
  // @@protoc_insertion_point(field_mutable:XpumDeviceBasicInfoArray.errorMsg)
  return errormsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XpumDeviceBasicInfoArray::release_errormsg() {
  // @@protoc_insertion_point(field_release:XpumDeviceBasicInfoArray.errorMsg)
  
  return errormsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XpumDeviceBasicInfoArray::set_allocated_errormsg(::std::string* errormsg) {
  if (errormsg != NULL) {
    
  } else {
    
  }
  errormsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), errormsg);
  // @@protoc_insertion_point(field_set_allocated:XpumDeviceBasicInfoArray.errorMsg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_core_2eproto
