// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for sysman metrics.
type MetricsConfig struct {
	HwGpuInfo         MetricConfig `mapstructure:"hw.gpu.info"`
	HwGpuSpeed        MetricConfig `mapstructure:"hw.gpu.speed"`
	HwGpuSpeedLimit   MetricConfig `mapstructure:"hw.gpu.speed.limit"`
	HwGpuSpeedRequest MetricConfig `mapstructure:"hw.gpu.speed.request"`
	HwGpuSpeedSamples MetricConfig `mapstructure:"hw.gpu.speed.samples"`
	HwGpuSpeedStatus  MetricConfig `mapstructure:"hw.gpu.speed.status"`
	HwMemorySize      MetricConfig `mapstructure:"hw.memory.size"`
	HwMemoryUsage     MetricConfig `mapstructure:"hw.memory.usage"`
	HwStatus          MetricConfig `mapstructure:"hw.status"`
	HwTemperature     MetricConfig `mapstructure:"hw.temperature"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		HwGpuInfo: MetricConfig{
			Enabled: true,
		},
		HwGpuSpeed: MetricConfig{
			Enabled: true,
		},
		HwGpuSpeedLimit: MetricConfig{
			Enabled: true,
		},
		HwGpuSpeedRequest: MetricConfig{
			Enabled: true,
		},
		HwGpuSpeedSamples: MetricConfig{
			Enabled: true,
		},
		HwGpuSpeedStatus: MetricConfig{
			Enabled: true,
		},
		HwMemorySize: MetricConfig{
			Enabled: true,
		},
		HwMemoryUsage: MetricConfig{
			Enabled: true,
		},
		HwStatus: MetricConfig{
			Enabled: true,
		},
		HwTemperature: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for sysman metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
