// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/scraper"
	conventions "go.opentelemetry.io/otel/semconv/v1.38.0"
)

// AttributeAggregation specifies the value aggregation attribute.
type AttributeAggregation int

const (
	_ AttributeAggregation = iota
	AttributeAggregationMin
	AttributeAggregationMax
	AttributeAggregationAvg
)

// String returns the string representation of the AttributeAggregation.
func (av AttributeAggregation) String() string {
	switch av {
	case AttributeAggregationMin:
		return "min"
	case AttributeAggregationMax:
		return "max"
	case AttributeAggregationAvg:
		return "avg"
	}
	return ""
}

// MapAttributeAggregation is a helper map of string to AttributeAggregation attribute value.
var MapAttributeAggregation = map[string]AttributeAggregation{
	"min": AttributeAggregationMin,
	"max": AttributeAggregationMax,
	"avg": AttributeAggregationAvg,
}

// AttributeHwType specifies the value hw.type attribute.
type AttributeHwType int

const (
	_ AttributeHwType = iota
	AttributeHwTypeMemory
	AttributeHwTypeTemperature
)

// String returns the string representation of the AttributeHwType.
func (av AttributeHwType) String() string {
	switch av {
	case AttributeHwTypeMemory:
		return "memory"
	case AttributeHwTypeTemperature:
		return "temperature"
	}
	return ""
}

// MapAttributeHwType is a helper map of string to AttributeHwType attribute value.
var MapAttributeHwType = map[string]AttributeHwType{
	"memory":      AttributeHwTypeMemory,
	"temperature": AttributeHwTypeTemperature,
}

// AttributeSampleStatus specifies the value sample.status attribute.
type AttributeSampleStatus int

const (
	_ AttributeSampleStatus = iota
	AttributeSampleStatusCollected
	AttributeSampleStatusDropped
)

// String returns the string representation of the AttributeSampleStatus.
func (av AttributeSampleStatus) String() string {
	switch av {
	case AttributeSampleStatusCollected:
		return "collected"
	case AttributeSampleStatusDropped:
		return "dropped"
	}
	return ""
}

// MapAttributeSampleStatus is a helper map of string to AttributeSampleStatus attribute value.
var MapAttributeSampleStatus = map[string]AttributeSampleStatus{
	"collected": AttributeSampleStatusCollected,
	"dropped":   AttributeSampleStatusDropped,
}

// AttributeStatistic specifies the value statistic attribute.
type AttributeStatistic int

const (
	_ AttributeStatistic = iota
	AttributeStatisticMin
	AttributeStatisticMax
)

// String returns the string representation of the AttributeStatistic.
func (av AttributeStatistic) String() string {
	switch av {
	case AttributeStatisticMin:
		return "min"
	case AttributeStatisticMax:
		return "max"
	}
	return ""
}

// MapAttributeStatistic is a helper map of string to AttributeStatistic attribute value.
var MapAttributeStatistic = map[string]AttributeStatistic{
	"min": AttributeStatisticMin,
	"max": AttributeStatisticMax,
}

var MetricsInfo = metricsInfo{
	HwGpuInfo: metricInfo{
		Name: "hw.gpu.info",
	},
	HwGpuSpeed: metricInfo{
		Name: "hw.gpu.speed",
	},
	HwGpuSpeedLimit: metricInfo{
		Name: "hw.gpu.speed.limit",
	},
	HwGpuSpeedRequest: metricInfo{
		Name: "hw.gpu.speed.request",
	},
	HwGpuSpeedSamples: metricInfo{
		Name: "hw.gpu.speed.samples",
	},
	HwGpuSpeedStatus: metricInfo{
		Name: "hw.gpu.speed.status",
	},
	HwMemorySize: metricInfo{
		Name: "hw.memory.size",
	},
	HwMemoryUsage: metricInfo{
		Name: "hw.memory.usage",
	},
	HwStatus: metricInfo{
		Name: "hw.status",
	},
	HwTemperature: metricInfo{
		Name: "hw.temperature",
	},
}

type metricsInfo struct {
	HwGpuInfo         metricInfo
	HwGpuSpeed        metricInfo
	HwGpuSpeedLimit   metricInfo
	HwGpuSpeedRequest metricInfo
	HwGpuSpeedSamples metricInfo
	HwGpuSpeedStatus  metricInfo
	HwMemorySize      metricInfo
	HwMemoryUsage     metricInfo
	HwStatus          metricInfo
	HwTemperature     metricInfo
}

type metricInfo struct {
	Name string
}

type metricHwGpuInfo struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.gpu.info metric with initial data.
func (m *metricHwGpuInfo) init() {
	m.data.SetName("hw.gpu.info")
	m.data.SetDescription("Information about the GPU device.")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwGpuInfo) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	dp.Attributes().PutStr("hw.model", hwModelAttributeValue)
	dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	dp.Attributes().PutStr("hw.serial_number", hwSerialNumberAttributeValue)
	dp.Attributes().PutStr("hw.vendor", hwVendorAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwGpuInfo) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwGpuInfo) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwGpuInfo(cfg MetricConfig) metricHwGpuInfo {
	m := metricHwGpuInfo{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwGpuSpeed struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.gpu.speed metric with initial data.
func (m *metricHwGpuSpeed) init() {
	m.data.SetName("hw.gpu.speed")
	m.data.SetDescription("Current GPU frequency.")
	m.data.SetUnit("Hz")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwGpuSpeed) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string, hwGpuSpeedTypeAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string, aggregationAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	dp.Attributes().PutStr("hw.model", hwModelAttributeValue)
	dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	dp.Attributes().PutStr("hw.serial_number", hwSerialNumberAttributeValue)
	dp.Attributes().PutStr("hw.vendor", hwVendorAttributeValue)
	dp.Attributes().PutStr("hw.gpu.speed.type", hwGpuSpeedTypeAttributeValue)
	dp.Attributes().PutStr("com.intel.gpu.subdevice_id", comIntelGpuSubdeviceIDAttributeValue)
	dp.Attributes().PutStr("aggregation", aggregationAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwGpuSpeed) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwGpuSpeed) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwGpuSpeed(cfg MetricConfig) metricHwGpuSpeed {
	m := metricHwGpuSpeed{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwGpuSpeedLimit struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.gpu.speed.limit metric with initial data.
func (m *metricHwGpuSpeedLimit) init() {
	m.data.SetName("hw.gpu.speed.limit")
	m.data.SetDescription("GPU frequency limit.")
	m.data.SetUnit("Hz")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwGpuSpeedLimit) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string, hwGpuSpeedTypeAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string, hwLimitTypeAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	dp.Attributes().PutStr("hw.model", hwModelAttributeValue)
	dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	dp.Attributes().PutStr("hw.serial_number", hwSerialNumberAttributeValue)
	dp.Attributes().PutStr("hw.vendor", hwVendorAttributeValue)
	dp.Attributes().PutStr("hw.gpu.speed.type", hwGpuSpeedTypeAttributeValue)
	dp.Attributes().PutStr("com.intel.gpu.subdevice_id", comIntelGpuSubdeviceIDAttributeValue)
	dp.Attributes().PutStr("hw.limit_type", hwLimitTypeAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwGpuSpeedLimit) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwGpuSpeedLimit) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwGpuSpeedLimit(cfg MetricConfig) metricHwGpuSpeedLimit {
	m := metricHwGpuSpeedLimit{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwGpuSpeedRequest struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.gpu.speed.request metric with initial data.
func (m *metricHwGpuSpeedRequest) init() {
	m.data.SetName("hw.gpu.speed.request")
	m.data.SetDescription("Requested GPU frequency.")
	m.data.SetUnit("Hz")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwGpuSpeedRequest) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string, hwGpuSpeedTypeAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	dp.Attributes().PutStr("hw.model", hwModelAttributeValue)
	dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	dp.Attributes().PutStr("hw.serial_number", hwSerialNumberAttributeValue)
	dp.Attributes().PutStr("hw.vendor", hwVendorAttributeValue)
	dp.Attributes().PutStr("hw.gpu.speed.type", hwGpuSpeedTypeAttributeValue)
	dp.Attributes().PutStr("com.intel.gpu.subdevice_id", comIntelGpuSubdeviceIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwGpuSpeedRequest) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwGpuSpeedRequest) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwGpuSpeedRequest(cfg MetricConfig) metricHwGpuSpeedRequest {
	m := metricHwGpuSpeedRequest{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwGpuSpeedSamples struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.gpu.speed.samples metric with initial data.
func (m *metricHwGpuSpeedSamples) init() {
	m.data.SetName("hw.gpu.speed.samples")
	m.data.SetDescription("Number of speed samples during the last collection interval.")
	m.data.SetUnit("{count}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwGpuSpeedSamples) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string, hwGpuSpeedTypeAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string, sampleStatusAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	dp.Attributes().PutStr("hw.model", hwModelAttributeValue)
	dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	dp.Attributes().PutStr("hw.serial_number", hwSerialNumberAttributeValue)
	dp.Attributes().PutStr("hw.vendor", hwVendorAttributeValue)
	dp.Attributes().PutStr("hw.gpu.speed.type", hwGpuSpeedTypeAttributeValue)
	dp.Attributes().PutStr("com.intel.gpu.subdevice_id", comIntelGpuSubdeviceIDAttributeValue)
	dp.Attributes().PutStr("sample.status", sampleStatusAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwGpuSpeedSamples) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwGpuSpeedSamples) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwGpuSpeedSamples(cfg MetricConfig) metricHwGpuSpeedSamples {
	m := metricHwGpuSpeedSamples{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwGpuSpeedStatus struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.gpu.speed.status metric with initial data.
func (m *metricHwGpuSpeedStatus) init() {
	m.data.SetName("hw.gpu.speed.status")
	m.data.SetDescription("GPU frequency status.")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwGpuSpeedStatus) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string, hwGpuSpeedTypeAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string, hwStateAttributeValue string, comIntelGpuSpeedThrottleReasonAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	dp.Attributes().PutStr("hw.model", hwModelAttributeValue)
	dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	dp.Attributes().PutStr("hw.serial_number", hwSerialNumberAttributeValue)
	dp.Attributes().PutStr("hw.vendor", hwVendorAttributeValue)
	dp.Attributes().PutStr("hw.gpu.speed.type", hwGpuSpeedTypeAttributeValue)
	dp.Attributes().PutStr("com.intel.gpu.subdevice_id", comIntelGpuSubdeviceIDAttributeValue)
	dp.Attributes().PutStr("hw.state", hwStateAttributeValue)
	dp.Attributes().PutStr("com.intel.gpu.speed.throttle_reason", comIntelGpuSpeedThrottleReasonAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwGpuSpeedStatus) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwGpuSpeedStatus) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwGpuSpeedStatus(cfg MetricConfig) metricHwGpuSpeedStatus {
	m := metricHwGpuSpeedStatus{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwMemorySize struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.memory.size metric with initial data.
func (m *metricHwMemorySize) init() {
	m.data.SetName("hw.memory.size")
	m.data.SetDescription("Size of the memory.")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwMemorySize) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwMemoryTypeAttributeValue string, hwNameAttributeValue string, hwParentAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	dp.Attributes().PutStr("hw.memory.type", hwMemoryTypeAttributeValue)
	dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	dp.Attributes().PutStr("hw.parent", hwParentAttributeValue)
	dp.Attributes().PutStr("com.intel.gpu.subdevice_id", comIntelGpuSubdeviceIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwMemorySize) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwMemorySize) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwMemorySize(cfg MetricConfig) metricHwMemorySize {
	m := metricHwMemorySize{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwMemoryUsage struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.memory.usage metric with initial data.
func (m *metricHwMemoryUsage) init() {
	m.data.SetName("hw.memory.usage")
	m.data.SetDescription("Memory used.")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwMemoryUsage) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwMemoryTypeAttributeValue string, hwNameAttributeValue string, hwParentAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	dp.Attributes().PutStr("hw.memory.type", hwMemoryTypeAttributeValue)
	dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	dp.Attributes().PutStr("hw.parent", hwParentAttributeValue)
	dp.Attributes().PutStr("com.intel.gpu.subdevice_id", comIntelGpuSubdeviceIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwMemoryUsage) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwMemoryUsage) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwMemoryUsage(cfg MetricConfig) metricHwMemoryUsage {
	m := metricHwMemoryUsage{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwStatus struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.status metric with initial data.
func (m *metricHwStatus) init() {
	m.data.SetName("hw.status")
	m.data.SetDescription("The operational status of the hardware component.")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwStatus) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwStateAttributeValue string, hwNameAttributeValue string, hwTypeAttributeValue string, hwParentAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	dp.Attributes().PutStr("hw.state", hwStateAttributeValue)
	dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	dp.Attributes().PutStr("hw.type", hwTypeAttributeValue)
	dp.Attributes().PutStr("hw.parent", hwParentAttributeValue)
	dp.Attributes().PutStr("com.intel.gpu.subdevice_id", comIntelGpuSubdeviceIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwStatus) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwStatus) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwStatus(cfg MetricConfig) metricHwStatus {
	m := metricHwStatus{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwTemperature struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.temperature metric with initial data.
func (m *metricHwTemperature) init() {
	m.data.SetName("hw.temperature")
	m.data.SetDescription("Temperature of the hardware component in degrees Celsius.")
	m.data.SetUnit("Cel")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwTemperature) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, hwIDAttributeValue string, hwNameAttributeValue string, hwParentAttributeValue string, hwSensorLocationAttributeValue string, statisticAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	dp.Attributes().PutStr("hw.parent", hwParentAttributeValue)
	dp.Attributes().PutStr("hw.sensor_location", hwSensorLocationAttributeValue)
	dp.Attributes().PutStr("statistic", statisticAttributeValue)
	dp.Attributes().PutStr("com.intel.gpu.subdevice_id", comIntelGpuSubdeviceIDAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwTemperature) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwTemperature) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwTemperature(cfg MetricConfig) metricHwTemperature {
	m := metricHwTemperature{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                  MetricsBuilderConfig // config of the metrics builder.
	startTime               pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity         int                  // maximum observed number of metrics per resource.
	metricsBuffer           pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo               component.BuildInfo  // contains version information.
	metricHwGpuInfo         metricHwGpuInfo
	metricHwGpuSpeed        metricHwGpuSpeed
	metricHwGpuSpeedLimit   metricHwGpuSpeedLimit
	metricHwGpuSpeedRequest metricHwGpuSpeedRequest
	metricHwGpuSpeedSamples metricHwGpuSpeedSamples
	metricHwGpuSpeedStatus  metricHwGpuSpeedStatus
	metricHwMemorySize      metricHwMemorySize
	metricHwMemoryUsage     metricHwMemoryUsage
	metricHwStatus          metricHwStatus
	metricHwTemperature     metricHwTemperature
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings scraper.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                  mbc,
		startTime:               pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:           pmetric.NewMetrics(),
		buildInfo:               settings.BuildInfo,
		metricHwGpuInfo:         newMetricHwGpuInfo(mbc.Metrics.HwGpuInfo),
		metricHwGpuSpeed:        newMetricHwGpuSpeed(mbc.Metrics.HwGpuSpeed),
		metricHwGpuSpeedLimit:   newMetricHwGpuSpeedLimit(mbc.Metrics.HwGpuSpeedLimit),
		metricHwGpuSpeedRequest: newMetricHwGpuSpeedRequest(mbc.Metrics.HwGpuSpeedRequest),
		metricHwGpuSpeedSamples: newMetricHwGpuSpeedSamples(mbc.Metrics.HwGpuSpeedSamples),
		metricHwGpuSpeedStatus:  newMetricHwGpuSpeedStatus(mbc.Metrics.HwGpuSpeedStatus),
		metricHwMemorySize:      newMetricHwMemorySize(mbc.Metrics.HwMemorySize),
		metricHwMemoryUsage:     newMetricHwMemoryUsage(mbc.Metrics.HwMemoryUsage),
		metricHwStatus:          newMetricHwStatus(mbc.Metrics.HwStatus),
		metricHwTemperature:     newMetricHwTemperature(mbc.Metrics.HwTemperature),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	rm.SetSchemaUrl(conventions.SchemaURL)
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricHwGpuInfo.emit(ils.Metrics())
	mb.metricHwGpuSpeed.emit(ils.Metrics())
	mb.metricHwGpuSpeedLimit.emit(ils.Metrics())
	mb.metricHwGpuSpeedRequest.emit(ils.Metrics())
	mb.metricHwGpuSpeedSamples.emit(ils.Metrics())
	mb.metricHwGpuSpeedStatus.emit(ils.Metrics())
	mb.metricHwMemorySize.emit(ils.Metrics())
	mb.metricHwMemoryUsage.emit(ils.Metrics())
	mb.metricHwStatus.emit(ils.Metrics())
	mb.metricHwTemperature.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordHwGpuInfoDataPoint adds a data point to hw.gpu.info metric.
func (mb *MetricsBuilder) RecordHwGpuInfoDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string) {
	mb.metricHwGpuInfo.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwModelAttributeValue, hwNameAttributeValue, hwSerialNumberAttributeValue, hwVendorAttributeValue)
}

// RecordHwGpuSpeedDataPoint adds a data point to hw.gpu.speed metric.
func (mb *MetricsBuilder) RecordHwGpuSpeedDataPoint(ts pcommon.Timestamp, val float64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string, hwGpuSpeedTypeAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string, aggregationAttributeValue AttributeAggregation) {
	mb.metricHwGpuSpeed.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwModelAttributeValue, hwNameAttributeValue, hwSerialNumberAttributeValue, hwVendorAttributeValue, hwGpuSpeedTypeAttributeValue, comIntelGpuSubdeviceIDAttributeValue, aggregationAttributeValue.String())
}

// RecordHwGpuSpeedLimitDataPoint adds a data point to hw.gpu.speed.limit metric.
func (mb *MetricsBuilder) RecordHwGpuSpeedLimitDataPoint(ts pcommon.Timestamp, val float64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string, hwGpuSpeedTypeAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string, hwLimitTypeAttributeValue string) {
	mb.metricHwGpuSpeedLimit.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwModelAttributeValue, hwNameAttributeValue, hwSerialNumberAttributeValue, hwVendorAttributeValue, hwGpuSpeedTypeAttributeValue, comIntelGpuSubdeviceIDAttributeValue, hwLimitTypeAttributeValue)
}

// RecordHwGpuSpeedRequestDataPoint adds a data point to hw.gpu.speed.request metric.
func (mb *MetricsBuilder) RecordHwGpuSpeedRequestDataPoint(ts pcommon.Timestamp, val float64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string, hwGpuSpeedTypeAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string) {
	mb.metricHwGpuSpeedRequest.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwModelAttributeValue, hwNameAttributeValue, hwSerialNumberAttributeValue, hwVendorAttributeValue, hwGpuSpeedTypeAttributeValue, comIntelGpuSubdeviceIDAttributeValue)
}

// RecordHwGpuSpeedSamplesDataPoint adds a data point to hw.gpu.speed.samples metric.
func (mb *MetricsBuilder) RecordHwGpuSpeedSamplesDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string, hwGpuSpeedTypeAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string, sampleStatusAttributeValue AttributeSampleStatus) {
	mb.metricHwGpuSpeedSamples.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwModelAttributeValue, hwNameAttributeValue, hwSerialNumberAttributeValue, hwVendorAttributeValue, hwGpuSpeedTypeAttributeValue, comIntelGpuSubdeviceIDAttributeValue, sampleStatusAttributeValue.String())
}

// RecordHwGpuSpeedStatusDataPoint adds a data point to hw.gpu.speed.status metric.
func (mb *MetricsBuilder) RecordHwGpuSpeedStatusDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwModelAttributeValue string, hwNameAttributeValue string, hwSerialNumberAttributeValue string, hwVendorAttributeValue string, hwGpuSpeedTypeAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string, hwStateAttributeValue string, comIntelGpuSpeedThrottleReasonAttributeValue string) {
	mb.metricHwGpuSpeedStatus.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwModelAttributeValue, hwNameAttributeValue, hwSerialNumberAttributeValue, hwVendorAttributeValue, hwGpuSpeedTypeAttributeValue, comIntelGpuSubdeviceIDAttributeValue, hwStateAttributeValue, comIntelGpuSpeedThrottleReasonAttributeValue)
}

// RecordHwMemorySizeDataPoint adds a data point to hw.memory.size metric.
func (mb *MetricsBuilder) RecordHwMemorySizeDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwMemoryTypeAttributeValue string, hwNameAttributeValue string, hwParentAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string) {
	mb.metricHwMemorySize.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwMemoryTypeAttributeValue, hwNameAttributeValue, hwParentAttributeValue, comIntelGpuSubdeviceIDAttributeValue)
}

// RecordHwMemoryUsageDataPoint adds a data point to hw.memory.usage metric.
func (mb *MetricsBuilder) RecordHwMemoryUsageDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwMemoryTypeAttributeValue string, hwNameAttributeValue string, hwParentAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string) {
	mb.metricHwMemoryUsage.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwMemoryTypeAttributeValue, hwNameAttributeValue, hwParentAttributeValue, comIntelGpuSubdeviceIDAttributeValue)
}

// RecordHwStatusDataPoint adds a data point to hw.status metric.
func (mb *MetricsBuilder) RecordHwStatusDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwStateAttributeValue string, hwNameAttributeValue string, hwTypeAttributeValue AttributeHwType, hwParentAttributeValue string, comIntelGpuSubdeviceIDAttributeValue string) {
	mb.metricHwStatus.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwStateAttributeValue, hwNameAttributeValue, hwTypeAttributeValue.String(), hwParentAttributeValue, comIntelGpuSubdeviceIDAttributeValue)
}

// RecordHwTemperatureDataPoint adds a data point to hw.temperature metric.
func (mb *MetricsBuilder) RecordHwTemperatureDataPoint(ts pcommon.Timestamp, val float64, hwIDAttributeValue string, hwNameAttributeValue string, hwParentAttributeValue string, hwSensorLocationAttributeValue string, statisticAttributeValue AttributeStatistic, comIntelGpuSubdeviceIDAttributeValue string) {
	mb.metricHwTemperature.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwNameAttributeValue, hwParentAttributeValue, hwSensorLocationAttributeValue, statisticAttributeValue.String(), comIntelGpuSubdeviceIDAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
