[unix_http_server]
file = ./tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
pidfile = ./tmp/supervisord.pid
logfile = ./tmp/supervisord.log

[supervisorctl]
serverurl=unix://./tmp/supervisor.sock

[program:xpum]
directory=./py/
command=python DGM.py
stdout_logfile=./tmp/output.log
stderr_logfile=./tmp/output.log