// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I../level-zero ./types.go

package sysman

import (
	"unsafe"

	"github.com/google/uuid"
	"github.com/intel/level-zero-go/core"
)

// driverHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-driver-handle-t
type driverHandle *_Ctype_struct__ze_driver_handle_t

// deviceHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-handle-t
type deviceHandle *_Ctype_struct__ze_device_handle_t

// schedHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-sched-handle-t
type schedHandle *_Ctype_struct__zes_sched_handle_t

// perfHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-perf-handle-t
type perfHandle *_Ctype_struct__zes_perf_handle_t

// pwrHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pwr-handle-t
type pwrHandle *_Ctype_struct__zes_pwr_handle_t

// freqHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-freq-handle-t
type freqHandle *_Ctype_struct__zes_freq_handle_t

// engineHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-engine-handle-t
type engineHandle *_Ctype_struct__zes_engine_handle_t

// standbyHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-standby-handle-t
type standbyHandle *_Ctype_struct__zes_standby_handle_t

// firmwareHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-firmware-handle-t
type firmwareHandle *_Ctype_struct__zes_firmware_handle_t

// memHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-mem-handle-t
type memHandle *_Ctype_struct__zes_mem_handle_t

// fabricPortHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-handle-t
type fabricPortHandle *_Ctype_struct__zes_fabric_port_handle_t

// tempHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-temp-handle-t
type tempHandle *_Ctype_struct__zes_temp_handle_t

// psuHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-psu-handle-t
type psuHandle *_Ctype_struct__zes_psu_handle_t

// fanHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fan-handle-t
type fanHandle *_Ctype_struct__zes_fan_handle_t

// ledHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-led-handle-t
type ledHandle *_Ctype_struct__zes_led_handle_t

// rasHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-ras-handle-t
type rasHandle *_Ctype_struct__zes_ras_handle_t

// diagHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-diag-handle-t
type diagHandle *_Ctype_struct__zes_diag_handle_t

// overclockHandle declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-overclock-handle-t
type overclockHandle *_Ctype_struct__zes_overclock_handle_t

// DriverExtensionProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-driver-extension-properties-t
//
// Extension properties queried using zesDriverGetExtensionProperties.
type DriverExtensionProperties struct {
	Name    core.StringProperty256
	Version uint32
}

// DeviceState declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-state-t
//
// Device state.
type DeviceState struct {
	stype    structureType
	pnext    unsafe.Pointer
	Reset    ResetReasonFlags
	Repaired RepairStatus
}

// ResetProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-reset-properties-t
//
// Device reset properties.
type ResetProperties struct {
	stype     structureType
	pnext     unsafe.Pointer
	Force     uint8
	ResetType ResetType
}

// Uuid declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-uuid-t
//
// Device universal unique id (UUID)
type Uuid struct {
	Id uuid.UUID
}

// DeviceBaseProperties is the device properties type declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-properties-t
type DeviceBaseProperties struct {
	stype         structureType
	pnext         unsafe.Pointer
	Core          core.DeviceProperties
	NumSubdevices uint32
	SerialNumber  core.StringProperty64
	BoardNumber   core.StringProperty64
	BrandName     core.StringProperty64
	ModelName     core.StringProperty64
	VendorName    core.StringProperty64
	DriverVersion core.StringProperty64
	_             [4]byte
}

// DeviceExtProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-ext-properties-t
//
// Device properties.
type DeviceExtProperties struct {
	stype structureType
	pnext unsafe.Pointer
	Uuid  Uuid
	Type  DeviceType
	Flags DevicePropertyFlags
}

// ProcessState declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-process-state-t
//
// Contains information about a process that has an open connection with this device.
//
//   - The application can use the process ID to query the OS for the owner and the
//     path to the executable.
type ProcessState struct {
	stype      structureType
	pnext      unsafe.Pointer
	ProcessId  uint32
	MemSize    uint64
	SharedSize uint64
	Engines    EngineTypeFlags
	_          [4]byte
}

// PciAddress declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-address-t
//
// PCI address.
type PciAddress struct {
	Domain   uint32
	Bus      uint32
	Device   uint32
	Function uint32
}

// PciSpeed declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-speed-t
//
// PCI speed.
type PciSpeed struct {
	Gen          int32
	Width        int32
	MaxBandwidth int64
}

// PciBaseProperties is the PCI properties type declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-properties-t
type PciBaseProperties struct {
	stype                 structureType
	pnext                 unsafe.Pointer
	Address               PciAddress
	MaxSpeed              PciSpeed
	HaveBandwidthCounters uint8
	HavePacketCounters    uint8
	HaveReplayCounters    uint8
	_                     [5]byte
}

// PciBaseState is the PCI state type declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-state-t
type PciBaseState struct {
	stype           structureType
	pnext           unsafe.Pointer
	Status          PciLinkStatus
	QualityIssues   PciLinkQualIssueFlags
	StabilityIssues PciLinkStabIssueFlags
	Speed           PciSpeed
}

// PciBarProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-bar-properties-t
//
// Properties of a pci bar.
type PciBarProperties struct {
	stype structureType
	pnext unsafe.Pointer
	Type  PciBarType
	Index uint32
	Base  uint64
	Size  uint64
}

// PciBarProperties12 declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-bar-properties12-t
//
// Properties of a pci bar, including the resizable bar.
type PciBarProperties12 struct {
	stype                 structureType
	pnext                 unsafe.Pointer
	Type                  PciBarType
	Index                 uint32
	Base                  uint64
	Size                  uint64
	ResizableBarSupported uint8
	ResizableBarEnabled   uint8
	_                     [6]byte
}

// PciStats declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-stats-t
//
// PCI stats counters.
//
//   - Percent replays is calculated by taking two snapshots (s1, s2) and using the
//     equation: replay = 10^6 * (s2.replayCounter - s1.replayCounter) / (s2.maxBandwidth
//   - (s2.timestamp - s1.timestamp))
//   - Percent throughput is calculated by taking two snapshots (s1, s2) and using the
//     equation: bw = 10^6 * ((s2.rxCounter - s1.rxCounter) + (s2.txCounter -
//     s1.txCounter)) / (s2.maxBandwidth * (s2.timestamp - s1.timestamp))
type PciStats struct {
	Timestamp     uint64
	ReplayCounter uint64
	PacketCounter uint64
	RxCounter     uint64
	TxCounter     uint64
	Speed         PciSpeed
}

// OverclockProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-overclock-properties-t
//
// Overclock properties.
//
//   - Information on the overclock domain type and all the contols that are part of
//     the domain.
type OverclockProperties struct {
	stype             structureType
	pnext             unsafe.Pointer
	DomainType        OverclockDomain
	AvailableControls OverclockControls
	VFProgramType     VfProgramType
	NumberOfVFPoints  uint32
}

// ControlProperty declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-control-property-t
//
// Overclock Control properties.
//
//   - Provides all the control capabilities supported by the device for the overclock
//     domain.
type ControlProperty struct {
	MinValue     float64
	MaxValue     float64
	StepValue    float64
	RefValue     float64
	DefaultValue float64
}

// VfProperty declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-vf-property-t
//
// Overclock VF properties.
//
//   - Provides all the VF capabilities supported by the device for the overclock
//     domain.
type VfProperty struct {
	MinFreq  float64
	MaxFreq  float64
	StepFreq float64
	MinVolt  float64
	MaxVolt  float64
	StepVolt float64
}

// DiagTest declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-diag-test-t
//
// Diagnostic test.
type DiagTest struct {
	Index uint32
	Name  core.StringProperty64
}

// DiagProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-diag-properties-t
//
// Diagnostics test suite properties.
type DiagProperties struct {
	stype       structureType
	pnext       unsafe.Pointer
	OnSubdevice uint8
	SubdeviceId uint32
	Name        core.StringProperty64
	HaveTests   uint8
	_           [7]byte
}

// DeviceEccDesc declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-ecc-desc-t
//
// ECC State Descriptor.
type DeviceEccDesc struct {
	stype structureType
	pnext unsafe.Pointer
	State DeviceEccState
	_     [4]byte
}

// DeviceEccProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-ecc-properties-t
//
// ECC State.
type DeviceEccProperties struct {
	stype         structureType
	pnext         unsafe.Pointer
	CurrentState  DeviceEccState
	PendingState  DeviceEccState
	PendingAction DeviceAction
	_             [4]byte
}

// EngineBaseProperties is the engine properties type declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-engine-properties-t
type EngineBaseProperties struct {
	stype       structureType
	pnext       unsafe.Pointer
	Type        EngineGroup
	OnSubdevice uint8
	SubdeviceId uint32
	_           [4]byte
}

// EngineStats declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-engine-stats-t
//
// Engine activity counters.
//
//   - Percent utilization is calculated by taking two snapshots (s1, s2) and using
//     the equation: util = (s2.activeTime - s1.activeTime) / (s2.timestamp - s1.timestamp)
//   - The time units are implementation-specific since the value is only intended to
//     be used for calculating utilization percentage.
//   - The should only be used to calculate delta between snapshots of this structure.
//   - The application should never take the delta of with the timestamp from a different
//     structure since they are not guaranteed to have the same base.
//   - When taking the delta, the difference between samples could be , if the frequency
//     of sampling the snapshots is higher than the frequency of the timestamp update.
//   - The absolute value of is only valid during within the application and may be
//     different on the next execution.
type EngineStats struct {
	ActiveTime uint64
	Timestamp  uint64
}

// FabricPortId declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-id-t
//
// Unique identifier for a fabric port.
//
//   - This not a universal identifier. The identified is garanteed to be unique for
//     the current hardware configuration of the system. Changes in the hardware may
//     result in a different identifier for a given port.
//   - The main purpose of this identifier to build up an instantaneous topology map
//     of system connectivity. An application should enumerate all fabric ports and
//     match the member of zes_fabric_port_state_t to the member of zes_fabric_port_properties_t.
type FabricPortId struct {
	FabricId   uint32
	AttachId   uint32
	PortNumber uint8
	_          [3]byte
}

// FabricPortSpeed declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-speed-t
//
// Fabric port speed in one direction.
type FabricPortSpeed struct {
	BitRate int64
	Width   int32
	_       [4]byte
}

// FabricPortProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-properties-t
//
// Fabric port properties.
type FabricPortProperties struct {
	stype       structureType
	pnext       unsafe.Pointer
	Model       core.StringProperty256
	OnSubdevice uint8
	SubdeviceId uint32
	PortId      FabricPortId
	MaxRxSpeed  FabricPortSpeed
	MaxTxSpeed  FabricPortSpeed
}

// FabricLinkType declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-link-type-t
//
// Provides information about the fabric link attached to a port.
type FabricLinkType struct {
	Desc core.StringProperty256
}

// FabricPortConfig declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-config-t
//
// Fabric port configuration.
type FabricPortConfig struct {
	stype     structureType
	pnext     unsafe.Pointer
	Enabled   uint8
	Beaconing uint8
	_         [6]byte
}

// FabricPortState declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-state-t
//
// Fabric port state.
type FabricPortState struct {
	stype          structureType
	pnext          unsafe.Pointer
	Status         FabricPortStatus
	QualityIssues  FabricPortQualIssueFlags
	FailureReasons FabricPortFailureFlags
	RemotePortId   FabricPortId
	RxSpeed        FabricPortSpeed
	TxSpeed        FabricPortSpeed
}

// FabricPortThroughput declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-throughput-t
//
// Fabric port throughput.
type FabricPortThroughput struct {
	Timestamp uint64
	RxCounter uint64
	TxCounter uint64
}

// FabricPortErrorCounters declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-error-counters-t
//
// Fabric Port Error Counters.
type FabricPortErrorCounters struct {
	stype            structureType
	pnext            unsafe.Pointer
	LinkFailureCount uint64
	FwCommErrorCount uint64
	FwErrorCount     uint64
	LinkDegradeCount uint64
}

// FanSpeed declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fan-speed-t
//
// Fan speed.
type FanSpeed struct {
	Speed int32
	Units FanSpeedUnits
}

// FanTempSpeed declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fan-temp-speed-t
//
// Fan temperature/speed pair.
type FanTempSpeed struct {
	Temperature uint32
	Speed       FanSpeed
}

// FanSpeedTable declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fan-speed-table-t
//
// Fan speed table.
type FanSpeedTable struct {
	NumPoints int32
	Table     [32]FanTempSpeed
}

// FanProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fan-properties-t
//
// Fan properties.
type FanProperties struct {
	stype          structureType
	pnext          unsafe.Pointer
	OnSubdevice    uint8
	SubdeviceId    uint32
	CanControl     uint8
	SupportedModes uint32
	SupportedUnits uint32
	MaxRPM         int32
	MaxPoints      int32
	_              [4]byte
}

// FanConfig declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fan-config-t
//
// Fan configuration.
type FanConfig struct {
	stype      structureType
	pnext      unsafe.Pointer
	Mode       FanSpeedMode
	SpeedFixed FanSpeed
	SpeedTable FanSpeedTable
}

// FirmwareProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-firmware-properties-t
//
// Firmware properties.
type FirmwareProperties struct {
	stype       structureType
	pnext       unsafe.Pointer
	OnSubdevice uint8
	SubdeviceId uint32
	CanControl  uint8
	Name        core.StringProperty64
	Version     core.StringProperty64
	_           [7]byte
}

// FreqProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-freq-properties-t
//
// Frequency properties.
//
//   - Indicates if this frequency domain can be overclocked (if true, functions such
//     as zesFrequencyOcSetFrequencyTarget() are supported).
//   - The min/max hardware frequencies are specified for non-overclock configurations.
//     For overclock configurations, use zesFrequencyOcGetFrequencyTarget() to determine
//     the maximum frequency that can be requested.
type FreqProperties struct {
	stype                    structureType
	pnext                    unsafe.Pointer
	Type                     FreqDomain
	OnSubdevice              uint8
	SubdeviceId              uint32
	CanControl               uint8
	IsThrottleEventSupported uint8
	Min                      float64
	Max                      float64
}

// FreqRange declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-freq-range-t
//
// Frequency range between which the hardware can operate.
//
//   - When setting limits, they will be clamped to the hardware limits.
//   - When setting limits, ensure that the max frequency is greater than or equal to
//     the min frequency specified.
//   - When setting limits to return to factory settings, specify -1 for both the min
//     and max limit.
type FreqRange struct {
	Min float64
	Max float64
}

// FreqState declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-freq-state-t
//
// Frequency state.
type FreqState struct {
	stype           structureType
	pnext           unsafe.Pointer
	CurrentVoltage  float64
	Request         float64
	Tdp             float64
	Efficient       float64
	Actual          float64
	ThrottleReasons FreqThrottleReasonFlags
	_               [4]byte
}

// FreqThrottleTime declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-freq-throttle-time-t
//
// Frequency throttle time snapshot.
//
//   - Percent time throttled is calculated by taking two snapshots (s1, s2) and using
//     the equation: throttled = (s2.throttleTime - s1.throttleTime) / (s2.timestamp
//   - s1.timestamp)
type FreqThrottleTime struct {
	ThrottleTime uint64
	Timestamp    uint64
}

// LedProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-led-properties-t
//
// LED properties.
type LedProperties struct {
	stype       structureType
	pnext       unsafe.Pointer
	OnSubdevice uint8
	SubdeviceId uint32
	CanControl  uint8
	HaveRGB     uint8
	_           [6]byte
}

// LedColor declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-led-color-t
//
// LED color.
type LedColor struct {
	Red   float64
	Green float64
	Blue  float64
}

// LedState declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-led-state-t
//
// LED state.
type LedState struct {
	stype structureType
	pnext unsafe.Pointer
	IsOn  uint8
	Color LedColor
}

// MemProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-mem-properties-t
//
// Memory properties.
type MemProperties struct {
	stype        structureType
	pnext        unsafe.Pointer
	Type         MemType
	OnSubdevice  uint8
	SubdeviceId  uint32
	Location     MemLoc
	PhysicalSize uint64
	BusWidth     int32
	NumChannels  int32
}

// MemState declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-mem-state-t
//
// Memory state - health, allocated.
//
// - Percent free is given by 100 * free / pysical mem size.
type MemState struct {
	stype  structureType
	pnext  unsafe.Pointer
	Health MemHealth
	Free   uint64
	Size   uint64
}

// MemBandwidth declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-mem-bandwidth-t
//
// Memory bandwidth.
//
//   - Percent bandwidth is calculated by taking two snapshots (s1, s2) and using the
//     equation: bw = 10^6 * ((s2.readCounter - s1.readCounter) + (s2.writeCounter -
//     s1.writeCounter)) / (s2.maxBandwidth * (s2.timestamp - s1.timestamp))
//   - Counter can roll over and rollover needs to be handled by comparing the current
//     read against the previous read
//   - Counter is a 32 byte transaction count, which means the calculated delta (delta
//     = current_value - previous_value or delta = 2^32 - previous_value + current_value
//     in case of rollover) needs to be multiplied by 32 to get delta between samples
//     in actual byte count
type MemBandwidth struct {
	ReadCounter  uint64
	WriteCounter uint64
	MaxBandwidth uint64
	Timestamp    uint64
}

// PerfProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-perf-properties-t
//
// Static information about a Performance Factor domain.
type PerfProperties struct {
	stype       structureType
	pnext       unsafe.Pointer
	OnSubdevice uint8
	SubdeviceId uint32
	Engines     EngineTypeFlags
	_           [4]byte
}

// PowerBaseProperties is the power properties type declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-power-properties-t
type PowerBaseProperties struct {
	stype                      structureType
	pnext                      unsafe.Pointer
	OnSubdevice                uint8
	SubdeviceId                uint32
	CanControl                 uint8
	IsEnergyThresholdSupported uint8
	DefaultLimit               int32
	MinLimit                   int32
	MaxLimit                   int32
}

// PowerEnergyCounter declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-power-energy-counter-t
//
// Energy counter snapshot.
//
//   - Average power is calculated by taking two snapshots (s1, s2) and using the
//     equation: PowerWatts = (s2.energy - s1.energy) / (s2.timestamp - s1.timestamp)
type PowerEnergyCounter struct {
	Energy    uint64
	Timestamp uint64
}

// EnergyThreshold declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-energy-threshold-t
//
// Energy threshold.
//
// - .
type EnergyThreshold struct {
	Enable    uint8
	Threshold float64
	ProcessId uint32
	_         [4]byte
}

// PsuProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-psu-properties-t
//
// Static properties of the power supply.
type PsuProperties struct {
	stype       structureType
	pnext       unsafe.Pointer
	OnSubdevice uint8
	SubdeviceId uint32
	HaveFan     uint8
	AmpLimit    int32
}

// PsuState declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-psu-state-t
//
// Dynamic state of the power supply.
type PsuState struct {
	stype       structureType
	pnext       unsafe.Pointer
	VoltStatus  PsuVoltageStatus
	FanFailed   uint8
	Temperature int32
	Current     int32
}

// RasProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-ras-properties-t
//
// RAS properties.
type RasProperties struct {
	stype       structureType
	pnext       unsafe.Pointer
	Type        RasErrorType
	OnSubdevice uint8
	SubdeviceId uint32
	_           [4]byte
}

// RasState declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-ras-state-t
//
// RAS error details.
type RasState struct {
	stype    structureType
	pnext    unsafe.Pointer
	Category [7]uint64
}

// RasConfig declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-ras-config-t
//
// RAS error configuration - thresholds used for triggering RAS events
// (ZES_EVENT_TYPE_FLAG_RAS_CORRECTABLE_ERRORS, ZES_EVENT_TYPE_FLAG_RAS_UNCORRECTABLE_ERRORS)
//
//   - The driver maintains a total counter which is updated every time a hardware
//     block covered by the corresponding RAS error set notifies that an error has
//     occurred. When this total count goes above the totalThreshold specified below,
//     a RAS event is triggered.
//   - The driver also maintains a counter for each category of RAS error (see
//     zes_ras_state_t for a breakdown). Each time a hardware block of that category
//     notifies that an error has occurred, that corresponding category counter is
//     updated. When it goes above the threshold specified in detailedThresholds, a
//     RAS event is triggered.
type RasConfig struct {
	stype              structureType
	pnext              unsafe.Pointer
	TotalThreshold     uint64
	DetailedThresholds RasState
}

// SchedProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-sched-properties-t
//
// Properties related to scheduler component.
type SchedProperties struct {
	stype          structureType
	pnext          unsafe.Pointer
	OnSubdevice    uint8
	SubdeviceId    uint32
	CanControl     uint8
	Engines        EngineTypeFlags
	SupportedModes uint32
	_              [4]byte
}

// SchedTimeoutProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-sched-timeout-properties-t
//
// Configuration for timeout scheduler mode (ZES_SCHED_MODE_TIMEOUT)
type SchedTimeoutProperties struct {
	stype           structureType
	pnext           unsafe.Pointer
	WatchdogTimeout uint64
}

// SchedTimesliceProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-sched-timeslice-properties-t
//
// Configuration for timeslice scheduler mode (ZES_SCHED_MODE_TIMESLICE)
type SchedTimesliceProperties struct {
	stype        structureType
	pnext        unsafe.Pointer
	Interval     uint64
	YieldTimeout uint64
}

// StandbyProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-standby-properties-t
//
// Standby hardware component properties.
type StandbyProperties struct {
	stype       structureType
	pnext       unsafe.Pointer
	Type        StandbyType
	OnSubdevice uint8
	SubdeviceId uint32
	_           [4]byte
}

// TempProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-temp-properties-t
//
// Temperature sensor properties.
type TempProperties struct {
	stype                   structureType
	pnext                   unsafe.Pointer
	Type                    TempSensors
	OnSubdevice             uint8
	SubdeviceId             uint32
	MaxTemperature          float64
	IsCriticalTempSupported uint8
	IsThreshold1Supported   uint8
	IsThreshold2Supported   uint8
	_                       [5]byte
}

// TempThreshold declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-temp-threshold-t
//
// Temperature sensor threshold.
type TempThreshold struct {
	EnableLowToHigh uint8
	EnableHighToLow uint8
	Threshold       float64
}

// TempConfig declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-temp-config-t
//
// Temperature configuration - which events should be triggered and the trigger
// conditions.
type TempConfig struct {
	stype          structureType
	pnext          unsafe.Pointer
	EnableCritical uint8
	Threshold1     TempThreshold
	Threshold2     TempThreshold
}

// DeviceEccDefaultPropertiesExt declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-ecc-default-properties-ext-t
//
// This structure may be passed to zesDeviceGetEccState as pNext member of
// zes_device_ecc_properties_t.
type DeviceEccDefaultPropertiesExt struct {
	stype        structureType
	pnext        unsafe.Pointer
	DefaultState DeviceEccState
	_            [4]byte
}

// PciLinkSpeedDowngradeExtState declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-link-speed-downgrade-ext-state-t
//
// Query PCIe downgrade status.
//
// - This structure can be passed in the 'pNext' of zes_pci_state_t
type PciLinkSpeedDowngradeExtState struct {
	stype                       structureType
	pnext                       unsafe.Pointer
	PciLinkSpeedDowngradeStatus uint8
	_                           [7]byte
}

// PciLinkSpeedDowngradeExtProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-link-speed-downgrade-ext-properties-t
//
// Query PCIe downgrade capability.
//
// - This structure can be passed in the 'pNext' of zes_pci_properties_t
type PciLinkSpeedDowngradeExtProperties struct {
	stype                     structureType
	pnext                     unsafe.Pointer
	PciLinkSpeedUpdateCapable uint8
	MaxPciGenSupported        int32
}

// PowerLimitExtDesc declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-power-limit-ext-desc-t
//
// Device power/current limit descriptor.
type PowerLimitExtDesc struct {
	stype               structureType
	pnext               unsafe.Pointer
	Level               PowerLevel
	Source              PowerSource
	LimitUnit           LimitUnit
	EnabledStateLocked  uint8
	Enabled             uint8
	IntervalValueLocked uint8
	Interval            int32
	LimitValueLocked    uint8
	Limit               int32
	_                   [4]byte
}

// PowerExtProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-power-ext-properties-t
//
// Extension properties related to device power settings.
//
//   - This structure may be returned from zesPowerGetProperties via the member of
//     zes_power_properties_t.
//   - This structure may also be returned from zesPowerGetProperties via the member
//     of zes_power_ext_properties_t
//   - Used for determining the power domain level, i.e. card-level v/s package-level
//     v/s stack-level & the factory default power limits.
type PowerExtProperties struct {
	stype        structureType
	pnext        unsafe.Pointer
	Domain       PowerDomain
	DefaultLimit *PowerLimitExtDesc
}

// EngineExtProperties declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-engine-ext-properties-t
//
// Extension properties related to Engine Groups.
//
//   - This structure may be passed to zesEngineGetProperties by having the pNext
//     member of zes_engine_properties_t point at this struct.
//   - Used for SRIOV per Virtual Function device utilization by zes_engine_group_t
type EngineExtProperties struct {
	stype                          structureType
	pnext                          unsafe.Pointer
	CountOfVirtualFunctionInstance uint32
	_                              [4]byte
}

// InitFlags declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-init-flags-t
//
// Supported sysman initialization flags.
type InitFlags InitFlag

// EngineTypeFlags declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-engine-type-flags-t
//
// Types of accelerator engines.
type EngineTypeFlags EngineTypeFlag

// ResetReasonFlags declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-reset-reason-flags-t
//
// Device reset reasons.
type ResetReasonFlags ResetReasonFlag

// DevicePropertyFlags declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-property-flags-t
//
// Supported device property flags.
type DevicePropertyFlags DevicePropertyFlag

// PciLinkQualIssueFlags declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-link-qual-issue-flags-t
//
// PCI link quality degradation reasons.
type PciLinkQualIssueFlags PciLinkQualIssueFlag

// PciLinkStabIssueFlags declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-link-stab-issue-flags-t
//
// PCI link stability issues.
type PciLinkStabIssueFlags PciLinkStabIssueFlag

// EventTypeFlags declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-event-type-flags-t
//
// Event types.
type EventTypeFlags EventTypeFlag

// FabricPortQualIssueFlags declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-qual-issue-flags-t
//
// Fabric port quality degradation reasons.
type FabricPortQualIssueFlags FabricPortQualIssueFlag

// FabricPortFailureFlags declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-failure-flags-t
//
// Fabric port failure reasons.
type FabricPortFailureFlags FabricPortFailureFlag

// FreqThrottleReasonFlags declared in:
// https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-freq-throttle-reason-flags-t
//
// Frequency throttle reasons.
type FreqThrottleReasonFlags FreqThrottleReasonFlag
