// Code generated by "stringer -type=DeviceEccState -trimprefix=DEVICE_ECC_STATE_ -output=zz_DeviceEccState_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEVICE_ECC_STATE_UNAVAILABLE-0]
	_ = x[DEVICE_ECC_STATE_ENABLED-1]
	_ = x[DEVICE_ECC_STATE_DISABLED-2]
	_ = x[DEVICE_ECC_STATE_FORCE_UINT32-2147483647]
}

const (
	_DeviceEccState_name_0 = "UNAVAILABLEENABLEDDISABLED"
	_DeviceEccState_name_1 = "FORCE_UINT32"
)

var (
	_DeviceEccState_index_0 = [...]uint8{0, 11, 18, 26}
)

func (i DeviceEccState) String() string {
	switch {
	case i <= 2:
		return _DeviceEccState_name_0[_DeviceEccState_index_0[i]:_DeviceEccState_index_0[i+1]]
	case i == 2147483647:
		return _DeviceEccState_name_1
	default:
		return "DeviceEccState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
