apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xpu-exporter.fullname" . }}-config
  labels:
    {{- include "xpu-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ .Values.config | toYaml | indent 4 }}
