#!/usr/bin/python3
import argparse

import json

import pprint
import requests

from texttable import Texttable

import os

os.environ['NO_PROXY'] = 'localhost'

host = "http://localhost:5000"

parser = argparse.ArgumentParser()
parser.add_argument('-l', '--list', action='store_true',
                    help='list all device')
parser.add_argument('-i', '--immed', action='store_true',
                    help='get realtime measuring data')
parser.add_argument('-d', '--device', help='specify a device by `GPU ID`')
parser.add_argument('-f', '--freq', action='store_true',
                    help='get latest frequency of gpu')
parser.add_argument('-p', '--power', action='store_true',
                    help='get latest power of gpu')
parser.add_argument('-t', '--temp', action='store_true',
                    help='get latest temperature of gpu')


class PrintTable:
    _t = Texttable()

    def __init__(self, headers):
        self.headers = headers
        self._t.add_row(headers)

    def add_row(self, row):
        self._t.add_row(row)

    def print(self):
        print(self._t.draw())


def arg():
    parsed = parser.parse_args()
    if parsed.list:
        get_devices()
        return
    if parsed.freq:
        if parsed.device:
            get_frequency(parsed.device, parsed.immed)
        else:
            print("Param error: device_id need be specified")
        return
    if parsed.power:
        if parsed.device:
            get_power(parsed.device, parsed.immed)
        else:
            print("Param error: device_id need be specified")
        return
    if parsed.temp:
        if parsed.device:
            get_temp(parsed.device, parsed.immed)
        else:
            print("Param error: device_id need be specified")
        return

    parser.print_help()


def device_info_to_str(props):
    info_list = []
    order_list = [
        "Device Type", "Device Name", "Brand Name", "Serial Number", "Vendor Name", "UUID", "BDF Address", None,
        "Driver Version", "Firmware Name", "Firmware Version", None,
        "Memory Physical Size", None,
        "Core Clock Rate", "available frequency", None,
        "Number of Slices", "Number of Sub Slices Per Sub Slice", "Number of EUs Per Sub Slice"
    ]
    for k in order_list:
        if k is None:
            info_list.append("")
        elif k in props.keys():
            info_list.append(k+": "+props[k])
    return "\n".join(info_list)


def get_devices():
    res = requests.get(host+"/dgm/v1/devices")

    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return

    data = res.json()

    t = PrintTable(["GPU ID", "Device Information"])

    for gpu in data:

        props = dict()

        for p in gpu['properties']:
            for k, v in p.items():
                props[k] = v

        t.add_row([gpu['device_id'], device_info_to_str(props)])

    t.print()


def get_temp(deviceId, realtime=False):
    data = get_measurement(deviceId, "temp", realtime)
    temp_dict = data['temp']

    t = PrintTable(["Temp", "Value(°C)"])

    if realtime:
        t.add_row(["current",temp_dict["current"]])
    else:
        ks = temp_dict.keys()
        vs = [str(i) for i in temp_dict.values()]
        t.add_row(["\n".join(ks), "\n".join(vs)])

    t.print()


def get_power(deviceId, realtime=False):
    data = get_measurement(deviceId, "power", realtime)
    power_dict = data['power']

    t = PrintTable(["Power", "Value(W)"])

    if realtime:
        t.add_row(["current",power_dict["current"]])
    else:
        ks = power_dict.keys()
        vs = [str(i) for i in power_dict.values()]
        t.add_row(["\n".join(ks), "\n".join(vs)])

    t.print()


def get_frequency(deviceId, realtime=False):
    data = get_measurement(deviceId, "frequency", realtime)
    freq_dict = data['frequency']
    
    t = PrintTable(["Frequency", "Value(MHz)"])

    if realtime:
        t.add_row(["current",freq_dict["current"]])
    else:
        ks = freq_dict.keys()
        vs = [str(i) for i in freq_dict.values()]
        t.add_row(["\n".join(ks), "\n".join(vs)])

    t.print()


def get_measurement(deviceId, measurementType, realtime=False):
    url = "/dgm/v1/devices/{}/measurements".format(deviceId)
    params = {"type": measurementType}
    if realtime:
        params['realtime'] = True
    res = requests.get(host + url, params=params)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    return res.json()


if __name__ == "__main__":
    arg()
