#!/usr/bin/python3
import argparse

import json

import pprint
import requests
from requests import ConnectionError
import time

from texttable import Texttable

import os

os.environ['NO_PROXY'] = 'localhost'

# host = "http://localhost:5000"
host = "http://localhost:30000"

parser = argparse.ArgumentParser()
parser.add_argument('-v', '--version', action='store_true',
                    help='Display version information and exit')

subparsers = parser.add_subparsers(
    title="Subcommand options", dest="subcommand")

# discovery subcommand parser
discovery_parser = subparsers.add_parser(
    "discovery", help="Discover devices on the system")

discovery_parser.add_argument('-d', '--device', metavar="<deviceId>", dest="deviceId",
                              help='The device id to query, will show more detailed info')

# group subcommand parser
group_parser = subparsers.add_parser("group", help="Group management")

group_parser.add_argument('-c', '--create', metavar="<groupName>", dest="groupNameToCreate",
                          help='Create a group')
group_parser.add_argument('-r', '--remove', dest="remove", action='store_true',
                          help='Remove a group')
group_parser.add_argument('-l', '--list', dest="list", action='store_true',
                          help='Display info for a group or all groups')
group_parser.add_argument('-g', '--group', metavar="<groupId>", dest="groupId", type=int,
                          help='The id of the group to manipulate')
group_parser.add_argument('-a', '--add', metavar="<deviceIds>", dest="deviceIdToAdd", nargs='+', type=int,
                          help='Add device to a group')
group_parser.add_argument('-d', '--delete', metavar="<deviceIds>", dest="deviceIdToDelete", nargs='+', type=int,
                          help='Delete device from a group')

# agentset subcommand parser
agentset_parser = subparsers.add_parser("agentset", help="XPUM agent settings")
agentset_parser.add_argument('-l', '--list', action='store_true',
                             help='Display all agent settings')
agentset_parser.add_argument('-t', '--time', metavar='<interval>', dest="interval",type=int,
                             help='Set the time interval (in milliseconds) by which xpum daemon tries to get data. Options are 100,200,500,1000.')

# statistics subcommand parser
stats_parser = subparsers.add_parser("stats", help="Display device statistics")
stats_parser.add_argument('-d', '--device', metavar="<deviceId>", dest="deviceId", type=int,
                          help='The device id to query')
stats_parser.add_argument('-g', '--group', metavar="<groupId>", dest="groupId", type=int,
                          help='The group id to query')

# health subcommand parser
health_parser = subparsers.add_parser("health", help="Display health status of GPUs")
health_parser.add_argument('-l', '--list', action='store_true',
                              help='Display health info for all devices')
health_parser.add_argument('-d', '--device', metavar="<deviceId>", dest="deviceId", type=int,
                          help='The device id to query')
health_parser.add_argument('-g', '--group', metavar="<groupId>", dest="groupId", type=int,
                          help='The group id to query')
health_parser.add_argument('-t', '--thermal', metavar="<thermalThreshold>", dest="thermalThreshold", type=int,
                          help='Set temperature threshold for device')
health_parser.add_argument('-p', '--power', metavar="<powerThreshold>", dest="powerThreshold", type=int,
                          help='Set power threshold for device')

# diagnostics subcommand parser
diag_parser = subparsers.add_parser("diag", help="System validation/diagnostic")
diag_parser.add_argument('-d', '--device', metavar="<deviceId>", dest="deviceId", type=int,
                          help='The device id to query')
diag_parser.add_argument('-g', '--group', metavar="<groupId>", dest="groupId", type=int,
                          help='The group id to query')
diag_parser.add_argument('-l', '--level', metavar="<level>", dest="level", type=int,
                          help='The diagnostics level to run')

# fwflash subcommand parser
fwflash_parser = subparsers.add_parser("fwflash", help="Flash device firmware")
fwflash_parser.add_argument('-d', '--device', metavar="<deviceId>", dest="deviceId", type=int, required=True,
                          help='The device id to query')
fwflash_parser.add_argument('-t', '--type', metavar="<firmwareName>", dest="firmwareName", required=True,
                          help='Firmware name to flash')
fwflash_parser.add_argument('-f', '--file', metavar="<imagePath>", dest="imagePath", required=True,
                          help='The file path in the server, used to flash firmware, should be located in /usr/bin')

# reset subcommand parser
reset_parser = subparsers.add_parser("reset", help="Reset device")
reset_parser.add_argument('-d', '--device', metavar="<deviceId>", dest="deviceId", type=int,
                          help='reset device')

# config subcommand parser
config_parser = subparsers.add_parser("config", help="used to configure settings for devices.")
config_parser.add_argument('-d', '--device', metavar="<deviceId>", dest="deviceId", type=int,
                          help='The device id to query or change')
config_parser.add_argument('-t', '--tile', metavar="<deviceTileId>", dest="deviceTileId", type=int,
                          help='The device tile id to query or change')
#config_parser.add_argument('-l', '--list', action='store_true',
#                          help='get all config')
config_parser.add_argument('--scheduler', metavar="<scheduler mode>", dest="SchedulerValue", type=str,
                          help='config scheduler：[timeout,timeout value],[timeslice,interval time,yield time],[exclusive]. Ex: --scheduler timeout,50000  --scheduler timeslice,10000,50000  --scheduler exclusive')
config_parser.add_argument('--standby', metavar="<standby mode>", dest="StandbyValue", type=str,
                          help='config standby mode: [default], [never]. Ex: --standby default  ,--standby never')
config_parser.add_argument('--powerlimit', metavar="<power limit>", dest="PowerLimitValue", type=str,
                          help='config power limit: [power value,average window]. Ex: --powerlimit 330,120')
config_parser.add_argument('--frequencyrange', metavar="<frequency range>", dest="FrequencyRangeValue", type=str,
                          help='config frequency range: [min frequency,max frequency]. Ex: --frequencyrange 400,1200')
config_parser.add_argument('--burstlimit', metavar="<burst limit>", dest="BurstLimitValue", type=str,
                          help='config burst limit: [power value, enable/disable] Ex: --burstlimit 800,true')

# telemetry subcommand parser
metricsTypeTranslationMap = {
    "XPUM_STATS_GPU_UTILIZATION": "GPU Utilization (%)",
    "XPUM_STATS_OCCUPATION": "Occupation (%)",
    "XPUM_STATS_ISSUE_EFFICIENCY": "Issue Efficiency (%)",
    "XPUM_STATS_EXECUTION_EFFICIENCY": "Execution Efficiency (%)",
    "XPUM_STATS_NON_OCCUPATION": "Non-Occupation (%)",
    "XPUM_STATS_POWER": "GPU Power (milliwatt)",
    "XPUM_STATS_ENERGY": "Energy Counter (millijoule)",
    "XPUM_STATS_GPU_FREQUENCY": "GPU Frequency (MHz)",
    "XPUM_STATS_GPU_TEMEPERATURE": "GPU Temperature (°C)",
    "XPUM_STATS_MEMORY_USED": "Memory Used (MiB)",
    "XPUM_STATS_MEMORY_UTILIZATION": "Memory Utilization (%)",
    "XPUM_STATS_MEMORY_BANDWIDTH": "Memory Bandwidth",
    "XPUM_STATS_MEMORY_READ": "Memory Read",
    "XPUM_STATS_MEMORY_WRITE": "Memory Write",
    "XPUM_STATS_ENGINE_GROUP_COMPUTE_ALL_UTILIZATION": "Engine Group Compute_all Utilization",
    "XPUM_STATS_ENGINE_GROUP_MEDIA_ALL_UTILIZATION": "Engine Group Media All Utilization",
    "XPUM_STATS_ENGINE_GROUP_COPY_ALL_UTILIZATION": "Engine Group Copy All Utilization",
    "XPUM_STATS_ENGINE_GROUP_RENDER_ALL_UTILIZATION": "Engine Group Render All Utilization",
    "XPUM_STATS_ENGINE_GROUP_3D_ALL_UTILIZATION": "Engine Group 3d All Utilization",
    "XPUM_STATS_PCIRX": "PCIRX",
    "XPUM_STATS_PCITX": "PCITX",
    "XPUM_STATS_RAS_ERROR_CAT_RESET": "Reset",
    "XPUM_STATS_RAS_ERROR_CAT_PROGRAMMING_ERRORS": "Programming Errors",
    "XPUM_STATS_RAS_ERROR_CAT_DRIVER_ERRORS": "Driver Errors",
    "XPUM_STATS_RAS_ERROR_CAT_CACHE_ERRORS_CORRECTABLE": "Cache Errors Correctable",
    "XPUM_STATS_RAS_ERROR_CAT_CACHE_ERRORS_UNCORRECTABLE": "Cache Errors Uncorrectable",
    "XPUM_STATS_RAS_ERROR_CAT_DISPLAY_ERRORS_CORRECTABLE": "Display Errors Correctable",
    "XPUM_STATS_RAS_ERROR_CAT_DISPLAY_ERRORS_UNCORRECTABLE": "Display Errors Uncorrectable"
}

telemetry_parser = subparsers.add_parser(
    "telemetry", help="used to collect and dump metrics raw data", formatter_class=argparse.RawTextHelpFormatter)
telemetry_parser.add_argument('-d', '--device', metavar="<deviceId>",
                              dest="deviceId", type=int, help='The device id to query or change')
telemetry_support_metrics = [
    "XPUM_STATS_GPU_UTILIZATION",
    "XPUM_STATS_POWER",
    "XPUM_STATS_ENERGY",
    "XPUM_STATS_GPU_FREQUENCY",
    "XPUM_STATS_GPU_TEMEPERATURE"
]
telemetry_start_help_lines = ["    {}. {}".format(i, metricsTypeTranslationMap.get(
    m, m)) for i, m in zip(range(len(telemetry_support_metrics)), telemetry_support_metrics)]

telemetry_start_help = "\n".join(
    ["Metrics type to collect raw data, options:"]+telemetry_start_help_lines)
telemetry_start_help = telemetry_start_help.replace("%","%%")
telemetry_parser.add_argument('-m', '--metrics', metavar="<metricsId>",
                              dest="metricsIds", nargs='+', type=int, help=telemetry_start_help)
telemetry_parser.add_argument('--start', action='store_true', help="""\
Start metrics raw data collect task, will return a task id.
    Notice XPU Manager supports at most 16 tasks coexist.
    When limit reached, start a new task will cause the oldest task automatically terminated and data removed.""")
telemetry_parser.add_argument('--stop', metavar="<taskId>", dest="stopTaskId", type=int, help="""\
Stop corresponding collect task. 
    Notice a task collect 5000 time frames at most. 
    When limit reached, the task will be terminated automatically.""")
telemetry_parser.add_argument('--dump', metavar="<taskId>", dest="dumpTaskId",
                              type=int, help="""Dump raw datas that collected in <taskId>, in csv format""")

# topology subcommand parser
topo_parser = subparsers.add_parser("topology", help="topology management")

topo_parser.add_argument('-d', '--device', metavar="<deviceId>", dest="deviceId", type=int,
                          help='The device id to query')

class PrintTable:
    _t = Texttable()

    def __init__(self, *args):
        if len(args)>=1:
            self.headers = args[0]
            self._t.add_row(args[0])

    def add_row(self, row):
        self._t.add_row(row)

    def add_rows(self, rows):
        for row in rows:
            self._t.add_row(row)

    def print(self):
        print(self._t.draw())


def arg():
    parsed = parser.parse_args()
    # print(parsed)
    if not parsed.subcommand:
        if parsed.version:
            display_version()
            return
    elif parsed.subcommand == "discovery":
        if parsed.deviceId:
            display_device_detail(parsed.deviceId)
            return
        display_devices()
        return
    elif parsed.subcommand == "group":
        if parsed.groupNameToCreate:
            groupName = parsed.groupNameToCreate
            create_group(groupName)
            return
        if parsed.remove:
            if not parsed.groupId:
                print("Wrong argument: <groupId> should be specified by -g option")
                return
            groupId = parsed.groupId
            remove_group(groupId)
            return
        if parsed.list:
            if parsed.groupId:
                groupId = parsed.groupId
                list_single_group_info(groupId)
                return
            list_all_group_info()
            return
        if parsed.deviceIdToAdd:
            if parsed.groupId is None:
                print("Wrong argument: <groupId> should be specified by -g option")
                return
            deviceIds = parsed.deviceIdToAdd
            groupId = parsed.groupId
            add_device_to_group(deviceIds, groupId)
            return
        if parsed.deviceIdToDelete:
            if not parsed.groupId:
                print("Wrong argument: <groupId> should be specified by -g option")
                return
            deviceIds = parsed.deviceIdToDelete
            groupId = parsed.groupId
            remove_device_from_group(deviceIds, groupId)
            return
    elif parsed.subcommand == "agentset":
        if parsed.list:
            display_all_agent_settings()
            return
        elif parsed.interval is not None:
            set_agent_settings(interval=parsed.interval)
            return
        else:
            agentset_parser.print_help()
            return
    elif parsed.subcommand == "stats":
        if parsed.deviceId is not None:
            display_device_stats(parsed.deviceId)
            return
        elif parsed.groupId is not None:
            display_group_stats(parsed.groupId)
            return
        else:
            display_all_device_stats()
            return
    elif parsed.subcommand == "health":
        if parsed.deviceId is not None:
            if parsed.thermalThreshold is not None:
                set_device_health_config(parsed.deviceId, "temperature", parsed.thermalThreshold)
                return
            elif parsed.powerThreshold is not None:
                set_device_health_config(parsed.deviceId, "power", parsed.powerThreshold)
                return
            else:
                display_device_health(parsed.deviceId)
                return
        elif parsed.groupId is not None:
            if parsed.thermalThreshold is not None:
                set_group_health_config(parsed.groupId, "temperature", parsed.thermalThreshold)
                return
            elif parsed.powerThreshold is not None:
                set_group_health_config(parsed.groupId, "power", parsed.powerThreshold)
                return
            else:
                display_group_health(parsed.groupId)
                return
        else:
            health_parser.print_help()
            return
    elif parsed.subcommand == "diag":
        if parsed.deviceId is not None and parsed.level is not None:
            run_device_diagnostics(parsed.deviceId, parsed.level)
            return
        elif parsed.groupId is not None and parsed.level is not None:
            run_group_diagnostics(parsed.groupId, parsed.level)
            return
        else:
            diag_parser.print_help()
            return
    elif parsed.subcommand == "fwflash":
        deviceId = parsed.deviceId
        firmwareName = parsed.firmwareName
        imagePath = parsed.imagePath
        flash_firmware(deviceId, firmwareName, imagePath)
        return
    elif parsed.subcommand == "reset":
        if parsed.deviceId is not None:
            reset_device(parsed.deviceId)
            return
        else:
            reset_parser.print_help()
            return
    elif parsed.subcommand == "config":
        if parsed.SchedulerValue is not None and parsed.deviceTileId is not None:
            set_device_scheduler(parsed.deviceId, parsed.deviceTileId, parsed.SchedulerValue)
            return
        elif parsed.FrequencyRangeValue is not None and parsed.deviceTileId is not None:
            set_device_frequencyRange(parsed.deviceId, parsed.deviceTileId, parsed.FrequencyRangeValue)
            return
        elif parsed.PowerLimitValue is not None and parsed.deviceTileId is not None:
            set_device_powerlimit(parsed.deviceId, parsed.deviceTileId, parsed.PowerLimitValue)
            return
        elif parsed.StandbyValue is not None and parsed.deviceTileId is not None:
            set_device_standby(parsed.deviceId, parsed.deviceTileId, parsed.StandbyValue)
            return
        elif parsed.BurstLimitValue is not None and parsed.deviceTileId is not None:
            set_device_burstlimit(parsed.deviceId, parsed.deviceTileId, parsed.BurstLimitValue)
            return
        elif parsed.deviceId is not None:
            display_device_all_config(parsed.deviceId, parsed.deviceTileId)
            return
        else:
            config_parser.print_help()
            return
    elif parsed.subcommand == "telemetry":
        if parsed.start:
            if parsed.deviceId is None or parsed.metricsIds is None:
                print("Wrong arguments")
            start_collect_metrics_raw_data_by_device(
                    parsed.deviceId, parsed.metricsIds)
        elif parsed.stopTaskId is not None:
            stop_collect_metrics_raw_data_task(parsed.stopTaskId)
        elif parsed.dumpTaskId is not None:
            dump_metrics_raw_data(parsed.dumpTaskId)
        else:
            telemetry_parser.print_help()
        return
    elif parsed.subcommand == "topology":
        if parsed.deviceId is not None:
            get_device_topology(parsed.deviceId)
            return
        else:
            topo_parser.print_help()
            return

    parser.print_help()

def set_agent_settings(**kwargs):
    reqData = {}
    if "interval" in kwargs:
        reqData["XPUM_AGENT_CONFIG_SAMPLE_INTERVAL"] = str(kwargs["interval"])
    else:
        print("Fail: agent set key not supported")
    res = requests.post(host+"/rest/v1/globalSettings",json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    display_all_agent_settings()

def display_all_agent_settings():
    # print("Display all agent settings")
    res = requests.get(host+"/rest/v1/globalSettings")
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        # print("Fail to get agent settings")
        return
    # print(res)
    data = res.json()
    t = PrintTable(["Name","Value"])
    rows = []
    for k in data:
        if k == "XPUM_AGENT_CONFIG_SAMPLE_INTERVAL":
            rows.append(["Sampling Interval (ms)",data[k]])
    t.add_rows(rows)
    t.print()
    

def display_all_device_stats():
    res = requests.get(host+"/rest/v1/devices")

    if res.status_code != 200:
        # print("Error occurs:"+res.content.decode())
        print("Fail to query data")
        return

    data = res.json()

    gpus = [d for d in data if d['DeviceType'] == 0]

    if not gpus:
        return
    print("Device Type: GPU")
    t = PrintTable()
    for d in gpus:
        res = requests.get(host+"/rest/v1/devices/{}/stats".format(d["DeviceId"]))
        if res.status_code != 200:
            print("Error occurs:"+res.content.decode())
            return
        data = res.json()
        rows = get_stats_rows(data)
        t.add_rows(rows)
    t.print()
        

def display_device_stats(deviceId):
    # print("stats for device {}".format(deviceId))
    res = requests.get(host+"/rest/v1/devices/{}/stats".format(deviceId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    print("Device Type: GPU")
    # print(data)
    rows = get_stats_rows(data)
    t = PrintTable()
    t.add_rows(rows)
    t.print()

def get_stats_data_by_metrics_type(metricsType, dataList):
    for stats in dataList:
        if stats['metricsType'] == metricsType:
            return stats
    return None


def stats_counter_formater(
        metricsType,
        counter_row_keys,
        counter_row_values,
        deviceLevelDataList,
        tileLevelDataLists,
        keyName,
        factor=1,
        precision=3):
    stats = get_stats_data_by_metrics_type(metricsType, deviceLevelDataList)
    counter_row_keys.append(keyName)
    value = "{}".format(round(stats['value'] * factor,precision)) if stats else ""
    counter_row_values.append(value)
    if tileLevelDataLists:
        for tile in tileLevelDataLists:
            tileId = tile["tileId"]
            tileStatsDataList = tile["dataList"]
            stats = get_stats_data_by_metrics_type(
                metricsType, tileStatsDataList)
            if stats:
                counter_row_keys.append("\n")
                counter_row_values.append(
                    "Tile {}: {}".format(tileId, round(stats["value"]*factor,precision)))


def stats_non_counter_formater(
        metricsType,
        rows,
        deviceLevelDataList,
        tileLevelDataLists,
        keyName,
        factor=1,
        precision=3):
    stats = get_stats_data_by_metrics_type(metricsType, deviceLevelDataList)
    values = []
    if stats:
        v = "current: {}\navg: {}\nmin: {}\nmax: {}".format(
            round(stats["value"]*factor, precision),
            round(stats["avg"]*factor, precision),
            round(stats["min"]*factor, precision),
            round(stats["max"]*factor, precision)
        )
        values.append(v)
    if tileLevelDataLists:
        for tile in tileLevelDataLists:
            tileId = tile["tileId"]
            tileStatsDataList = tile["dataList"]
            stats = get_stats_data_by_metrics_type(
                metricsType, tileStatsDataList)
            if stats:
                v = "Tile {}:\n\tcurrent: {}\n\tavg: {}\n\tmin: {}\n\tmax: {}".format(
                    tileId,
                    round(stats["value"]*factor, precision),
                    round(stats["avg"]*factor, precision),
                    round(stats["min"]*factor, precision),
                    round(stats["max"]*factor, precision)
                )
                # values.append("")
                values.append(v)
    rows.append([keyName, "\n\n".join(values)])

def get_stats_rows(data):
    header_row = ["Device Id", data['DeviceId']]
    rows = []
    counter_row_keys = ["Start Time","End Time"]
    counter_row_values = [data['Begin'],data['End']]
    deviceLevelDataList = data["DeviceLevel"]
    tileLevelDataLists =[]
    if "TileLevel" in  data:
        tileLevelDataLists = data["TileLevel"]

    # Energy Consumed (J)
    stats_counter_formater(
        "XPUM_STATS_ENERGY",
        counter_row_keys,
        counter_row_values,
        deviceLevelDataList,
        tileLevelDataLists,
        "Energy Consumed (J)",
        factor=1/1e3)
    
    # Reset
    stats_counter_formater(
        "XPUM_STATS_RAS_ERROR_CAT_RESET",
        counter_row_keys,
        counter_row_values,
        deviceLevelDataList,
        tileLevelDataLists,
        "Reset")
    
    # Programming Errors
    stats_counter_formater(
        "XPUM_STATS_RAS_ERROR_CAT_PROGRAMMING_ERRORS",
        counter_row_keys,
        counter_row_values,
        deviceLevelDataList,
        tileLevelDataLists,
        "Programming Errors")
    
    # Driver Errors
    stats_counter_formater(
        "XPUM_STATS_RAS_ERROR_CAT_DRIVER_ERRORS",
        counter_row_keys,
        counter_row_values,
        deviceLevelDataList,
        tileLevelDataLists,
        "Driver Errors")

    # Cache Errors Correctable
    stats_counter_formater(
        "XPUM_STATS_RAS_ERROR_CAT_CACHE_ERRORS_CORRECTABLE",
        counter_row_keys,
        counter_row_values,
        deviceLevelDataList,
        tileLevelDataLists,
        "Cache Errors Correctable")

    # Cache Errors Uncorrectable
    stats_counter_formater(
        "XPUM_STATS_RAS_ERROR_CAT_CACHE_ERRORS_UNCORRECTABLE",
        counter_row_keys,
        counter_row_values,
        deviceLevelDataList,
        tileLevelDataLists,
        "Cache Errors Uncorrectable")

    # Display Errors Correctable
    stats_counter_formater(
        "XPUM_STATS_RAS_ERROR_CAT_DISPLAY_ERRORS_CORRECTABLE",
        counter_row_keys,
        counter_row_values,
        deviceLevelDataList,
        tileLevelDataLists,
        "Display Errors Correctable")

    # Display Errors Uncorrectable
    stats_counter_formater(
        "XPUM_STATS_RAS_ERROR_CAT_DISPLAY_ERRORS_UNCORRECTABLE",
        counter_row_keys,
        counter_row_values,
        deviceLevelDataList,
        tileLevelDataLists,
        "Display Errors Uncorrectable")

    # Occupation (%)
    stats_non_counter_formater(
        "XPUM_STATS_OCCUPATION",
        rows,
        deviceLevelDataList,
        tileLevelDataLists,
        "Occupation (%)")
    
    # Issue Efficiency (%)
    stats_non_counter_formater(
        "XPUM_STATS_ISSUE_EFFICIENCY",
        rows,
        deviceLevelDataList,
        tileLevelDataLists,
        "Issue Efficiency (%)")
    
    # Execution Efficiency (%)
    stats_non_counter_formater(
        "XPUM_STATS_EXECUTION_EFFICIENCY",
        rows,
        deviceLevelDataList,
        tileLevelDataLists,
        "Execution Efficiency (%)")
    
    # Non-Occupation (%)
    stats_non_counter_formater(
        "XPUM_STATS_NON_OCCUPATION",
        rows,
        deviceLevelDataList,
        tileLevelDataLists,
        "Non-Occupation (%)")
    
    # GPU Utilization (%)
    stats_non_counter_formater(
        "XPUM_STATS_GPU_UTILIZATION",
        rows,
        deviceLevelDataList,
        tileLevelDataLists,
        "GPU Utilization (%)")

    # GPU Power (W)
    stats_non_counter_formater(
        "XPUM_STATS_POWER",
        rows,
        deviceLevelDataList,
        tileLevelDataLists,
        "GPU Power (W)")

    # GPU Frequency (MHz)
    stats_non_counter_formater(
        "XPUM_STATS_GPU_FREQUENCY",
        rows,
        deviceLevelDataList,
        tileLevelDataLists,
        "GPU Frequency (MHz)")

    # GPU Temperature (°C)
    stats_non_counter_formater(
        "XPUM_STATS_GPU_TEMEPERATURE",
        rows,
        deviceLevelDataList,
        tileLevelDataLists,
        "GPU Temperature (°C)")

    # Memory Used (MiB)
    stats_non_counter_formater(
        "XPUM_STATS_MEMORY_USED",
        rows,
        deviceLevelDataList,
        tileLevelDataLists,
        "Memory Used (MiB)",
        1/(2**20),2)
        
    counter_row = ["\n".join(counter_row_keys),"\n".join(counter_row_values)]
    return [header_row,counter_row,*rows]

def display_group_stats(groupId):
    # print("stats for group {}".format(groupId))
    res = requests.get(host+"/rest/v1/groups/{}/stats".format(groupId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    print("Device Type: GPU")
    t = PrintTable()
    for d in data["Datas"]:
        rows = get_stats_rows(d)
        t.add_rows(rows)
    t.print()

def remove_device_from_group(deviceIds, groupId):
    # print("remove device{} from group {}".format(deviceId,groupId))
    reqData = {
        "DeviceIdToRemove": deviceIds
    }
    res = requests.post(host+"/rest/v1/groups/{}".format(groupId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    print("Successfully remove device {} from group {}".format(deviceIds, groupId))
    data = res.json()
    t = PrintTable(["Group Id", "Group Properties"])
    value = "Group Name: \"{}\"\nDevice Ids: {}".format(
        data['GroupName'],
        data['DeviceIds']
    )
    t.add_row([data['GroupId'], value])
    t.print()

def add_device_to_group(deviceIds, groupId):
    # print("add device{} to group {}".format(deviceId,groupId))
    reqData = {
        "DeviceIdToAdd": deviceIds
    }
    res = requests.post(host+"/rest/v1/groups/{}".format(groupId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    print("Successfully add device {} to group {}".format(deviceIds, groupId))
    data = res.json()
    t = PrintTable(["Group Id", "Group Properties"])
    value = "Group Name: \"{}\"\nDevice Ids: {}".format(
        data['GroupName'],
        data['DeviceIds']
    )
    t.add_row([data['GroupId'], value])
    t.print()


def list_all_group_info():
    # print("Display info for all groups")
    res = requests.get(host+"/rest/v1/groups")
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    groupIds = res.json()
    rows = []
    for groupId in groupIds:
        res = requests.get(host+"/rest/v1/groups/{}".format(groupId))
        data = res.json()
        value = "Group Name: \"{}\"\nDevice Ids: {}".format(
            data['GroupName'],
            data['DeviceIds']
        )
        rows.append([data['GroupId'], value])
    t = PrintTable(["Group Id", "Group Properties"])
    t.add_rows(rows)
    t.print()
        

def list_single_group_info(groupId):
    # print("Display info for group "+groupId)
    res = requests.get(host+"/rest/v1/groups/{}".format(groupId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    # print(data)
    t = PrintTable(["Group Id", "Group Properties"])
    value = "Group Name: \"{}\"\nDevice Ids: {}".format(
        data['GroupName'],
        data['DeviceIds']
    )
    t.add_row([data['GroupId'], value])
    t.print()

def remove_group(groupId):
    # print("Remove group "+groupId)
    res = requests.delete(host+"/rest/v1/groups/{}".format(groupId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    print("Destroy Group Successfully!")

def create_group(groupName):
    # print("Create group "+groupName)
    reqData = {
        "GroupName":groupName
    }
    res = requests.post(host+"/rest/v1/groups", json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    # print(data)
    t = PrintTable(["Group Id", "Group Properties"])
    value = "Group Name: \"{}\"\nDevice Ids: {}".format(
        data['GroupName'],
        data['DeviceIds']
    )
    t.add_row([data['GroupId'], value])
    t.print()

def display_version():
    res = requests.get(host+"/rest/v1/version")
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    template = '''CLI:
    Version: {cli_version}
    Build Id: 10

Service:
    Version: {service_version}
    Build Id: 10
    Level Zero Version: {level_zero_version}
    '''
    cli_version = service_version = data['Version']
    level_zero_version = data['LevelZeroVersion']
    output = template.format(
        cli_version=cli_version,
        service_version=service_version,
        level_zero_version=level_zero_version
    )
    print(output)


def device_info_to_str(props):
    rows = []
    rows.append("Device Type: {}".format(props["DeviceType"]))
    rows.append("Device Name: {}".format(props["DeviceName"]))
    rows.append("")
    rows.append("Vendor Name: {}".format(props["VendorName"]))
    rows.append("UUID: {}".format(props["UUID"]))
    rows.append("PCI BDF Address: {}".format(props["PCIBdfAddress"]))
    rows.append("PCI Slot: {}".format(props["PCISlot"]))
    rows.append("")
    rows.append("Driver Version: {}".format(props["DriverVersion"]))
    if "FirmwareName" in props:
        rows.append("Firmware Name: {}".format(props["FirmwareName"]))
    if "FirmwareVersion" in props:
        rows.append("Firmware Version: {}".format(props["FirmwareVersion"]))
    rows.append("")
    # rows.append("Number of Sub Devices: {}".format(
    #     props["NumberOfSubDevices"]))
    rows.append("Serial Number: {}".format(props["SerialNumber"]))
    rows.append("Core Clock Rate: {}".format(props["CoreClockRate"]))
    rows.append("Memory Physical Size: {}".format(props["MemoryPhysicalSize"]))
    rows.append("Memory Free Size: {}".format(props["MemoryFreeSize"]))
    rows.append("Max Mem Alloc Size: {}".format(props["MaxMemAllocSize"]))
    rows.append("Max Hardware Contexts: {}".format(
        props["MaxHardwareContexts"]))
    rows.append("Max Command Queue Priority: {}".format(
        props["MaxCommandQueuePriority"]))
    rows.append("")
    rows.append("Number of Slices: {}".format(props["NumberOfSlices"]))
    rows.append("Number of Sub Slices Per Slice: {}".format(
        props["NumberOfSubSlicesPerSubSlice"]))
    rows.append("Number of EUs Per Sub Slice: {}".format(
        props["NumberOfEusPerSubSlice"]))
    rows.append("Number of Threads Per EU: {}".format(
        props["NumberOfThreadsPerEu"]))
    rows.append("Physical EU SIMD Width: {}".format(
        props["PhysicalEuSimdWidth"]))
    # rows.append("Timer Resolution: {}".format(props["TimerResolution"]))
    # rows.append("Timestamp Valid Bits: {}".format(props["TimestampValidBits"]))
    # rows.append("PCI Vendor Id: {}".format(props["PCIVendorId"]))
    # rows.append("Kernel Timestamp Valid Bits: {}".format(
    #     props["KernelTimestampValidBits"]))
    # rows.append("Flags: {}".format(props["Flags"]))
    
    rows.append("")
    rows.append("PCIe Generation: {}".format(props["PCIeGen"]))
    rows.append("PCIe Max Link Width: {}".format(props["PCIeMaxLinkWidth"]))
    rows.append("Number of Memory Channels: {}".format(props["NumberOfMemoryChannel"]))
    rows.append("Memory Bus Width: {}".format(props["MemoryBusWidth"]))

    return "\n".join(rows)


def display_devices():
    res = requests.get(host+"/rest/v1/devices")

    if res.status_code != 200:
        # print("Error occurs:"+res.content.decode())
        print("Fail to query data")
        return

    data = res.json()

    gpus = [d for d in data if d['DeviceType'] == 0]

    if gpus:
        print("Device Type: GPU")
        t = PrintTable(["Device ID", "Device Information"])
        for gpu in gpus:
            rows = []
            rows.append("Device Name: {}".format(gpu["DeviceName"]))
            rows.append("Vendor Name: {}".format(gpu["VendorName"]))
            rows.append("UUID: {}".format(gpu["UUID"]))
            rows.append("PCI BDF Address: {}".format(gpu["PCIBDFAddress"]))
            "\n".join(rows)
            t.add_row([gpu['DeviceId'], "\n".join(rows)])
        t.print()


def display_device_detail(deviceId):
    res = requests.get(host+"/rest/v1/devices/{}".format(deviceId))

    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return

    data = res.json()

    t = PrintTable(["Device ID", "Device Information"])

    t.add_row([data['DeviceId'], device_info_to_str(data)])

    t.print()

def get_diag_rows(data):
    header_row = ["Device Id", data['DeviceId']]
    base_row_keys = ["Level", "Finished", "Count", "Message"]
    base_row_values = [str(data['Level']), str(data['Finished']), str(data['Count']), data['Message']]
    base_row = ["\n".join(base_row_keys),"\n".join(base_row_values)]
    rows = []
    for component in data['ComponentList']:
        v = "Finished: {}\nResult: {}\nMessage: {}".format(
                component["Finished"],
                component["Result"],
                component["Message"]
        )
        rows.append([component["Type"],v])
    return [header_row, base_row, *rows]

def run_device_diagnostics(deviceId, level):
    reqData = {
        "DiagnosticsLevel":level
    }
    res = requests.post(host+"/rest/v1/devices/{}/diagnostics".format(deviceId), json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    while True:
        res = requests.get(host+"/rest/v1/devices/{}/diagnostics".format(deviceId))
        if res.status_code != 200:
            print("Error occurs:"+res.content.decode())
            return
        data = res.json()
        if data["Finished"] == True:
            break
        time.sleep(3)
    print("Device Type: GPU")
    rows = get_diag_rows(data)
    t = PrintTable()
    t.add_rows(rows)
    t.print()

def run_group_diagnostics(groupId, level):
    reqData = {
        "DiagnosticsLevel":level
    }
    res = requests.post(host+"/rest/v1/groups/{}/diagnostics".format(groupId), json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    while True:
        res = requests.get(host+"/rest/v1/groups/{}/diagnostics".format(groupId))
        if res.status_code != 200:
            print("Error occurs:"+res.content.decode())
            return
        data = res.json()
        allFinished = True
        for devices in data["Diagnostics"]:
            if devices["Finished"] == False:
                allFinished = False
                break
        if allFinished == True:
            break
        time.sleep(3)
    print("Device Type: GPU")
    t = PrintTable()
    for d in data["Diagnostics"]:
        rows = get_diag_rows(d)
        t.add_rows(rows)
    t.print()

def get_health_rows(data):
    header_row = ["Device Id", data['DeviceId']]
    rows = []
    if "Temperature" in data.keys():
        v = "Status: {}\nDescription: {}\nThreshold: {}".format(
                data["Temperature"]["Status"],
                data["Temperature"]["Description"],
                data["Temperature"]["Threshold"]
        )
        rows.append(["Temperature",v])
    if "Power" in data.keys():
        v = "Status: {}\nDescription: {}\nThreshold: {}".format(
                data["Power"]["Status"],
                data["Power"]["Description"],
                data["Power"]["Threshold"]
        )
        rows.append(["Power",v])
    if "Memory" in data.keys():
        v = "Status: {}\nDescription: {}".format(
                data["Memory"]["Status"],
                data["Memory"]["Description"]
        )
        rows.append(["Memory",v])
    if "Fabricport" in data.keys():
        v = "Status: {}\nDescription: {}".format(
                data["Fabricport"]["Status"],
                data["Fabricport"]["Description"]
        )
        rows.append(["Fabricport",v])
    return [header_row, *rows]

def display_device_health(deviceId):
    # print("health for device {}".format(deviceId))
    res = requests.get(host+"/rest/v1/devices/{}/health".format(deviceId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    print("Device Type: GPU")
    rows = get_health_rows(data)
    t = PrintTable()
    t.add_rows(rows)
    t.print()

def display_group_health(groupId):
    # print("health for group {}".format(groupId))
    res = requests.get(host+"/rest/v1/groups/{}/health".format(groupId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    print("Device Type: GPU")
    t = PrintTable()
    for d in data["Health"]:
        rows = get_health_rows(d)
        t.add_rows(rows)
    t.print()

def set_device_health_config(deviceId, healthType, threshold):
    reqData = {
        "Threshold":threshold
    }
    res = requests.put(host+"/rest/v1/devices/{}/health/{}".format(deviceId, healthType), json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    display_device_health(deviceId)
    
def set_group_health_config(groupId, healthType, threshold):
    reqData = {
        "Threshold":threshold
    }
    res = requests.put(host+"/rest/v1/groups/{}/health/{}".format(groupId, healthType), json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    display_group_health(groupId)

def flash_firmware(deviceId, firmwareName, imagePath):
    firmwareNameMap = {
        "GSC":0
    }
    firmwareType = firmwareNameMap[firmwareName]
    reqData = {
        "type": firmwareType,
        "file": imagePath
    }
    print("Start flashing firmware:")
    print("Firmware name: {}".format(firmwareName))
    print("Image path: {}".format(imagePath))
    res = requests.post(host+"/rest/v1/devices/{}/firmwareUpgrade".format(deviceId), data=reqData)
    if res.status_code != 200 or res.json()["result"]!="OK":
        print("Error occurs: fail to flash firmware")
    while True:
        time.sleep(0.5)
        res = requests.get(host+"/rest/v1/devices/0/firmware",params={"type":firmwareType})
        data = res.json()
        result = data["result"]
        if result == "OK":
            print("Firmware flashed successfully!")
            return
        elif result=="ERROR":
            print("Error occurs: fail to flash firmware")

def search_standbys_enum_mode(num):
    return {
        0: "DEFAULT",
        1: "NEVER",
        0x7fffffff:"STANDBY_MODE_FORCE_UINT32",
    }.get(num, "unknown")

def search_standbys_enum_type(num):
    return {
        0: "XPUM_GLOBAL",
        0x7fffffff: "XPUM_STANDBY_TYPE_FORCE_UINT32",
    }.get(num, "unknown")

def get_device_standbys(deviceId):
    res = requests.get(host+"/rest/v1/devices/{}/standbys".format(deviceId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    standbyConfig = []
    for d in data["Standbys"]:
        if d["onSubdevice"] == True :
            subDeviceId = d["subdeviceId"]
        else:
            subDeviceId =' '
        #print( d["standbyType"],search_standbys_enum_type(d["standbyType"]))
        #print( d["mode"],search_standbys_enum_mode(d["mode"]))
        standbyConfig.append((subDeviceId,d["mode"]))
    return standbyConfig

def set_device_standby(deviceId, subDeviceId, standbyType, mode):
    reqData = {
        "subDeviceId": subDeviceId,
        "standbyType": standbyType,
        "mode":mode
    }
    #print(reqData)
    res = requests.post(host+"/rest/v1/devices/{}/standbys".format(deviceId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    else:
        print(res.status_code)
    get_device_standbys(deviceId)

def get_device_powerlimits(deviceId, subDeviceId):
    reqData = {
        "subDeviceId": subDeviceId,
    }
    #print(reqData)
    res = requests.get(host+"/rest/v1/devices/{}/powerLimits".format(deviceId), json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    return data["limits"]["sustainedLimit"]["power"], data["limits"]["sustainedLimit"]["interval"]
    #t = PrintTable(["Device ID", "SubDevice ID","Sustained Limit", "Burst Limit", "Peak Limit"])
    #sustained = "enabled:", data["limits"]["sustainedLimit"]["enabled"],"interval:",data["limits"]["sustainedLimit"]["interval"],'power:',data["limits"]["sustainedLimit"]["power"]
    #burst = "enabled:", data["limits"]["burstLimit"]["enabled"],'power:',data["limits"]["burstLimit"]["power"]
    #peak = "powerAC:", data["limits"]["peakLimit"]["powerAC"],'powerDC:',data["limits"]["peakLimit"]["powerDC"]
    #t.add_row([deviceId,subDeviceId,sustained,burst,peak])
    #t.print()

def get_device_burstlimits(deviceId, subDeviceId):
    reqData = {
        "subDeviceId": subDeviceId,
    }
    #print(reqData)
    res = requests.get(host+"/rest/v1/devices/{}/powerLimits".format(deviceId), json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    return data["limits"]["burstLimit"]["enabled"], data["limits"]["burstLimit"]["power"]

def set_device_powerlimit(deviceId, subDeviceId, limitType, enabled, power, interval, powerAC, powerDC):
    reqData = {
        "subDeviceId": subDeviceId,
        "limitType": limitType,
        "enabled":enabled,
        "power":power,
        "interval":interval,
        "powerAC":powerAC,
        "powerDC":powerDC,
    }
    #print(reqData)
    res = requests.post(host+"/rest/v1/devices/{}/powerLimits".format(deviceId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    else:
        print(res.status_code)

def get_device_frequencyRanges(deviceId):
    res = requests.get(host+"/rest/v1/devices/{}/frequencyRanges".format(deviceId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    freqRangeArray = []
    #t = PrintTable(["Device ID", "SubDevice ID","Frequency Type", "Min", "Max"])
    for d in data["FrequencyRange"]:
        #t.add_row([deviceId,d['subdeviceId'],d['type'],d['min'],d['max']])
        freqRangeArray.append((d['subdeviceId'],d['type'],d['min'],d['max']))
    return freqRangeArray
    #t.print()

def set_device_frequencyRange(deviceId, subDeviceId, type, min, max):
    reqData = {
        "subDeviceId": subDeviceId,
        "type": type,
        "min":min,
        "max":max
    }
    #print(reqData)
    res = requests.post(host+"/rest/v1/devices/{}/frequencyRanges".format(deviceId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    else:
        print(res.status_code)

def search_engine_type_enum(num):
    return {
        1 << 0: "XPUM_UNDEFINED",
        1 << 1: "XPUM_COMPUTE",
        1 << 2: "XPUM_THREE_D",
        1 << 3: "XPUM_MEDIA",
        1 << 4: "XPUM_COPY",
        1 << 5: "XPUM_RENDER",
        0x7fffffff:"XPUM_TYPE_FLAGS_FORCE_UINT32",
    }.get(num, "unknown")

def search_mode_enumList(num):
    nameList = []
    if num >= 0x7fffffff:
        nameList.append('XPUM_MODE_FORCE_UINT32')
        num -= 0x7fffffff
    if num >= (1<<3):
        nameList.append('XPUM_COMPUTE_UNIT_DEBUG')
        num -= 3
    if num >= (1<<2):
        nameList.append('XPUM_EXCLUSIVE')
        num -= 2
    if num >= (1<<1):
        nameList.append('XPUM_TIMESLICE')
        num -= 1
    if num >= (1<<0):
        nameList.append('XPUM_TIMEOUT')
        num -= 0
    return nameList

def search_mode_enum(num):
    #nameList = []
    if num >= 0x7fffffff:
        return 'MODE_FORCE_UINT32'
    if num >= 3: #(1<<3)
        return 'COMPUTE_UNIT_DEBUG'
    if num >= 2: #(1<<2)
        return 'EXCLUSIVE'
    if num >= 1: #(1<<1)
        return 'TIMESLICE'
    if num >= 0: #(1<<0)
         return 'TIMEOUT'

def get_device_schedulers(deviceId):
    res = requests.get(host+"/rest/v1/devices/{}/schedulers".format(deviceId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    schedulerArray = []
    #print(data)
    #t = PrintTable(["Device ID", "SubDevice ID","Can Control", "Engine Type", "Mode", "Supported Mode"])
    for d in data["schedulers"]:
        if d["onSubdevice"] == True :
            subDeviceId = d["subdeviceId"]
        else:
            subDeviceId =' '
        #engineType = d["engineType"],search_engine_type_enum(d["engineType"])
        mode =subDeviceId, d["mode"]
        schedulerArray.append(mode)
        #supportedMode = d["supportedMode"], search_mode_enumList(d["supportedMode"])
        #t.add_row([deviceId, subDeviceId, d["canControl"], engineType, mode, supportedMode])
    return schedulerArray
    #t.print()

def set_device_scheduler(deviceId, subDeviceId, schedulerType, watchdogTimeout, interval, yieldTimeout):
    reqData = {
        "subDeviceId": subDeviceId,
        "SchedulerType": schedulerType,
        "watchdogTimeout":watchdogTimeout,
        "interval":interval,
        "yieldTimeout":yieldTimeout
    }
    #print(reqData)
    res = requests.post(host+"/rest/v1/devices/{}/schedulers".format(deviceId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    else:
        print(res.status_code)

def reset_device(deviceId):
    res = requests.post(host+"/rest/v1/devices/{}/reset".format(deviceId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    else:
        print("OK")

def get_device_tile_num(deviceId):
    res = requests.get(host+"/rest/v1/devices/{}".format(deviceId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    #print("get_device_tile_num",data["NumberOfSubDevices"])
    return data["NumberOfSubDevices"]

def display_device_all_config(deviceId, deviceTileId):
    if deviceTileId is None:
        numTile = get_device_tile_num(deviceId)
        tileList = [*range(0,int(numTile),1)]
    else:
        numTile = 1
        tileList = [deviceTileId]
    #print(tileList)
    powerLimit = []
    burstLimit = []
    for tileId in tileList :
        power, interval = get_device_powerlimits(deviceId, tileId)
        enable,power1 = get_device_burstlimits(deviceId, tileId)
        powerLimit.append((tileId, power, interval))
        burstLimit.append((tileId, power1, enable))
        #print(str(power1)+ " "+ str(enable))
    #print(powerLimit) 
    standbyConfig = get_device_standbys(deviceId)
    freqRange = get_device_frequencyRanges(deviceId)
    scheduler = get_device_schedulers(deviceId)
    t = PrintTable(["Device Type", "Device Id/Tile Id","Configuration"])
    for tileId in tileList :
        tileStandby = [(valx,valy) for (valx,valy) in standbyConfig if (valx ==tileId)]
        tileFreq = [(vala,valb,valc,vald) for (vala,valb,valc,vald) in freqRange if (vala ==tileId)]
        tileScheduler = list(set([(vala,valb) for (vala,valb) in scheduler if (vala ==tileId)]))
        tilePowerLimit = [(vala,valb,valc) for (vala,valb,valc) in powerLimit if (vala ==tileId)]
        tileBurstLimit = [(vala,valb,valc) for (vala,valb,valc) in burstLimit if (vala ==tileId)]
        #print("tileStandby",tileStandby)
        #print("tileFreq",tileFreq)
        #print("tileScheduler",tileScheduler)
        #print("tilePowerLimit",tilePowerLimit)
        configContent = "Power Limit(w): "+ str(tilePowerLimit[0][1]/1000)+"\n" + "    Legal Range: 0 to 500" +"\n"\
            + "Power Average Window (ms): " + str(tilePowerLimit[0][2]) + "\n" + "    Legal Range: 0 to 125"
        configContent += "\n\n"
        configContent += "Burst Limit(w): "+ str(tileBurstLimit[0][1]/1000)+ " "+ str(tileBurstLimit[0][2]) +"\n"
        configContent += "GPU Min Frequency(MHz): " + str(tileFreq[0][2]) + "\n"\
            "GPU Max Frequency(MHz): " + str(tileFreq[0][3])\
            +"\n    Legal Range: 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000,"\
            + "1050,1100, 1150, 1200, 1250, 1300\n"
        configContent += "\n"
        configContent += "Standby type: " + search_standbys_enum_mode(tileStandby[0][1]) +"\n"\
            "    Legal Options: Default, Never\n"
        configContent += "\n"
        configContent += "Scheduler Mode: " + search_mode_enum( tileScheduler[0][1]) + "\n    Legal Options: Timeout,Timeslice, Exclusive"
        row = "GPU",str(deviceId)+"/"+str(tileId),configContent
        t.add_row(row)  
    t.print()

def set_device_scheduler(deviceId, deviceTileId, keyValue):
    #print(keyValue)
    keyValueArray = keyValue.split(",")
    #print(keyValueArray)
    watchdogTimeout = 0
    interval = 0
    yieldTimeout = 0

    if keyValueArray[0] == "timeout":
        watchdogTimeout = int(keyValueArray[1])
        schedulerType = 0
    elif keyValueArray[0] == "timeslice":
        yieldTimeout = int(keyValueArray[2])
        interval = int(keyValueArray[1])
        schedulerType = 1
    else:
        schedulerType =2
    reqData = {
        "subDeviceId": deviceTileId,
        "SchedulerType": schedulerType,
        "watchdogTimeout":watchdogTimeout,
        "interval":interval,
        "yieldTimeout":yieldTimeout
    }
    #print(reqData)
    res = requests.post(host+"/rest/v1/devices/{}/schedulers".format(deviceId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    else:
        print("OK")
    return

def set_device_frequencyRange(deviceId, deviceTileId, keyValue):
    keyValueArray = keyValue.split(",")
    #print(keyValueArray)
    reqData = {
        "subDeviceId": deviceTileId,
        "type": int(0),
        "min":int(keyValueArray[0]),
        "max":int(keyValueArray[1])
    }
    #print(reqData)
    res = requests.post(host+"/rest/v1/devices/{}/frequencyRanges".format(deviceId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    else:
        print("OK")
    return

def set_device_powerlimit(deviceId, deviceTileId, keyValue):
    keyValueArray = keyValue.split(",")
    #print(keyValueArray)
    reqData = {
        "subDeviceId": deviceTileId,
        "limitType": int(0),
        "enabled":bool(True),
        "power":int(keyValueArray[0])*1000,
        "interval":int(keyValueArray[1]),
        "powerAC":int(0),
        "powerDC":int(0),
    }
    #print(reqData)
    res = requests.post(host+"/rest/v1/devices/{}/powerLimits".format(deviceId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    else:
        print("OK")
    return

def set_device_standby(deviceId, deviceTileId, keyValue):
    if keyValue == "never":
        KeyValueInt = 1
    elif keyValue == "default":
        KeyValueInt = 0
    else:
        print("Error occurs: invalid parameter")
        return
    reqData = {
        "subDeviceId": deviceTileId,
        "standbyType": int(0),
        "mode": KeyValueInt
    }
    #print(reqData)
    res = requests.post(host+"/rest/v1/devices/{}/standbys".format(deviceId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    else:
        print("OK")
    return
def set_device_burstlimit(deviceId, deviceTileId, keyValue):
    keyValueArray = keyValue.split(",")
    #print(keyValueArray)
    reqData = {
        "subDeviceId": deviceTileId,
        "limitType": int(1),
        "enabled":bool(keyValueArray[1]=='True'),
        "power":int(keyValueArray[0])*1000,
        "interval":int(0),
        "powerAC":int(0),
        "powerDC":int(0),
    }
    #print(reqData)
    res = requests.post(host+"/rest/v1/devices/{}/powerLimits".format(deviceId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    else:
        print("OK")
    return


def start_collect_metrics_raw_data_by_device(deviceId, metricsIds):
    reqData = {
        "deviceId": deviceId,
        "metricsTypeList": [telemetry_support_metrics[i] for i in metricsIds]
    }
    res = requests.post(host+"/rest/v1/metricsRawDataTask",json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    resData = res.json()
    print("Start telemetry successfully!")
    print("Task id: {}".format(resData['TaskId']))


def start_collect_metrics_raw_data_by_group(groupId, metricsIds):
    pass


def stop_collect_metrics_raw_data_task(taskId):
    res = requests.post(host+"/rest/v1/metricsRawDataTask/{}".format(taskId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    print("Task {} stop successfully!".format(taskId))

def dump_metrics_raw_data(taskId):
    res = requests.get(host+"/rest/v1/metricsRawDataTask/{}".format(taskId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    csv_content = res.content.decode()
    header,body = csv_content.split("\n", 1)
    headers = [n.strip() for n in header.split(",")]
    print(",".join(["{}".format(metricsTypeTranslationMap.get(n,n)) for n in headers]))
    print(body)


def get_device_topology(deviceId):
    res = requests.get(host+"/rest/v1/devices/{}/topology".format(deviceId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    template = '''Topology:
    leviceId: {deviceId}
    localCPUList: {localCPUList}
    localCPUs: {localCPUs}
    switchCount:{switchCount} 
    '''
    deviceId = data['DeviceId']
    localCPUList = data['localCPUList']
    localCPUs = data['localCPUs']
    switchCount = data['switchCount']
    output = template.format(
        deviceId=deviceId,
        localCPUList=localCPUList,
        localCPUs=localCPUs,
        switchCount=switchCount
    )
    print(output)
    if switchCount>0:
        t = PrintTable(["Switch","Device Path"])
        rows = []
        for k in range(switchCount):
            rows.append(["switch_"+str(k), data['switch_'+str(k)]])
        t.add_rows(rows)
        t.print()

if __name__ == "__main__":
    try:
        arg()
    except ConnectionError as e:
        print("Fail to connect to service!")
        print("Please check xpum engine is running")
