#!/usr/bin/python3
import argparse

import json

import pprint
import requests

from texttable import Texttable

import os

os.environ['NO_PROXY'] = 'localhost'

# host = "http://localhost:5000"
host = "http://localhost:30000"

parser = argparse.ArgumentParser()
parser.add_argument('-v', '--version', action='store_true',
                    help='Display version information and exit')

subparsers = parser.add_subparsers(
    title="Subcommand options", dest="subcommand")

# discovery subcommand parser
discovery_parser = subparsers.add_parser(
    "discovery", help="Discover devices on the system")

discovery_parser.add_argument('-l', '--list', action='store_true',
                              help='List all devices discovered on the host')

discovery_parser.add_argument('-d', '--device', metavar="<deviceId>", dest="deviceId",
                              help='The device id to query, will show more detailed info')

# group subcommand parser
group_parser = subparsers.add_parser("group", help="Group management")

group_parser.add_argument('-c', '--create', metavar="<groupName>", dest="groupNameToCreate",
                          help='Create a group')
group_parser.add_argument('-r', '--remove', dest="remove", action='store_true',
                          help='Remove a group')
group_parser.add_argument('-l', '--list', dest="list", action='store_true',
                          help='Display info for a group or all groups')
group_parser.add_argument('-g', '--group', metavar="<groupId>", dest="groupId", type=int,
                          help='The id of the group to manipulate')
group_parser.add_argument('-a', '--add', metavar="<deviceIds>", dest="deviceIdToAdd", nargs='+', type=int,
                          help='Add device to a group')
group_parser.add_argument('-d', '--delete', metavar="<deviceIds>", dest="deviceIdToDelete", nargs='+', type=int,
                          help='Delete device from a group')

# agentset subcommand parser
agentset_parser = subparsers.add_parser("agentset", help="XPUM agent settings")
agentset_parser.add_argument('-l', '--list', action='store_true',
                             help='Display all agent settings')
agentset_parser.add_argument('-t', '--time', metavar='<interval>', dest="interval",type=int,
                             help='Set the time interval (in milliseconds) by which xpum daemon tries to get data. Options are 100,200,500,1000.')

# statistics subcommand parser
stats_parser = subparsers.add_parser("stats", help="Display device statistics")
stats_parser.add_argument('-d', '--device', metavar="<deviceId>", dest="deviceId", type=int,
                          help='The device id to query')
stats_parser.add_argument('-g', '--group', metavar="<groupId>", dest="groupId", type=int,
                          help='The group id to query')


class PrintTable:
    _t = Texttable()

    def __init__(self, *args):
        if len(args)>=1:
            self.headers = args[0]
            self._t.add_row(args[0])

    def add_row(self, row):
        self._t.add_row(row)

    def add_rows(self, rows):
        for row in rows:
            self._t.add_row(row)

    def print(self):
        print(self._t.draw())


def arg():
    parsed = parser.parse_args()
    # print(parsed)
    if not parsed.subcommand:
        if parsed.version:
            display_version()
            return
    elif parsed.subcommand == "discovery":
        if parsed.list:
            if parsed.deviceId:
                display_device_detail(parsed.deviceId)
                return
            display_devices()
            return
    elif parsed.subcommand == "group":
        if parsed.groupNameToCreate:
            groupName = parsed.groupNameToCreate
            create_group(groupName)
            return
        if parsed.remove:
            if not parsed.groupId:
                print("Wrong argument: <groupId> should be specified by -g option")
                return
            groupId = parsed.groupId
            remove_group(groupId)
            return
        if parsed.list:
            if parsed.groupId:
                groupId = parsed.groupId
                list_single_group_info(groupId)
                return
            list_all_group_info()
            return
        if parsed.deviceIdToAdd:
            if parsed.groupId is None:
                print("Wrong argument: <groupId> should be specified by -g option")
                return
            deviceIds = parsed.deviceIdToAdd
            groupId = parsed.groupId
            add_device_to_group(deviceIds, groupId)
            return
        if parsed.deviceIdToDelete:
            if not parsed.groupId:
                print("Wrong argument: <groupId> should be specified by -g option")
                return
            deviceIds = parsed.deviceIdToDelete
            groupId = parsed.groupId
            remove_device_from_group(deviceIds, groupId)
            return
    elif parsed.subcommand == "agentset":
        if parsed.list:
            display_all_agent_settings()
            return
        elif parsed.interval is not None:
            set_agent_settings(interval=parsed.interval)
            return
        else:
            agentset_parser.print_help()
            return
    elif parsed.subcommand == "stats":
        if parsed.deviceId is not None:
            display_device_stats(parsed.deviceId)
            return
        elif parsed.groupId is not None:
            display_group_stats(parsed.groupId)
            return
        else:
            display_all_device_stats()
            return
    parser.print_help()

def set_agent_settings(**kwargs):
    reqData = {}
    if "interval" in kwargs:
        reqData["XPUM_AGENT_CONFIG_SAMPLE_INTERVAL"] = str(kwargs["interval"])
    else:
        print("Fail: agent set key not supported")
    res = requests.post(host+"/rest/v1/globalSettings",json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    display_all_agent_settings()

def display_all_agent_settings():
    # print("Display all agent settings")
    res = requests.get(host+"/rest/v1/globalSettings")
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        # print("Fail to get agent settings")
        return
    # print(res)
    data = res.json()
    t = PrintTable(["Name","Value"])
    rows = []
    for k in data:
        if k == "XPUM_AGENT_CONFIG_SAMPLE_INTERVAL":
            rows.append(["Sampling Interval (ms)",data[k]])
    t.add_rows(rows)
    t.print()
    

def display_all_device_stats():
    res = requests.get(host+"/rest/v1/devices")

    if res.status_code != 200:
        # print("Error occurs:"+res.content.decode())
        print("Fail to query data")
        return

    data = res.json()

    gpus = [d for d in data if d['DeviceType'] == 0]

    if not gpus:
        return
    print("Device Type: GPU")
    t = PrintTable()
    for d in gpus:
        res = requests.get(host+"/rest/v1/devices/{}/stats".format(d["DeviceId"]))
        if res.status_code != 200:
            print("Error occurs:"+res.content.decode())
            return
        data = res.json()
        rows = get_stats_rows(data)
        t.add_rows(rows)
    t.print()
        

def display_device_stats(deviceId):
    # print("stats for device {}".format(deviceId))
    res = requests.get(host+"/rest/v1/devices/{}/stats".format(deviceId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    print("Device Type: GPU")
    # print(data)
    rows = get_stats_rows(data)
    t = PrintTable()
    t.add_rows(rows)
    t.print()

def get_stats_rows(data):
    header_row = ["Device Id", data['DeviceId']]
    rows = []
    counter_row_keys = ["Start Time","End Time"]
    counter_row_values = [data['Begin'],data['End']]
    for stats in data['dataList']:
        if stats['metricsType'] == "XPUM_STATS_GPU_COMPUTATION":
            v = "current: {}\navg: {}\nmin: {}\nmax: {}".format(
                stats["value"],
                stats["avg"],
                stats["min"],
                stats["max"]
            )
            rows.append(["GPU Computation (%)",v])
        elif stats['metricsType'] == "XPUM_STATS_POWER":
            v = "current: {}\navg: {}\nmin: {}\nmax: {}".format(
                stats["value"],
                stats["avg"],
                stats["min"],
                stats["max"]
            )
            rows.append(["GPU Power (w)",v])
        elif stats['metricsType'] == "XPUM_STATS_ENERGY":
            counter_row_keys.append("Energy Consumed (J)")
            counter_row_values.append("{:.3f}".format(stats['value']/1e3))
        elif stats['metricsType'] == "XPUM_STATS_GPU_FREQUENCY":
            v = "current: {}\navg: {}\nmin: {}\nmax: {}".format(
                stats["value"],
                stats["avg"],
                stats["min"],
                stats["max"]
            )
            rows.append(["GPU Frequency (MHz)",v])
        elif stats['metricsType'] == "XPUM_STATS_GPU_TEMEPERATURE":
            v = "current: {}\navg: {}\nmin: {}\nmax: {}".format(
                stats["value"],
                stats["avg"],
                stats["min"],
                stats["max"]
            )
            rows.append(["GPU Temperature (°C)",v])
        elif stats['metricsType'] == "XPUM_STATS_MEMORY_USED":
            v = "current: {:.2f}\navg: {:.2f}\nmin: {:.2f}\nmax: {:.2f}".format(
                stats["value"]/(2**20),
                stats["avg"]/(2**20),
                stats["min"]/(2**20),
                stats["max"]/(2**20)
            )
            rows.append(["Memory Userd (MiB)",v])
        elif stats['metricsType'] == "XPUM_STATS_MEMORY_READ":
            counter_row_keys.append("Memory Read (KB)")
            counter_row_values.append("{:.2f}".format(stats['value']/1e3))
        elif stats['metricsType'] == "XPUM_STATS_MEMORY_WRITE":
            counter_row_keys.append("Memory Write (KB)")
            counter_row_values.append("{:.2f}".format(stats['value']/1e3))
        
    counter_row = ["\n".join(counter_row_keys),"\n".join(counter_row_values)]
    return [header_row,counter_row,*rows]

def display_group_stats(groupId):
    # print("stats for group {}".format(groupId))
    res = requests.get(host+"/rest/v1/groups/{}/stats".format(groupId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    print("Device Type: GPU")
    t = PrintTable()
    for d in data["Datas"]:
        rows = get_stats_rows(d)
        t.add_rows(rows)
    t.print()

def remove_device_from_group(deviceIds, groupId):
    # print("remove device{} from group {}".format(deviceId,groupId))
    reqData = {
        "DeviceIdToRemove": deviceIds
    }
    res = requests.post(host+"/rest/v1/groups/{}".format(groupId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    print("Successfully remove device {} from group {}".format(deviceIds, groupId))
    data = res.json()
    t = PrintTable(["Group Id", "Group Properties"])
    value = "Group Name: \"{}\"\nDevice Ids: {}".format(
        data['GroupName'],
        data['DeviceIds']
    )
    t.add_row([data['GroupId'], value])
    t.print()

def add_device_to_group(deviceIds, groupId):
    # print("add device{} to group {}".format(deviceId,groupId))
    reqData = {
        "DeviceIdToAdd": deviceIds
    }
    res = requests.post(host+"/rest/v1/groups/{}".format(groupId),json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    print("Successfully add device {} to group {}".format(deviceIds, groupId))
    data = res.json()
    t = PrintTable(["Group Id", "Group Properties"])
    value = "Group Name: \"{}\"\nDevice Ids: {}".format(
        data['GroupName'],
        data['DeviceIds']
    )
    t.add_row([data['GroupId'], value])
    t.print()


def list_all_group_info():
    # print("Display info for all groups")
    res = requests.get(host+"/rest/v1/groups")
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    groupIds = res.json()
    rows = []
    for groupId in groupIds:
        res = requests.get(host+"/rest/v1/groups/{}".format(groupId))
        data = res.json()
        value = "Group Name: \"{}\"\nDevice Ids: {}".format(
            data['GroupName'],
            data['DeviceIds']
        )
        rows.append([data['GroupId'], value])
    t = PrintTable(["Group Id", "Group Properties"])
    t.add_rows(rows)
    t.print()
        

def list_single_group_info(groupId):
    # print("Display info for group "+groupId)
    res = requests.get(host+"/rest/v1/groups/{}".format(groupId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    # print(data)
    t = PrintTable(["Group Id", "Group Properties"])
    value = "Group Name: \"{}\"\nDevice Ids: {}".format(
        data['GroupName'],
        data['DeviceIds']
    )
    t.add_row([data['GroupId'], value])
    t.print()

def remove_group(groupId):
    # print("Remove group "+groupId)
    res = requests.delete(host+"/rest/v1/groups/{}".format(groupId))
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    print("Destroy Group Successfully!")

def create_group(groupName):
    # print("Create group "+groupName)
    reqData = {
        "GroupName":groupName
    }
    res = requests.post(host+"/rest/v1/groups", json=reqData)
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    # print(data)
    t = PrintTable(["Group Id", "Group Properties"])
    value = "Group Name: \"{}\"\nDevice Ids: {}".format(
        data['GroupName'],
        data['DeviceIds']
    )
    t.add_row([data['GroupId'], value])
    t.print()

def display_version():
    res = requests.get(host+"/rest/v1/version")
    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return
    data = res.json()
    template = '''CLI:
    Version: {cli_version}
    Build Id: 10

Service:
    Version: {service_version}
    Build Id: 10
    Level Zero Version: {level_zero_version}
    '''
    cli_version = service_version = data['Version']
    level_zero_version = data['LevelZeroVersion']
    output = template.format(
        cli_version=cli_version,
        service_version=service_version,
        level_zero_version=level_zero_version
    )
    print(output)


def device_info_to_str(props):
    rows = []
    rows.append("Device Type: {}".format(props["DeviceType"]))
    rows.append("Device Name: {}".format(props["DeviceName"]))
    rows.append("")
    rows.append("Vendor Name: {}".format(props["VendorName"]))
    rows.append("UUID: {}".format(props["UUID"]))
    rows.append("PCI BDF Address: {}".format(props["PCIBdfAddress"]))
    rows.append("PCI Slot: {}".format(props["PCISlot"]))
    rows.append("")
    rows.append("Driver Version: {}".format(props["DriverVersion"]))
    if "FirmwareName" in props:
        rows.append("Firmware Name: {}".format(props["FirmwareName"]))
    if "FirmwareVersion" in props:
        rows.append("Firmware Version: {}".format(props["FirmwareVersion"]))
    rows.append("")
    rows.append("Number of Sub Devices: {}".format(
        props["NumberOfSubDevices"]))
    rows.append("Serial Number: {}".format(props["SerialNumber"]))
    rows.append("Core Clock Rate: {}".format(props["CoreClockRate"]))
    rows.append("Max Mem Alloc Size: {}".format(props["MaxMemAllocSize"]))
    rows.append("Max Hardware Contexts: {}".format(
        props["MaxHardwareContexts"]))
    rows.append("Max Command Queue Priority: {}".format(
        props["MaxCommandQueuePriority"]))
    rows.append("")
    rows.append("Number of Slices: {}".format(props["NumberOfSlices"]))
    rows.append("Number of Sub Slices Per Slice: {}".format(
        props["NumberOfSubSlicesPerSubSlice"]))
    rows.append("Number of EUs Per Sub Slice: {}".format(
        props["NumberOfEusPerSubSlice"]))
    rows.append("Number of Threads Per EU: {}".format(
        props["NumberOfThreadsPerEu"]))
    rows.append("Pysical EU SIMD Width: {}".format(
        props["PysicalEuSimdWidth"]))
    rows.append("Timer Resolution: {}".format(props["TimerResolution"]))
    rows.append("Timestamp Valid Bits: {}".format(props["TimestampValidBits"]))
    rows.append("PCI Vendor Id: {}".format(props["PCIVendorId"]))
    rows.append("Kernel Timestamp Valid Bits: {}".format(
        props["KernelTimestampValidBits"]))
    rows.append("Flags: {}".format(props["Flags"]))
    rows.append("Memory Physical Size: {}".format(props["MemoryPhysicalSize"]))
    rows.append("Memory Free Size: {}".format(props["MemoryFreeSize"]))

    return "\n".join(rows)


def display_devices():
    res = requests.get(host+"/rest/v1/devices")

    if res.status_code != 200:
        # print("Error occurs:"+res.content.decode())
        print("Fail to query data")
        return

    data = res.json()

    gpus = [d for d in data if d['DeviceType'] == 0]

    if gpus:
        print("Device Type: GPU")
        t = PrintTable(["Device ID", "Device Information"])
        for gpu in gpus:
            rows = []
            rows.append("Device Name: {}".format(gpu["DeviceName"]))
            rows.append("Vendor Name: {}".format(gpu["VendorName"]))
            rows.append("UUID: {}".format(gpu["UUID"]))
            rows.append("PCI BDF Address: {}".format(gpu["PCIBDFAddress"]))
            "\n".join(rows)
            t.add_row([gpu['DeviceId'], "\n".join(rows)])
        t.print()


def display_device_detail(deviceId):
    res = requests.get(host+"/rest/v1/devices/{}".format(deviceId))

    if res.status_code != 200:
        print("Error occurs:"+res.content.decode())
        return

    data = res.json()

    t = PrintTable(["Device ID", "Device Information"])

    t.add_row([data['DeviceId'], device_info_to_str(data)])

    t.print()



if __name__ == "__main__":
    arg()
