#!/bin/bash

echo "Intel (R) Flash Programming Tool Version: 200.0.0.1310
Copyright (C) 2005 - 2021, Intel Corporation. All rights reserved."

sleep .5

echo "

    --- Flash Devices Found ---
    ID:0x000000    Size: 8192KB (65536Kb)

"

sleep .5

echo "Processing Flash memory block     0 from  2047.
- Erasing Flash Block [0x001000] - 100 percent complete.
- dGfxSPI Flash Operation [0x0000000]     4KB of     4KB - 100 percent complete."

sleep .5

echo "Processing Flash memory block     7 from  2047.
- Erasing Flash Block [0x008000] - 100 percent complete.
- dGfxSPI Flash Operation [0x0005000]    12KB of    12KB - 100 percent complete."

sleep .5

echo "Processing Flash memory block    67 from  2047.
- Erasing Flash Block [0x044000] - 100 percent complete.
- dGfxSPI Flash Operation [0x0043000]     4KB of     4KB - 100 percent complete."

sleep .5

echo "Processing Flash memory block    75 from  2047.
- Erasing Flash Block [0x04C000] - 100 percent complete.
- dGfxSPI Flash Operation [0x0049000]    12KB of    12KB - 100 percent complete."

sleep .5

echo "Processing Flash memory block    89 from  2047.
- Erasing Flash Block [0x05A000] - 100 percent complete.
- dGfxSPI Flash Operation [0x0057000]    12KB of    12KB - 100 percent complete."

sleep .5

echo "Processing Flash memory block   100 from  2047.
- Erasing Flash Block [0x065000] - 100 percent complete.
- dGfxSPI Flash Operation [0x0064000]     4KB of     4KB - 100 percent complete."

sleep .5

echo "Processing Flash memory block   161 from  2047.
- Erasing Flash Block [0x0A2000] - 100 percent complete.
- dGfxSPI Flash Operation [0x0084000]   120KB of   120KB - 100 percent complete."

sleep .5

echo "Processing Flash memory block   506 from  2047.
- Erasing Flash Block [0x1FB000] - 100 percent complete.
- dGfxSPI Flash Operation [0x01FA000]     4KB of     4KB - 100 percent complete."

sleep .5

echo "Processing Flash memory block   567 from  2047.
- Erasing Flash Block [0x238000] - 100 percent complete.
- dGfxSPI Flash Operation [0x021A000]   120KB of   120KB - 100 percent complete.
- Processed memory blocks 2047 from 2047.
RESULT: The data is identical. 8192KB of  8192KB - 100 percent complete.

FPT Operation Successful."
