# @schema additionalProperties:false
image:
  # -- Image repository
  repository: ghcr.io/intel/xpumd/xpumd
  # @schema enum: [Always, IfNotPresent, Never]
  # -- Image pull policy
  pullPolicy: Always
  # -- Image tag, defaults to Chart.AppVersion
  tag: ""

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.PodSpec/properties/imagePullSecrets
# -- [Image pull secrets](https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod)
imagePullSecrets: []

# -- Override the chart name
nameOverride: ""
# -- Override the fully qualified app name
fullnameOverride: ""

# @schema additionalProperties:false
serviceAccount:
  # -- Create service account
  create: true
  # @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta/properties/annotations
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not specified and create is true, a name is generated using the fully qualified app name.
  name: ""

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta/properties/annotations
# -- Annotations to add to the pod
podAnnotations: {}

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.PodSecurityContext
# -- [Pod security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)
podSecurityContext: {}

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.SecurityContext
# -- [Container security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container)
securityContext:
  # @schema hidden
  runAsUser: 0
  # @schema hidden
  privileged: true

# @schema additionalProperties:false
service:
  # -- Create service
  create: false
  # @schema enum: [ClusterIP, NodePort, LoadBalancer, ExternalName]
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: 8080

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements
# -- [Resource requests and limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) of the container
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.PodSpec/properties/nodeSelector
# -- Node selector for pod placement
nodeSelector: {}

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.PodSpec/properties/tolerations
# -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for the pods
tolerations: []

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.Affinity
# -- [Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) for the pods
affinity: {}

# @schema additionalProperties:false
config:
  # -- Configuration for receivers (https://opentelemetry.io/docs/collector/configuration/#receivers)
  # @default --  
  # @section -- XPUM Daemon Configuration
  receivers:
    # @schema additionalProperties:false
    # -- Configuration for the custom Level-Zero Sysman receiver.
    # @default --  
    # @section -- XPUM Daemon Configuration
    sysman:
      # @schema enum: [debug, info, warn, error]
      # -- Log level (debug, info, warn, error)
      # @section -- XPUM Daemon Configuration
      log_level: info
      # -- Metrics data collection interval. Must be at least twice the sample_interval.
      # @section -- XPUM Daemon Configuration
      collection_interval: 30s
      # -- Initial start delay for metrics collection, any non positive value is assumed to be immediately.
      # @section -- XPUM Daemon Configuration
      initial_delay: 1s
      # -- Metrics collection timeout.
      # @section -- XPUM Daemon Configuration
      timeout: 0
      # -- Sample interval for the high-frequency metrics.
      # @section -- XPUM Daemon Configuration
      sample_interval: 1s

  # -- Configuration for exporters (https://opentelemetry.io/docs/collector/configuration/#exporters)
  # @section -- XPUM Daemon Configuration
  exporters: {}

  # -- Configuration for processors (https://opentelemetry.io/docs/collector/configuration/#processors)
  # @section -- XPUM Daemon Configuration
  processors: {}

  # -- Configuration for extensions (https://opentelemetry.io/docs/collector/configuration/#extensions)
  # @section -- XPUM Daemon Configuration
  extensions: {}

  # -- Configuration for service (https://opentelemetry.io/docs/collector/configuration/#service)
  # @section -- XPUM Daemon Configuration
  service:
    pipelines:
      metrics:
        receivers: [sysman]
