// Copyright (C) 2026 Intel Corporation
//
// SPDX-License-Identifier: MIT
//

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Level Zero Core API bindings for Go
*/
package core
