// Code generated by "stringer -type=ApiVersion -trimprefix=API_VERSION_ -output=zz_ApiVersion_string.go const.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[API_VERSION_1_0-65536]
	_ = x[API_VERSION_1_1-65537]
	_ = x[API_VERSION_1_2-65538]
	_ = x[API_VERSION_1_3-65539]
	_ = x[API_VERSION_1_4-65540]
	_ = x[API_VERSION_1_5-65541]
	_ = x[API_VERSION_1_6-65542]
	_ = x[API_VERSION_1_7-65543]
	_ = x[API_VERSION_1_8-65544]
	_ = x[API_VERSION_1_9-65545]
	_ = x[API_VERSION_1_10-65546]
	_ = x[API_VERSION_1_11-65547]
	_ = x[API_VERSION_1_12-65548]
	_ = x[API_VERSION_1_13-65549]
	_ = x[API_VERSION_1_14-65550]
	_ = x[API_VERSION_1_15-65551]
	_ = x[API_VERSION_CURRENT-65551]
	_ = x[API_VERSION_FORCE_UINT32-2147483647]
}

const (
	_ApiVersion_name_0 = "1_01_11_21_31_41_51_61_71_81_91_101_111_121_131_141_15"
	_ApiVersion_name_1 = "FORCE_UINT32"
)

var (
	_ApiVersion_index_0 = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 34, 38, 42, 46, 50, 54}
)

func (i ApiVersion) String() string {
	switch {
	case 65536 <= i && i <= 65551:
		i -= 65536
		return _ApiVersion_name_0[_ApiVersion_index_0[i]:_ApiVersion_index_0[i+1]]
	case i == 2147483647:
		return _ApiVersion_name_1
	default:
		return "ApiVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
