// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs ./types.go

package sysman

import "github.com/intel/level-zero-go/core"

// DriverExtensionProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-driver-extension-properties-t
type DriverExtensionProperties struct {
	Name    core.StringProperty256
	Version uint32
}

// DeviceState as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-state-t
type DeviceState struct {
	stype    uint32
	pnext    *byte
	Reset    ResetReasonFlags
	Repaired RepairStatus
}

// ResetProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-reset-properties-t
type ResetProperties struct {
	stype     uint32
	pnext     *byte
	Force     uint8
	ResetType ResetType
}

// Uuid as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-uuid-t
type Uuid struct {
	Id [16]uint8
}

// DeviceProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-properties-t
type DeviceProperties struct {
	stype         uint32
	pnext         *byte
	Core          core.DeviceProperties
	NumSubdevices uint32
	SerialNumber  core.StringProperty64
	BoardNumber   core.StringProperty64
	BrandName     core.StringProperty64
	ModelName     core.StringProperty64
	VendorName    core.StringProperty64
	DriverVersion core.StringProperty64
	_             [4]byte
}

// DeviceExtProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-ext-properties-t
type DeviceExtProperties struct {
	stype uint32
	pnext *byte
	Uuid  Uuid
	Type  DeviceType
	Flags DevicePropertyFlags
}

// ProcessState as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-process-state-t
type ProcessState struct {
	stype      uint32
	pnext      *byte
	ProcessId  uint32
	MemSize    uint64
	SharedSize uint64
	Engines    EngineTypeFlags
	_          [4]byte
}

// PciAddress as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-address-t
type PciAddress struct {
	Domain   uint32
	Bus      uint32
	Device   uint32
	Function uint32
}

// PciSpeed as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-speed-t
type PciSpeed struct {
	Gen          int32
	Width        int32
	MaxBandwidth int64
}

// PciProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-properties-t
type PciProperties struct {
	stype                 uint32
	pnext                 *byte
	Address               PciAddress
	MaxSpeed              PciSpeed
	HaveBandwidthCounters uint8
	HavePacketCounters    uint8
	HaveReplayCounters    uint8
	_                     [5]byte
}

// PciState as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-state-t
type PciState struct {
	stype           uint32
	pnext           *byte
	Status          PciLinkStatus
	QualityIssues   PciLinkQualIssueFlags
	StabilityIssues PciLinkStabIssueFlags
	Speed           PciSpeed
}

// PciBarProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-bar-properties-t
type PciBarProperties struct {
	stype uint32
	pnext *byte
	Type  PciBarType
	Index uint32
	Base  uint64
	Size  uint64
}

// PciBarProperties12 as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-bar-properties12-t
type PciBarProperties12 struct {
	stype                 uint32
	pnext                 *byte
	Type                  PciBarType
	Index                 uint32
	Base                  uint64
	Size                  uint64
	ResizableBarSupported uint8
	ResizableBarEnabled   uint8
	_                     [6]byte
}

// PciStats as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-stats-t
type PciStats struct {
	Timestamp     uint64
	ReplayCounter uint64
	PacketCounter uint64
	RxCounter     uint64
	TxCounter     uint64
	Speed         PciSpeed
}

// OverclockProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-overclock-properties-t
type OverclockProperties struct {
	stype             uint32
	pnext             *byte
	DomainType        OverclockDomain
	AvailableControls uint32
	VFProgramType     VfProgramType
	NumberOfVFPoints  uint32
}

// ControlProperty as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-control-property-t
type ControlProperty struct {
	MinValue     float64
	MaxValue     float64
	StepValue    float64
	RefValue     float64
	DefaultValue float64
}

// VfProperty as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-vf-property-t
type VfProperty struct {
	MinFreq  float64
	MaxFreq  float64
	StepFreq float64
	MinVolt  float64
	MaxVolt  float64
	StepVolt float64
}

// DiagTest as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-diag-test-t
type DiagTest struct {
	Index uint32
	Name  core.StringProperty64
}

// DiagProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-diag-properties-t
type DiagProperties struct {
	stype       uint32
	pnext       *byte
	OnSubdevice uint8
	SubdeviceId uint32
	Name        core.StringProperty64
	HaveTests   uint8
	_           [7]byte
}

// DeviceEccDesc as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-ecc-desc-t
type DeviceEccDesc struct {
	stype uint32
	pnext *byte
	State DeviceEccState
	_     [4]byte
}

// DeviceEccProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-ecc-properties-t
type DeviceEccProperties struct {
	stype         uint32
	pnext         *byte
	CurrentState  DeviceEccState
	PendingState  DeviceEccState
	PendingAction DeviceAction
	_             [4]byte
}

// EngineProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-engine-properties-t
type EngineProperties struct {
	stype       uint32
	pnext       *byte
	Type        EngineGroup
	OnSubdevice uint8
	SubdeviceId uint32
	_           [4]byte
}

// EngineStats as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-engine-stats-t
type EngineStats struct {
	ActiveTime uint64
	Timestamp  uint64
}

// FabricPortId as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-id-t
type FabricPortId struct {
	FabricId   uint32
	AttachId   uint32
	PortNumber uint8
	_          [3]byte
}

// FabricPortSpeed as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-speed-t
type FabricPortSpeed struct {
	BitRate int64
	Width   int32
	_       [4]byte
}

// FabricPortProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-properties-t
type FabricPortProperties struct {
	stype       uint32
	pnext       *byte
	Model       core.StringProperty256
	OnSubdevice uint8
	SubdeviceId uint32
	PortId      FabricPortId
	MaxRxSpeed  FabricPortSpeed
	MaxTxSpeed  FabricPortSpeed
}

// FabricLinkType as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-link-type-t
type FabricLinkType struct {
	Desc core.StringProperty256
}

// FabricPortConfig as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-config-t
type FabricPortConfig struct {
	stype     uint32
	pnext     *byte
	Enabled   uint8
	Beaconing uint8
	_         [6]byte
}

// FabricPortState as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-state-t
type FabricPortState struct {
	stype          uint32
	pnext          *byte
	Status         FabricPortStatus
	QualityIssues  FabricPortQualIssueFlags
	FailureReasons FabricPortFailureFlags
	RemotePortId   FabricPortId
	RxSpeed        FabricPortSpeed
	TxSpeed        FabricPortSpeed
}

// FabricPortThroughput as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-throughput-t
type FabricPortThroughput struct {
	Timestamp uint64
	RxCounter uint64
	TxCounter uint64
}

// FabricPortErrorCounters as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-error-counters-t
type FabricPortErrorCounters struct {
	stype            uint32
	pnext            *byte
	LinkFailureCount uint64
	FwCommErrorCount uint64
	FwErrorCount     uint64
	LinkDegradeCount uint64
}

// FanSpeed as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fan-speed-t
type FanSpeed struct {
	Speed int32
	Units FanSpeedUnits
}

// FanTempSpeed as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fan-temp-speed-t
type FanTempSpeed struct {
	Temperature uint32
	Speed       FanSpeed
}

// FanSpeedTable as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fan-speed-table-t
type FanSpeedTable struct {
	NumPoints int32
	Table     [32]FanTempSpeed
}

// FanProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fan-properties-t
type FanProperties struct {
	stype          uint32
	pnext          *byte
	OnSubdevice    uint8
	SubdeviceId    uint32
	CanControl     uint8
	SupportedModes uint32
	SupportedUnits uint32
	MaxRPM         int32
	MaxPoints      int32
	_              [4]byte
}

// FanConfig as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fan-config-t
type FanConfig struct {
	stype      uint32
	pnext      *byte
	Mode       FanSpeedMode
	SpeedFixed FanSpeed
	SpeedTable FanSpeedTable
}

// FirmwareProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-firmware-properties-t
type FirmwareProperties struct {
	stype       uint32
	pnext       *byte
	OnSubdevice uint8
	SubdeviceId uint32
	CanControl  uint8
	Name        core.StringProperty64
	Version     core.StringProperty64
	_           [7]byte
}

// FreqProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-freq-properties-t
type FreqProperties struct {
	stype                    uint32
	pnext                    *byte
	Type                     FreqDomain
	OnSubdevice              uint8
	SubdeviceId              uint32
	CanControl               uint8
	IsThrottleEventSupported uint8
	Min                      float64
	Max                      float64
}

// FreqRange as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-freq-range-t
type FreqRange struct {
	Min float64
	Max float64
}

// FreqState as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-freq-state-t
type FreqState struct {
	stype           uint32
	pnext           *byte
	CurrentVoltage  float64
	Request         float64
	Tdp             float64
	Efficient       float64
	Actual          float64
	ThrottleReasons FreqThrottleReasonFlags
	_               [4]byte
}

// FreqThrottleTime as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-freq-throttle-time-t
type FreqThrottleTime struct {
	ThrottleTime uint64
	Timestamp    uint64
}

// LedProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-led-properties-t
type LedProperties struct {
	stype       uint32
	pnext       *byte
	OnSubdevice uint8
	SubdeviceId uint32
	CanControl  uint8
	HaveRGB     uint8
	_           [6]byte
}

// LedColor as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-led-color-t
type LedColor struct {
	Red   float64
	Green float64
	Blue  float64
}

// LedState as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-led-state-t
type LedState struct {
	stype uint32
	pnext *byte
	IsOn  uint8
	Color LedColor
}

// MemProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-mem-properties-t
type MemProperties struct {
	stype        uint32
	pnext        *byte
	Type         MemType
	OnSubdevice  uint8
	SubdeviceId  uint32
	Location     MemLoc
	PhysicalSize uint64
	BusWidth     int32
	NumChannels  int32
}

// MemState as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-mem-state-t
type MemState struct {
	stype  uint32
	pnext  *byte
	Health MemHealth
	Free   uint64
	Size   uint64
}

// MemBandwidth as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-mem-bandwidth-t
type MemBandwidth struct {
	ReadCounter  uint64
	WriteCounter uint64
	MaxBandwidth uint64
	Timestamp    uint64
}

// PerfProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-perf-properties-t
type PerfProperties struct {
	stype       uint32
	pnext       *byte
	OnSubdevice uint8
	SubdeviceId uint32
	Engines     EngineTypeFlags
	_           [4]byte
}

// PowerProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-power-properties-t
type PowerProperties struct {
	stype                      uint32
	pnext                      *byte
	OnSubdevice                uint8
	SubdeviceId                uint32
	CanControl                 uint8
	IsEnergyThresholdSupported uint8
	DefaultLimit               int32
	MinLimit                   int32
	MaxLimit                   int32
}

// PowerEnergyCounter as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-power-energy-counter-t
type PowerEnergyCounter struct {
	Energy    uint64
	Timestamp uint64
}

// EnergyThreshold as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-energy-threshold-t
type EnergyThreshold struct {
	Enable    uint8
	Threshold float64
	ProcessId uint32
	_         [4]byte
}

// PsuProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-psu-properties-t
type PsuProperties struct {
	stype       uint32
	pnext       *byte
	OnSubdevice uint8
	SubdeviceId uint32
	HaveFan     uint8
	AmpLimit    int32
}

// PsuState as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-psu-state-t
type PsuState struct {
	stype       uint32
	pnext       *byte
	VoltStatus  PsuVoltageStatus
	FanFailed   uint8
	Temperature int32
	Current     int32
}

// RasProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-ras-properties-t
type RasProperties struct {
	stype       uint32
	pnext       *byte
	Type        RasErrorType
	OnSubdevice uint8
	SubdeviceId uint32
	_           [4]byte
}

// RasState as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-ras-state-t
type RasState struct {
	stype    uint32
	pnext    *byte
	Category [7]uint64
}

// RasConfig as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-ras-config-t
type RasConfig struct {
	stype              uint32
	pnext              *byte
	TotalThreshold     uint64
	DetailedThresholds RasState
}

// SchedProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-sched-properties-t
type SchedProperties struct {
	stype          uint32
	pnext          *byte
	OnSubdevice    uint8
	SubdeviceId    uint32
	CanControl     uint8
	Engines        EngineTypeFlags
	SupportedModes uint32
	_              [4]byte
}

// SchedTimeoutProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-sched-timeout-properties-t
type SchedTimeoutProperties struct {
	stype           uint32
	pnext           *byte
	WatchdogTimeout uint64
}

// SchedTimesliceProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-sched-timeslice-properties-t
type SchedTimesliceProperties struct {
	stype        uint32
	pnext        *byte
	Interval     uint64
	YieldTimeout uint64
}

// StandbyProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-standby-properties-t
type StandbyProperties struct {
	stype       uint32
	pnext       *byte
	Type        StandbyType
	OnSubdevice uint8
	SubdeviceId uint32
	_           [4]byte
}

// TempProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-temp-properties-t
type TempProperties struct {
	stype                   uint32
	pnext                   *byte
	Type                    TempSensors
	OnSubdevice             uint8
	SubdeviceId             uint32
	MaxTemperature          float64
	IsCriticalTempSupported uint8
	IsThreshold1Supported   uint8
	IsThreshold2Supported   uint8
	_                       [5]byte
}

// TempThreshold as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-temp-threshold-t
type TempThreshold struct {
	EnableLowToHigh uint8
	EnableHighToLow uint8
	Threshold       float64
}

// TempConfig as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-temp-config-t
type TempConfig struct {
	stype          uint32
	pnext          *byte
	EnableCritical uint8
	Threshold1     TempThreshold
	Threshold2     TempThreshold
}

// DeviceEccDefaultPropertiesExt as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-ecc-default-properties-ext-t
type DeviceEccDefaultPropertiesExt struct {
	stype        uint32
	pnext        *byte
	DefaultState DeviceEccState
	_            [4]byte
}

// PowerLimitExtDesc as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-power-limit-ext-desc-t
type PowerLimitExtDesc struct {
	stype               uint32
	pnext               *byte
	Level               PowerLevel
	Source              PowerSource
	LimitUnit           LimitUnit
	EnabledStateLocked  uint8
	Enabled             uint8
	IntervalValueLocked uint8
	Interval            int32
	LimitValueLocked    uint8
	Limit               int32
	_                   [4]byte
}

// PowerExtProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-power-ext-properties-t
type PowerExtProperties struct {
	stype        uint32
	pnext        *byte
	Domain       PowerDomain
	DefaultLimit *PowerLimitExtDesc
}

// EngineExtProperties as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-engine-ext-properties-t
type EngineExtProperties struct {
	stype                          uint32
	pnext                          *byte
	CountOfVirtualFunctionInstance uint32
	_                              [4]byte
}

// InitFlags as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-init-flags-t
type InitFlags InitFlag

// EngineTypeFlags as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-engine-type-flags-t
type EngineTypeFlags EngineTypeFlag

// ResetReasonFlags as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-reset-reason-flags-t
type ResetReasonFlags ResetReasonFlag

// DevicePropertyFlags as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-device-property-flags-t
type DevicePropertyFlags DevicePropertyFlag

// PciLinkQualIssueFlags as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-link-qual-issue-flags-t
type PciLinkQualIssueFlags PciLinkQualIssueFlag

// PciLinkStabIssueFlags as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-pci-link-stab-issue-flags-t
type PciLinkStabIssueFlags PciLinkStabIssueFlag

// EventTypeFlags as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-event-type-flags-t
type EventTypeFlags EventTypeFlag

// FabricPortQualIssueFlags as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-qual-issue-flags-t
type FabricPortQualIssueFlags FabricPortQualIssueFlag

// FabricPortFailureFlags as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-fabric-port-failure-flags-t
type FabricPortFailureFlags FabricPortFailureFlag

// FreqThrottleReasonFlags as declared in https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#zes-freq-throttle-reason-flags-t
type FreqThrottleReasonFlags FreqThrottleReasonFlag
