// Code generated by "stringer -type=EngineTypeFlag -trimprefix=ENGINE_TYPE_FLAG_ -output=zz_EngineTypeFlag_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ENGINE_TYPE_FLAG_OTHER-1]
	_ = x[ENGINE_TYPE_FLAG_COMPUTE-2]
	_ = x[ENGINE_TYPE_FLAG_3D-4]
	_ = x[ENGINE_TYPE_FLAG_MEDIA-8]
	_ = x[ENGINE_TYPE_FLAG_DMA-16]
	_ = x[ENGINE_TYPE_FLAG_RENDER-32]
	_ = x[ENGINE_TYPE_FLAG_FORCE_UINT32-2147483647]
}

const (
	_EngineTypeFlag_name_0 = "OTHERCOMPUTE"
	_EngineTypeFlag_name_1 = "3D"
	_EngineTypeFlag_name_2 = "MEDIA"
	_EngineTypeFlag_name_3 = "DMA"
	_EngineTypeFlag_name_4 = "RENDER"
	_EngineTypeFlag_name_5 = "FORCE_UINT32"
)

var (
	_EngineTypeFlag_index_0 = [...]uint8{0, 5, 12}
)

func (i EngineTypeFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _EngineTypeFlag_name_0[_EngineTypeFlag_index_0[i]:_EngineTypeFlag_index_0[i+1]]
	case i == 4:
		return _EngineTypeFlag_name_1
	case i == 8:
		return _EngineTypeFlag_name_2
	case i == 16:
		return _EngineTypeFlag_name_3
	case i == 32:
		return _EngineTypeFlag_name_4
	case i == 2147483647:
		return _EngineTypeFlag_name_5
	default:
		return "EngineTypeFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
