// Code generated by "stringer -type=MemPageOfflineStateExpVersion -trimprefix=MEM_PAGE_OFFLINE_STATE_EXP_VERSION_ -output=zz_MemPageOfflineStateExpVersion_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MEM_PAGE_OFFLINE_STATE_EXP_VERSION_1_0-65536]
	_ = x[MEM_PAGE_OFFLINE_STATE_EXP_VERSION_CURRENT-65536]
	_ = x[MEM_PAGE_OFFLINE_STATE_EXP_VERSION_END_MARKER-2147483647]
}

const (
	_MemPageOfflineStateExpVersion_name_0 = "1_0"
	_MemPageOfflineStateExpVersion_name_1 = "END_MARKER"
)

func (i MemPageOfflineStateExpVersion) String() string {
	switch {
	case i == 65536:
		return _MemPageOfflineStateExpVersion_name_0
	case i == 2147483647:
		return _MemPageOfflineStateExpVersion_name_1
	default:
		return "MemPageOfflineStateExpVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
