// Code generated by "stringer -type=SchedMode -trimprefix=SCHED_MODE_ -output=zz_SchedMode_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SCHED_MODE_TIMEOUT-0]
	_ = x[SCHED_MODE_TIMESLICE-1]
	_ = x[SCHED_MODE_EXCLUSIVE-2]
	_ = x[SCHED_MODE_COMPUTE_UNIT_DEBUG-3]
	_ = x[SCHED_MODE_FORCE_UINT32-2147483647]
}

const (
	_SchedMode_name_0 = "TIMEOUTTIMESLICEEXCLUSIVECOMPUTE_UNIT_DEBUG"
	_SchedMode_name_1 = "FORCE_UINT32"
)

var (
	_SchedMode_index_0 = [...]uint8{0, 7, 16, 25, 43}
)

func (i SchedMode) String() string {
	switch {
	case i <= 3:
		return _SchedMode_name_0[_SchedMode_index_0[i]:_SchedMode_index_0[i+1]]
	case i == 2147483647:
		return _SchedMode_name_1
	default:
		return "SchedMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
