// Code generated by "stringer -type=StandbyPromoMode -trimprefix=STANDBY_PROMO_MODE_ -output=zz_StandbyPromoMode_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STANDBY_PROMO_MODE_DEFAULT-0]
	_ = x[STANDBY_PROMO_MODE_NEVER-1]
	_ = x[STANDBY_PROMO_MODE_FORCE_UINT32-2147483647]
}

const (
	_StandbyPromoMode_name_0 = "DEFAULTNEVER"
	_StandbyPromoMode_name_1 = "FORCE_UINT32"
)

var (
	_StandbyPromoMode_index_0 = [...]uint8{0, 7, 12}
)

func (i StandbyPromoMode) String() string {
	switch {
	case i <= 1:
		return _StandbyPromoMode_name_0[_StandbyPromoMode_index_0[i]:_StandbyPromoMode_index_0[i+1]]
	case i == 2147483647:
		return _StandbyPromoMode_name_1
	default:
		return "StandbyPromoMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
