
SET(PROJECT_VERSION_MAJOR 1)
SET(PROJECT_VERSION_MINOR 0)
SET(PROJECT_VERSION_PATCH 0)

if (NOT DEFINED BUILD_DATE)	
	execute_process(
		COMMAND date "+%Y%m%d"
		OUTPUT_VARIABLE BUILD_DATE
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)
	message(STATUS "build date=${BUILD_DATE}")
	#SET(BUILD_TIMESTAMP "${BUILD_DATE}")
	execute_process(
		COMMAND date "+%H%M%S"
		OUTPUT_VARIABLE BUILD_TIME
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)
endif()

if (NOT DEFINED GIT_COMMIT)	
	execute_process(
		COMMAND git rev-parse HEAD
		OUTPUT_VARIABLE BUILD_HASH
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)
	if (BUILD_HASH)
		message(STATUS "BUILD_HASH=${BUILD_HASH}")
		string(SUBSTRING ${BUILD_HASH} 0 8 GIT_COMMIT)
	else()
		set(GIT_COMMIT "00000000")
	endif()
	
	message(STATUS "git hash=${GIT_COMMIT}")
endif()

set(PROJECT_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}.${BUILD_DATE}")
set(PROJECT_REAL_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")
set(XPUM_VERSION_STRING ${PROJECT_VERSION})

message(STATUS "full version ${PROJECT_VERSION}") 
message(STATUS "real version: ${PROJECT_REAL_VERSION}")