// Copyright (C) 2026 Intel Corporation
//
// SPDX-License-Identifier: MIT
//

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package intel

/*
#cgo pkg-config: level-zero
#cgo CFLAGS: -I${SRCDIR}/../../../include
#include "ze_api.h"
#include "zes_api.h"
#include "intel/zes_intel_gpu_sysman.h"
#include "shim.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// Driver info logs extension name.
	DRIVER_INFO_LOGS_EXP_NAME = "ZES_intel_experimental_driver_info_logs"
	// Driver scoped event extension name.
	DRIVER_EVENT_EXP_NAME = "ZES_intel_experimental_driver_event"
	// Driver Scoped CPER Data Available Event.
	CPER_DATA_AVAILABLE = 65536
	// _STRUCTURE_TYPE_INFO_LOG_PROPERTIES_EXP as defined in intel/ze_stypes.h:33
	_STRUCTURE_TYPE_INFO_LOG_PROPERTIES_EXP = ((structureTypeExt)(0x0004000D))
	// _STRUCTURE_TYPE_INFO_LOG_METADATA_EXP as defined in intel/ze_stypes.h:35
	_STRUCTURE_TYPE_INFO_LOG_METADATA_EXP = ((structureTypeExt)(0x0004000F))
)

// DriverInfoLogsExpVersion declared in include/intel/zes_intel_gpu_sysman.h
//
// Driver info logs extension Version(s).
type DriverInfoLogsExpVersion uint32

// DriverInfoLogsExpVersion enumeration from intel/zes_intel_gpu_sysman.h:529
const (
	// version 1.0
	DRIVER_INFO_LOGS_EXP_VERSION_1_0 DriverInfoLogsExpVersion = 65536
	// latest known version
	DRIVER_INFO_LOGS_EXP_VERSION_CURRENT      DriverInfoLogsExpVersion = 65536
	DRIVER_INFO_LOGS_EXP_VERSION_FORCE_UINT32 DriverInfoLogsExpVersion = 2147483647
)

// InfoLogTypeExp declared in include/intel/zes_intel_gpu_sysman.h
//
// Info log type.
type InfoLogTypeExp uint32

// InfoLogTypeExp enumeration from intel/zes_intel_gpu_sysman.h:572
const (
	// Device info log.
	INFO_LOG_TYPE_EXP_DEVICE       InfoLogTypeExp = iota
	INFO_LOG_TYPE_EXP_FORCE_UINT32 InfoLogTypeExp = 2147483647
)

// InfoLogFormat declared in include/intel/zes_intel_gpu_sysman.h
//
// Info Log format.
type InfoLogFormat uint32

// InfoLogFormat enumeration from intel/zes_intel_gpu_sysman.h:579
const (
	INFO_LOG_FORMAT_CPER         InfoLogFormat = iota
	INFO_LOG_FORMAT_FORCE_UINT32 InfoLogFormat = 2147483647
)

// DriverEventExpVersion declared in include/intel/zes_intel_gpu_sysman.h
//
// Driver scoped event extension Version(s).
type DriverEventExpVersion uint32

// DriverEventExpVersion enumeration from intel/zes_intel_gpu_sysman.h:769
const (
	// version 1.0
	DRIVER_EVENT_EXP_VERSION_1_0 DriverEventExpVersion = 65536
	// latest known version
	DRIVER_EVENT_EXP_VERSION_CURRENT      DriverEventExpVersion = 65536
	DRIVER_EVENT_EXP_VERSION_FORCE_UINT32 DriverEventExpVersion = 2147483647
)
