# Copyright (C) 2022-2025 Intel Corporation.
# SPDX-License-Identifier: MIT
FROM centos:7.6.1810@sha256:62d9e1c2daa91166139b51577fe4f4f6b4cc41a3a2c7fc36bd895e2a17a3e4e6

ARG L0_SRC_URL=https://github.com/oneapi-src/level-zero/archive/refs/tags/v1.19.2.tar.gz
ARG CMAKE_INSTALLER_URL=https://cmake.org/files/v3.20/cmake-3.20.0-linux-x86_64.sh
ARG AUTOMAKE_URL=https://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.gz
ARG METEE_URL=https://github.com/intel/metee/archive/refs/tags/4.0.0.tar.gz
ARG IGSC_URL=https://github.com/intel/igsc/archive/refs/tags/V0.9.5.tar.gz
ARG ZLIB_VERSION=v1.3
ARG GRPC_VERSION=v1.56.2
ARG CARES_VERSION=cares-1_29_0

RUN cd /etc/yum.repos.d/ && \
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* &&\
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* &&\
    sed -i 's/$releasever/7.6.1810/g' /etc/yum.repos.d/CentOS-*

RUN yum install -y epel-release https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm https://repo.ius.io/ius-release-el7.rpm && \
    yum update -y && \
    yum install -y ccache \
        curl \
        doxygen \
        git \
        glibc-static \
        libtool \
        libudev-devel \
        lua53u-devel \
        make \
        openssl-devel \
        rpm-build \
        which
RUN yum-config-manager --add-repo=http://vault.centos.org/centos/7/sclo/x86_64/rh/ && \
    sed -i '/\[vault.centos.org_centos_7_sclo_x86_64_rh_\]/a gpgcheck=0' /etc/yum.repos.d/vault.centos.org_centos_7_sclo_x86_64_rh_.repo && \
    yum install -y devtoolset-9-gcc* \
        rh-python38 \
        rh-python38-python-devel \
        rh-python38-python-pip && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN echo "source /opt/rh/devtoolset-9/enable" >> /etc/bashrc

SHELL ["/bin/bash", "--login", "-c"]

RUN mkdir cmake && \
    cd cmake && \
    curl -s $CMAKE_INSTALLER_URL --output cmake.sh && \
    chmod +x cmake.sh && \
    ./cmake.sh --skip-license && \
    rm -f cmake.sh

ENV PATH="/cmake/bin:${PATH}".

RUN git clone --recurse-submodules --depth 1 -b $GRPC_VERSION https://github.com/grpc/grpc && \
    cd /grpc/third_party/zlib && \
    git pull https://github.com/madler/zlib $ZLIB_VERSION && \
    # fix CVE-2023-45853 by removing minizip code
    rm -rf contrib/minizip && \
    cd /grpc/third_party/cares/cares/ && \
    git pull https://github.com/c-ares/c-ares.git $CARES_VERSION && \
    cd /grpc && \
    # https://github.com/grpc/grpc/issues/32322 to fix centos7 systemd version
    sed -i 's/SYSTEMD libsystemd/SYSTEMD libsystemd>=233/' cmake/modules/Findsystemd.cmake && \
    mkdir -p cmake/build && \
    cd cmake/build && \
    cmake -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
      ../.. && \
    make -j4 && make install && \
    rm -fr /grpc

ENV PATH="/cmake/bin:/opt/rh/rh-python38/root/usr/bin:/opt/rh/rh-python38/root/usr/local/bin:${PATH}".

COPY builder/requirements.txt /tmp/requirements.txt
RUN python3.8 -m pip --proxy=$http_proxy install -r /tmp/requirements.txt

RUN curl -s --location $AUTOMAKE_URL | tar -xz && \
    cd automake-* && \
    ./configure && \
    make install && \
    rm -fr /automake-*

ENV CC=/opt/rh/devtoolset-9/root/usr/bin/gcc
ENV CXX=/opt/rh/devtoolset-9/root/usr/bin/g++

RUN curl -s --location $METEE_URL | tar -xz && \
    cd /metee-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install && \
    rm -fr /metee-*

RUN curl -s --location $IGSC_URL | tar -xz && \
    cd /igsc-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install && \
    rm -fr /igsc-*

RUN curl -s --location ${L0_SRC_URL} | tar -xz && \
    cd /level-zero-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --config Release && \
    cmake --build . --config Release --target install && \
    rm -fr /level-zero-*

RUN echo $(which python3.8) && \
    ln -sf $(which python3.8) /usr/bin/python && \
    ln -sf $(which python3.8) /usr/bin/python3 && \
    ldconfig

ENV ACLOCAL_PATH=/usr/share/aclocal