FROM debian:10.13@sha256:d39357a2a8840e450e387df33a5aaf8f0c8f99e388a0e18169f3dd240fc2393d

ARG L0_SRC_URL=https://github.com/oneapi-src/level-zero/archive/refs/tags/v1.8.5.tar.gz
ARG CMAKE_INSTALLER_URL=https://cmake.org/files/v3.20/cmake-3.20.0-linux-x86_64.sh
ARG METEE_URL=https://github.com/intel/metee/archive/refs/tags/3.1.3.tar.gz
ARG IGSC_URL=https://github.com/intel/igsc/archive/refs/tags/V0.8.4.tar.gz
ARG ZLIB_VERSION=v1.3
ARG GRPC_VERSION=v1.56.2
ARG CARES_VERSION=cares-1_19_1

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y autoconf automake build-essential ccache doxygen \
    dpkg-dev git gcc g++ libssl-dev libtool liblua5.2-0 libudev-dev pkg-config wget \
    zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libreadline-dev libffi-dev \
    apt-transport-https ca-certificates curl && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir cmake && \
    cd cmake && \
    wget -qc --no-check-certificate $CMAKE_INSTALLER_URL -O cmake.sh && \
    chmod +x cmake.sh && \
    ./cmake.sh --skip-license && \
    rm -f cmake.sh

ENV PATH "/cmake/bin:${PATH}"

RUN wget -qc --no-check-certificate https://www.python.org/ftp/python/3.8.9/Python-3.8.9.tar.xz && \
    tar -xf Python-3.8.*.tar.xz && \
    cd /Python-3.8* && \
    ./configure --enable-optimizations && \
    make -j4 && \
    make altinstall && \
    rm -fr /Python-3.8*

COPY builder/requirements.txt /tmp/requirements.txt

RUN python3.8 -m pip --proxy=$http_proxy install -r /tmp/requirements.txt

RUN git clone --recurse-submodules --depth 1 -b $GRPC_VERSION https://github.com/grpc/grpc && \
    cd /grpc/third_party/zlib && \
    git pull https://github.com/madler/zlib $ZLIB_VERSION && \
    # fix CVE-2023-45853 by removing minizip code
    rm -rf contrib/minizip && \
    cd /grpc/third_party/cares/cares/ && \
    git pull https://github.com/c-ares/c-ares.git $CARES_VERSION && \
    cd /grpc && \
    mkdir -p cmake/build && \
    cd cmake/build && \
    cmake -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
      ../.. && \
    make -j4 && make install && \
    rm -fr /grpc

RUN wget -qc --no-check-certificate $L0_SRC_URL -O - | tar -xz && \
    cd /level-zero-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install && \
    rm -fr /level-zero-*

RUN wget -qc --no-check-certificate $METEE_URL -O - | tar -xz && \
    cd /metee-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install
    
RUN wget -qc --no-check-certificate $IGSC_URL -O - | tar -xz && \
    cd /igsc-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install

RUN echo $(which python3.8) && \
    ln -sf $(which python3.8) /usr/bin/python && \
    ln -sf $(which python3.8) /usr/bin/python3 && \
    ldconfig