ARG BASE_VERSION=stream9
FROM quay.io/centos/centos:$BASE_VERSION

ARG L0_SRC_URL=https://github.com/oneapi-src/level-zero/archive/refs/tags/v1.8.5.tar.gz
ARG METEE_URL=https://github.com/intel/metee/archive/refs/tags/3.1.3.tar.gz
ARG IGSC_URL=https://github.com/intel/igsc/archive/refs/tags/V0.8.4.tar.gz
ARG ZLIB_VERSION=v1.2.13
ARG GRPC_VERSION=v1.56.2
ARG CARES_VERSION=cares-1_19_1

RUN dnf update -y && \
    dnf clean all && \
    dnf install -y cmake \
    dnf-plugins-core \
    gcc \
    gcc-c++ \
    git \
    libtool \
    libudev-devel \
    make \
    openssl-devel \
    python3.9 \
    python3.9-devel \
    python3.9-pip \
    rpm-build && \
    dnf config-manager --set-enabled crb && \
    dnf -y install epel-release && \
    dnf install -y  \
    ccache \
    doxygen \
    glibc-static \
    lua-devel && \
    dnf clean all

RUN git clone --recurse-submodules --depth 1 -b $GRPC_VERSION https://github.com/grpc/grpc && \
    cd /grpc/third_party/zlib && \
    git pull https://github.com/madler/zlib $ZLIB_VERSION && \
    cd /grpc/third_party/cares/cares/ && \
    git pull https://github.com/c-ares/c-ares.git $CARES_VERSION && \
    cd /grpc && \
    mkdir -p cmake/build && \
    cd cmake/build && \
    cmake -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
      -DCMAKE_CXX_STANDARD=14 \
      ../.. && \
    make -j && make install && \
    rm -fr /grpc

COPY builder/requirements.txt /tmp/requirements.txt
RUN python3 -m pip --proxy=$http_proxy install -r /tmp/requirements.txt

RUN curl -s --location $METEE_URL | tar -xz && \
    cd /metee-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install && \
    rm -fr /metee-*

RUN curl -s --location $IGSC_URL | tar -xz && \
    cd /igsc-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install && \
    rm -fr /igsc-*

RUN curl -s --location ${L0_SRC_URL} | tar -xz && \
    cd /level-zero-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --config Release && \
    cmake --build . --config Release --target install && \
    rm -fr /level-zero-* && \
    ldconfig
