#!/bin/bash

set -e

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

WORK=$(dirname "$0")
WORK_DIR=$(cd ${WORK} && pwd)

xpumcli_path=/opt/xpum/bin/xpumcli

# xpumcli_path=${WORK_DIR}/../cli/build/xpumcli

PROGNAME=`basename $0`

print_usage() {
    echo "Usage: $PROGNAME -m power -d 0 -c 50 -w 30"
    echo "Usage: $PROGNAME -m temperature -d 0 -t 0"
    echo "Usage: $PROGNAME --help"
}

print_help() {
    print_usage
    echo ""
    echo "GPU health status detector plugin"
    echo "Supported metric types:"
    echo " power"
}

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h|--help)
      print_help
      exit $STATE_OK
      ;;
    -d|--device)
      DEVICE=$2
      shift # past argument
      shift # past value
      ;;
    -t|--tile)
      TILE=$2
      shift # past argument
      shift # past value
      ;;
    -m|--metric)
      METRIC="$2"
      shift # past argument
      shift # past value
      ;;
    -w|--warning)
      WARNING=$2
      shift # past argument
      shift # past value
      ;;
    -c|--critical)
      CRITICAL=$2
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      echo "Unknown argument: $1"
      print_usage
      exit $STATE_UNKNOWN
      ;;
  esac
done

if [ ! $DEVICE ] ; then
    echo "Please assign device id"
    print_usage
    exit $STATE_UNKNOWN
fi

get_metric_json() {
    stats_json=$(${xpumcli_path} stats -d ${DEVICE} -j)
    if [ $TILE ] ; then
        tile_json=$(echo ${stats_json} | jq '.tile_level[] | select(.tile_id=='"${TILE})")
        # echo $tile_json
        metric_json=$(echo ${tile_json} | jq '.data_list[] | select(.metrics_type=="'"$1"'")')
        # echo $temp_json
    else
        metric_json=$(echo ${stats_json} | jq '.device_level[] | select(.metrics_type=="'"$1"'")')
    fi

    if ! [ $TILE ] ; then
        key="GPU ${DEVICE}"
    else
        key="GPU ${DEVICE} Tile ${TILE}"
    fi

    if [ ! "$metric_json" ] ; then
        echo "Critical: Can not get data"
        exit $STATE_CRITICAL
    fi
}

output() {
    if [ $CRITICAL ] && (($avg>=$CRITICAL)) ; then
        echo "Critical: ${key} $1 is over critical threshold (${avg}$2 > ${CRITICAL}$2)| '${key} $1'=${avg}$2;$WARNING;$CRITICAL;$min;$max"
        exit $STATE_CRITICAL
    elif [ $WARNING ] && (($avg>=$WARNING)); then
        echo "Warning: ${key} $1 is over warning threshold (${avg}$2 > ${WARNING}$2)| '${key} $1'=${avg}$2;$WARNING;$CRITICAL;$min;$max"
        exit $STATE_WARNING
    else
        echo "OK: ${key} $1 is fine (${avg}$2)| '${key} $1'=${avg}$2;$WARNING;$CRITICAL;$min;$max"
        exit $STATE_OK
    fi
}

detect_power() {

    get_metric_json "XPUM_STATS_POWER"

    avg=$( echo $metric_json | jq '.avg' )
    min=$( echo $metric_json | jq '.min' )
    max=$( echo $metric_json | jq '.max' )

    output "power" "W"

}

detect_temperature() {
    get_metric_json "XPUM_STATS_GPU_CORE_TEMPERATURE"

    avg=$( echo $metric_json | jq '.avg' )
    min=$( echo $metric_json | jq '.min' )
    max=$( echo $metric_json | jq '.max' )

    output "core temperature" "C"

}

case $METRIC in 
  power)
    detect_power
    ;;
  temperature)
    detect_temperature
    ;;
  *)
    echo "Unknown metrics type"
    print_usage
    exit $STATE_UNKNOWN
    ;;
esac



