object Host "ATS" {
    import "generic-host"
    address = "10.165.54.237"
}

object CheckCommand "by_xpum" {
    command = [ PluginDir + "/check_intel_gpu.py" ]

    arguments += {
        "-H" = {
            value = "$xpum_hostname$"
            required = true
        }
        "-p" = {
            value = "$xpum_port$"
            required = true
        }
        "-B" = {
            value = "$xpum_bdfaddr$"
            required = true
        }
        "-U" = {
            value = "$xpum_username$"
            required = true
        }
        "-P" = {
            value = "$xpum_password$"
            required = true
        }
        "-T" = {
            value = "$xpum_check_type$"
            required = true
        }
        "--disableTLS" = {
            set_if = "$xpum_disable_tls$"
        }
    }

    vars.xpum_disable_tls = false
}

template Service "intel-gpu-xpum" {
    vars.xpum_port = 30000
    vars.xpum_bdfaddr = "0000:4d:00.0"
    vars.xpum_username = "xpumadmin"
    vars.xpum_password = "user@123"
    vars.xpum_hostname = host.address
}

apply Service "gpu telemetry" {
    import "generic-service"
    import "intel-gpu-xpum"

    check_command = "by_xpum"

    vars.xpum_check_type = "telemetry"
    assign where host.name == "ATS"
}

apply Service "gpu health" {
    import "generic-service"
    import "intel-gpu-xpum"

    check_command = "by_xpum"

    vars.xpum_check_type = "health"
    assign where host.name == "ATS"
}