// Code generated by "stringer -type=DeviceHealthStatusExt -trimprefix=DEVICE_HEALTH_STATUS_EXT_ -output=zz_DeviceHealthStatusExt_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEVICE_HEALTH_STATUS_EXT_OK-0]
	_ = x[DEVICE_HEALTH_STATUS_EXT_WARNING-1]
	_ = x[DEVICE_HEALTH_STATUS_EXT_CRITICAL-2]
	_ = x[DEVICE_HEALTH_STATUS_EXT_FAILED-3]
	_ = x[DEVICE_HEALTH_STATUS_EXT_FORCE_UINT32-2147483647]
}

const (
	_DeviceHealthStatusExt_name_0 = "OKWARNINGCRITICALFAILED"
	_DeviceHealthStatusExt_name_1 = "FORCE_UINT32"
)

var (
	_DeviceHealthStatusExt_index_0 = [...]uint8{0, 2, 9, 17, 23}
)

func (i DeviceHealthStatusExt) String() string {
	switch {
	case i <= 3:
		return _DeviceHealthStatusExt_name_0[_DeviceHealthStatusExt_index_0[i]:_DeviceHealthStatusExt_index_0[i+1]]
	case i == 2147483647:
		return _DeviceHealthStatusExt_name_1
	default:
		return "DeviceHealthStatusExt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
