// Code generated by "stringer -type=DeviceAction -trimprefix=DEVICE_ACTION_ -output=zz_DeviceAction_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEVICE_ACTION_NONE-0]
	_ = x[DEVICE_ACTION_WARM_CARD_RESET-1]
	_ = x[DEVICE_ACTION_COLD_CARD_RESET-2]
	_ = x[DEVICE_ACTION_COLD_SYSTEM_REBOOT-3]
	_ = x[DEVICE_ACTION_FORCE_UINT32-2147483647]
}

const (
	_DeviceAction_name_0 = "NONEWARM_CARD_RESETCOLD_CARD_RESETCOLD_SYSTEM_REBOOT"
	_DeviceAction_name_1 = "FORCE_UINT32"
)

var (
	_DeviceAction_index_0 = [...]uint8{0, 4, 19, 34, 52}
)

func (i DeviceAction) String() string {
	switch {
	case i <= 3:
		return _DeviceAction_name_0[_DeviceAction_index_0[i]:_DeviceAction_index_0[i+1]]
	case i == 2147483647:
		return _DeviceAction_name_1
	default:
		return "DeviceAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
