// Code generated by "stringer -type=FreqThrottleReasonFlag -trimprefix=FREQ_THROTTLE_REASON_FLAG_ -output=zz_FreqThrottleReasonFlag_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FREQ_THROTTLE_REASON_FLAG_AVE_PWR_CAP-1]
	_ = x[FREQ_THROTTLE_REASON_FLAG_BURST_PWR_CAP-2]
	_ = x[FREQ_THROTTLE_REASON_FLAG_CURRENT_LIMIT-4]
	_ = x[FREQ_THROTTLE_REASON_FLAG_THERMAL_LIMIT-8]
	_ = x[FREQ_THROTTLE_REASON_FLAG_PSU_ALERT-16]
	_ = x[FREQ_THROTTLE_REASON_FLAG_SW_RANGE-32]
	_ = x[FREQ_THROTTLE_REASON_FLAG_HW_RANGE-64]
	_ = x[FREQ_THROTTLE_REASON_FLAG_VOLTAGE-128]
	_ = x[FREQ_THROTTLE_REASON_FLAG_THERMAL-256]
	_ = x[FREQ_THROTTLE_REASON_FLAG_POWER-512]
	_ = x[FREQ_THROTTLE_REASON_FLAG_FORCE_UINT32-2147483647]
}

const (
	_FreqThrottleReasonFlag_name_0 = "AVE_PWR_CAPBURST_PWR_CAP"
	_FreqThrottleReasonFlag_name_1 = "CURRENT_LIMIT"
	_FreqThrottleReasonFlag_name_2 = "THERMAL_LIMIT"
	_FreqThrottleReasonFlag_name_3 = "PSU_ALERT"
	_FreqThrottleReasonFlag_name_4 = "SW_RANGE"
	_FreqThrottleReasonFlag_name_5 = "HW_RANGE"
	_FreqThrottleReasonFlag_name_6 = "VOLTAGE"
	_FreqThrottleReasonFlag_name_7 = "THERMAL"
	_FreqThrottleReasonFlag_name_8 = "POWER"
	_FreqThrottleReasonFlag_name_9 = "FORCE_UINT32"
)

var (
	_FreqThrottleReasonFlag_index_0 = [...]uint8{0, 11, 24}
)

func (i FreqThrottleReasonFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FreqThrottleReasonFlag_name_0[_FreqThrottleReasonFlag_index_0[i]:_FreqThrottleReasonFlag_index_0[i+1]]
	case i == 4:
		return _FreqThrottleReasonFlag_name_1
	case i == 8:
		return _FreqThrottleReasonFlag_name_2
	case i == 16:
		return _FreqThrottleReasonFlag_name_3
	case i == 32:
		return _FreqThrottleReasonFlag_name_4
	case i == 64:
		return _FreqThrottleReasonFlag_name_5
	case i == 128:
		return _FreqThrottleReasonFlag_name_6
	case i == 256:
		return _FreqThrottleReasonFlag_name_7
	case i == 512:
		return _FreqThrottleReasonFlag_name_8
	case i == 2147483647:
		return _FreqThrottleReasonFlag_name_9
	default:
		return "FreqThrottleReasonFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
