// Code generated by "stringer -type=FreqDomain -trimprefix=FREQ_DOMAIN_ -output=zz_FreqDomain_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FREQ_DOMAIN_GPU-0]
	_ = x[FREQ_DOMAIN_MEMORY-1]
	_ = x[FREQ_DOMAIN_MEDIA-2]
	_ = x[FREQ_DOMAIN_FORCE_UINT32-2147483647]
}

const (
	_FreqDomain_name_0 = "GPUMEMORYMEDIA"
	_FreqDomain_name_1 = "FORCE_UINT32"
)

var (
	_FreqDomain_index_0 = [...]uint8{0, 3, 9, 14}
)

func (i FreqDomain) String() string {
	switch {
	case i <= 2:
		return _FreqDomain_name_0[_FreqDomain_index_0[i]:_FreqDomain_index_0[i+1]]
	case i == 2147483647:
		return _FreqDomain_name_1
	default:
		return "FreqDomain(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
