// Code generated by "stringer -type=MemLoc -trimprefix=MEM_LOC_ -output=zz_MemLoc_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MEM_LOC_SYSTEM-0]
	_ = x[MEM_LOC_DEVICE-1]
	_ = x[MEM_LOC_FORCE_UINT32-2147483647]
}

const (
	_MemLoc_name_0 = "SYSTEMDEVICE"
	_MemLoc_name_1 = "FORCE_UINT32"
)

var (
	_MemLoc_index_0 = [...]uint8{0, 6, 12}
)

func (i MemLoc) String() string {
	switch {
	case i <= 1:
		return _MemLoc_name_0[_MemLoc_index_0[i]:_MemLoc_index_0[i+1]]
	case i == 2147483647:
		return _MemLoc_name_1
	default:
		return "MemLoc(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
