// Code generated by "stringer -type=MemoryVendorInfoExtVersion -trimprefix=MEMORY_VENDOR_INFO_EXT_VERSION_ -output=zz_MemoryVendorInfoExtVersion_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MEMORY_VENDOR_INFO_EXT_VERSION_1_0-65536]
	_ = x[MEMORY_VENDOR_INFO_EXT_VERSION_CURRENT-65536]
	_ = x[MEMORY_VENDOR_INFO_EXT_VERSION_FORCE_UINT32-2147483647]
}

const (
	_MemoryVendorInfoExtVersion_name_0 = "1_0"
	_MemoryVendorInfoExtVersion_name_1 = "FORCE_UINT32"
)

func (i MemoryVendorInfoExtVersion) String() string {
	switch {
	case i == 65536:
		return _MemoryVendorInfoExtVersion_name_0
	case i == 2147483647:
		return _MemoryVendorInfoExtVersion_name_1
	default:
		return "MemoryVendorInfoExtVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
