// Code generated by "stringer -type=PciLinkStabIssueFlag -trimprefix=PCI_LINK_STAB_ISSUE_FLAG_ -output=zz_PciLinkStabIssueFlag_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PCI_LINK_STAB_ISSUE_FLAG_RETRAINING-1]
	_ = x[PCI_LINK_STAB_ISSUE_FLAG_FORCE_UINT32-2147483647]
}

const (
	_PciLinkStabIssueFlag_name_0 = "RETRAINING"
	_PciLinkStabIssueFlag_name_1 = "FORCE_UINT32"
)

func (i PciLinkStabIssueFlag) String() string {
	switch {
	case i == 1:
		return _PciLinkStabIssueFlag_name_0
	case i == 2147483647:
		return _PciLinkStabIssueFlag_name_1
	default:
		return "PciLinkStabIssueFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
