// Code generated by "stringer -type=PciBarType -trimprefix=PCI_BAR_TYPE_ -output=zz_PciBarType_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PCI_BAR_TYPE_MMIO-0]
	_ = x[PCI_BAR_TYPE_ROM-1]
	_ = x[PCI_BAR_TYPE_MEM-2]
	_ = x[PCI_BAR_TYPE_FORCE_UINT32-2147483647]
}

const (
	_PciBarType_name_0 = "MMIOROMMEM"
	_PciBarType_name_1 = "FORCE_UINT32"
)

var (
	_PciBarType_index_0 = [...]uint8{0, 4, 7, 10}
)

func (i PciBarType) String() string {
	switch {
	case i <= 2:
		return _PciBarType_name_0[_PciBarType_index_0[i]:_PciBarType_index_0[i+1]]
	case i == 2147483647:
		return _PciBarType_name_1
	default:
		return "PciBarType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
