// Code generated by "stringer -type=PowerSource -trimprefix=POWER_SOURCE_ -output=zz_PowerSource_string.go const.go"; DO NOT EDIT.

package sysman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[POWER_SOURCE_ANY-0]
	_ = x[POWER_SOURCE_MAINS-1]
	_ = x[POWER_SOURCE_BATTERY-2]
	_ = x[POWER_SOURCE_FORCE_UINT32-2147483647]
}

const (
	_PowerSource_name_0 = "ANYMAINSBATTERY"
	_PowerSource_name_1 = "FORCE_UINT32"
)

var (
	_PowerSource_index_0 = [...]uint8{0, 3, 8, 15}
)

func (i PowerSource) String() string {
	switch {
	case i <= 2:
		return _PowerSource_name_0[_PowerSource_index_0[i]:_PowerSource_index_0[i+1]]
	case i == 2147483647:
		return _PowerSource_name_1
	default:
		return "PowerSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
