/*
 * Copyright (C) 2025 Intel Corporation
 * SPDX-License-Identifier: MIT
 *
 */

#ifndef __PLDM_FIRMWAREUPDATE_H
#define __PLDM_FIRMWAREUPDATE_H

#define PLDM_FWUPDATE_MAX_PAYLOAD_SIZE 512
#define PLDM_FWU_COMP_VER_STR_SIZE_MAX 256
#define PLDM_MCTP_MAX_TRANSFER_SIZE 32
#define FWU_MAXIMUM_OUTSTANDING_TRANSFER_REQ 1
#define FWU_PACKAGE_DATALENGTH 0
#define FWU_FORCEUPDATE 1

#define FWU_COMMAND_BASE_SIZE 12
#define QUERY_DEVICE_IDENTIFIERS_SIZE 12
#define GET_FIRMWARE_PARAMETERS_SIZE 12
#define ACTIVATE_FIRMWARE_SIZE 13
#define COMPONENTCLASSIFICATIONINDEX 0x00

#include "pldm.h"

enum _pldm_firmwareupdate_command_code
{
	QUERY_DEVICE_IDENTIFIERS = 0x01,
	GET_FIRMWARE_PARAMETERS = 0x02,
	QUERY_DOWNSTREAM_DEVICES = 0x03,
	QUERY_DOWNSTREAM_IDENTIFIERS = 0x04,
	GET_DOWNSTREAM_FIRMWARE_PARAMETERS = 0x05,
	REQUEST_UPDATE = 0x10,
	GET_PACKAGE_DATA = 0x11,
	GET_DEVICE_META_DATA = 0x12,
	PASS_COMPONENT_TABLE = 0x13,
	UPDATE_COMPONENT = 0x14,
	REQUEST_FIRMWARE_DATA = 0x15,
	TRANSFER_COMPLETE = 0x16,
	VERIFY_COMPLETE = 0x17,
	APPLY_COMPLETE = 0x18,
	GET_META_DATA = 0x19,
	ACTIVATE_FIRMWARE = 0x1A,
	GET_STATUS = 0x1B,
	CANCEL_UPDATE_COMPONENT = 0x1C,
	CANCEL_UPDATE = 0x1D,
	ACTIVATE_PENDING_COMPONENT_IMAGE_SET = 0x1E,
	ACTIVATE_PENDING_COMPONENT_IMAGE = 0x1F,
	REQUEST_DOWNSTREAM_DEVICE_UPDATE = 0x20,
	GET_COMPONENT_OPAQUE_DATA = 0x21,
	UPDATE_SECURITY_REVISION = 0x22
};

enum _pldm_fwupdate_error_codes
{
	NOT_IN_UPDATE_MODE = 0x80,
	ALREADY_IN_UPDATE_MODE = 0x81,
	DATA_OUT_OF_RANGE = 0x82,
	INVALID_TRANSFER_LENGTH = 0x83,
	INVALID_STATE_FOR_COMMAND = 0x84,
	INCOMPLETE_UPDATE = 0x85,
	BUSY_IN_BACKGROUND = 0x86,
	CANCEL_PENDING = 0x87,
	COMMAND_NOT_EXPECTED = 0x88,
	RETRY_REQUEST_FW_DATA = 0x89,
	UNABLE_TO_INITIATE_UPDATE = 0x8A,
	ACTIVATION_NOT_REQUIRED = 0x8B,
	SELF_CONTAINED_ACTIVATION_NOT_PERMITTED = 0x8C,
	NO_DEVICE_METADATA = 0x8D,
	RETRY_REQUEST_UPDATE = 0x8E,
	NO_PACKAGE_DATA = 0x8F,
	INVALID_DATA_TRANSFER_HANDLE = 0x90,
	INVALID_TRANSFER_OPERATION_FLAG = 0x91,
	ACTIVATE_PENDING_IMAGE_NOT_PERMITTED = 0x92,
	PACKAGE_DATA_ERROR = 0x93
};

enum GETSTATUS_STATES
{
	GETSTATUS_IDLE = 0x00,
	GETSTATUS_LEARN_COMPONENTS = 0x01,
	GETSTATUS_READY_XFER = 0x02,
	GETSTATUS_DOWNLOAD = 0x03,
	GETSTATUS_VERIFY = 0x04,
	GETSTATUS_APPLY = 0x05,
	GETSTATUS_ACTIVE = 0x06
};

enum PASSCOMPONENT_TABLE_TRANSFERFLAG
{
	TRANSFERFLAG_START = 0x01,
	TRANSFERFLAG_MIDDLE = 0x02,
	TRANSFERFLAG_END = 0x04,
	TRANSFERFLAG_STARTANDEND = 0x5
};

struct fwupd_cmds_t
{
	std::string name;
	_pldm_firmwareupdate_command_code cmd;
	uint8_t size;
};

#endif // __PLDM_FIRMWAREUPDATE_H
