# files for GPU Diagnostics
MEDIA_CODER_TOOLS_PATH = "/usr/share/mfx/samples/"
MEDIA_CODER_TOOLS_DECODE_FILE = "test_stream.264"
MEDIA_CODER_TOOLS_ENCODE_FILE = "test_stream_176x96.yuv"

# thresholds for GPU Diagnostics
# ATS-P 2T
NAME = Intel(R) Graphics [0x020a]
PCIE_BANDWIDTH_MIN_GBPS = 24            # GBPS
SINGLE_PRECISION_MIN_GFLOPS = 16000     # GFLOPS
POWER_MIN_STRESS_WATT = 100             # W
MEMORY_BANDWIDTH_MIN_GBPS = 450         # GBPS

# ATS-M3
NAME = Intel(R) Graphics [0x56c1]
PCIE_BANDWIDTH_MIN_GBPS = 8             # GBPS
SINGLE_PRECISION_MIN_GFLOPS = 1200      # GFLOPS
POWER_MIN_STRESS_WATT = 20              # W
MEMORY_BANDWIDTH_MIN_GBPS = 80          # GBPS

# ATS-P 1T
# ATS-M1
# PVC