name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: intelsb.prod.amr.dind
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Checkout level-zero-go
      uses: actions/checkout@v6
      with:
        repository: marquiz/level-zero-go
        path: ./level-zero-go
        token: ${{ secrets.LEVEL_ZERO_GO_TOKEN }}

    - name: Golangci-lint
      run: docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:latest golangci-lint run
