name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: [intel.prod.amr.dind]
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Golangci-lint
      run: |
        docker run --rm -v $(pwd):/app -w /app \
        -e PKG_CONFIG_PATH=/app/hack \
        golangci/golangci-lint:v2.6.2 golangci-lint run

    - name: Verify generated assets
      run: |
        docker build --target artifacts \
                     --output type=local,dest=. \
                     -f hack/Dockerfile.generate .
        if ! git diff --quiet; then
          echo "Generated assets are out of date. Please run make generate and commit the changes."
          git --no-pager diff
          exit 1
        fi
