name: CI Checks - Level-Zero Go bindings

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on:
      labels: [intel.prod.amr.dind]
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Build examples
      uses: docker/build-push-action@v6
      with:
        context: ./receiver/internal/level-zero-go
        file: ./receiver/internal/level-zero-go/examples/list-sysman/Dockerfile
