name: Container Images

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on:
      labels: [intel.prod.amr.dind]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Install cosign
      if: github.event_name == 'push'
      uses: sigstore/cosign-installer@v3
      with:
        cosign-release: 'v2.6.1'

    - name: Setup Helm
      if: github.event_name == 'push'
      uses: azure/setup-helm@v4

    - name: Docker login
      if: ${{ github.event_name == 'push' }}
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set image tags
      id: vars
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          tag="pr-${{ github.event.pull_request.number }}"
        else
          tag="${{ github.ref_name }}"
        fi
        if [ "${{ github.ref_type }}" = "tag" ]; then
          chart_version=$(echo "${{ github.ref_name }}" | sed 's/^v//')
        else
          chart_version="0.0.0-${{ github.ref_name }}"
        fi

        echo "IMAGE_TAG=ghcr.io/${{ github.repository }}/xpumd:${tag}" >> $GITHUB_ENV
        echo "CHART_VERSION=${chart_version}" >> $GITHUB_ENV

    - name: Build and push image
      id: build_and_push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ github.event_name == 'push' }}
        tags: ${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Sign image
      if: ${{ github.event_name == 'push' }}
      env:
        DIGEST: ${{ steps.build_and_push.outputs.digest }}
      run: cosign sign --yes ${{ env.IMAGE_TAG }}@${{ steps.build_and_push.outputs.digest }}

    - name: Run Trivy image scan
      continue-on-error: true
      uses: aquasecurity/trivy-action@0.34.1
      with:
        exit-code: 1
        image-ref: ${{ env.IMAGE_TAG }}
        list-all-pkgs: true
        format: json
        output: trivy-report.json

    - name: Print Trivy report in human-readable format
      uses: aquasecurity/trivy-action@0.34.1
      with:
        scan-type: convert
        image-ref: trivy-report.json
        format: table

    - name: Convert Trivy report to CSV format
      uses: aquasecurity/trivy-action@0.34.1
      with:
        scan-type: convert
        image-ref: trivy-report.json
        format: template
        template: "@.github/workflows/trivy-csv.tpl"
        output: trivy-image-report.csv

    - name: Upload Trivy CSV report as artifact
      uses: actions/upload-artifact@v6
      with:
        name: trivy-image-report
        path: trivy-image-report.csv

    - name: Helm login
      if: github.event_name == 'push'
      run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Package Helm chart
      if: github.event_name == 'push'
      run: |
        helm package ./charts/xpumd/ --version ${{ env.CHART_VERSION }} --app-version ${{ github.ref_name }}

    - name: Push Helm chart
      if: github.event_name == 'push'
      run: helm push xpumd-*.tgz oci://ghcr.io/${{ github.repository }}/charts/
