name: Linux - xpumd container images

on:
  push:
    branches:
      - main
      - dev
      - v2*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*
      - xpumd/v[0-9]+.[0-9]+.[0-9]+
      - xpumd/v[0-9]+.[0-9]+.[0-9]+-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Install cosign
      if: github.event_name == 'push'
      uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
      with:
        cosign-release: 'v2.6.1'

    - name: Setup Helm
      if: github.event_name == 'push'
      uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

    - name: Docker login
      if: ${{ github.event_name == 'push' }}
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set image tags
      id: versiontags
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          tag="pr-${{ github.event.pull_request.number }}"
        else
          tag=$(echo "${{ github.ref_name }}" | sed 's!^xpumd/!!')
        fi
        if [ "${{ github.ref_type }}" = "tag" ]; then
          chart_version=$(echo "${{ github.ref_name }}" | sed -e 's!^xpumd/!!' -e 's!^v!!')
        else
          chart_version="0.0.0-${{ github.ref_name }}"
        fi

        echo "IMAGE_TAG=ghcr.io/${{ github.repository }}/xpumd:${tag}" >> $GITHUB_ENV
        echo "CHART_VERSION=${chart_version}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      if: vars.NO_SETUP_BUILDX != 'true'
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

    - name: Build and push image
      id: build_and_push
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
      with:
        context: ./xpumd
        file: ./xpumd/Dockerfile
        push: ${{ github.event_name == 'push' }}
        tags: ${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Sign image
      if: ${{ github.event_name == 'push' }}
      env:
        DIGEST: ${{ steps.build_and_push.outputs.digest }}
      run: cosign sign --yes ${{ env.IMAGE_TAG }}@${{ steps.build_and_push.outputs.digest }}

    - name: Run Trivy image scan
      continue-on-error: true
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        exit-code: 1
        image-ref: ${{ env.IMAGE_TAG }}
        list-all-pkgs: true
        format: json
        output: trivy-report.json

    - name: Print Trivy report in human-readable format
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        scan-type: convert
        image-ref: trivy-report.json
        format: table

    - name: Convert Trivy report to CSV format
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        scan-type: convert
        image-ref: trivy-report.json
        format: template
        template: "@.github/workflows/trivy-csv.tpl"
        output: trivy-xpumd-image-report.csv

    - name: Upload Trivy CSV report as artifact
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: trivy-xpumd-image-report
        path: trivy-xpumd-image-report.csv

    - name: Helm login
      if: github.event_name == 'push'
      run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Package Helm chart
      if: github.event_name == 'push'
      run: |
        helm package ./xpumd/charts/xpumd/ --version ${{ env.CHART_VERSION }} --app-version ${{ github.ref_name }}

    - name: Push Helm chart
      if: github.event_name == 'push'
      run: helm push xpumd-*.tgz oci://ghcr.io/${{ github.repository }}/charts/
