name: Linux - Level-Zero Go bindings

on:
  push:
    branches:
      - main
      - dev
      - v2*
  pull_request:
    paths:
      - 'xpumd/**'
      - '.github/workflows/xpumd-ci-checks-go-bindings.yml'

permissions:
  contents: read

jobs:
  checks:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    strategy:
      matrix:
        app:
          - list-sysman
          - events-sysman
    steps:
    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Build examples
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
      with:
        context: ./xpumd/receiver/internal/level-zero-go
        file: ./xpumd/receiver/internal/level-zero-go/examples/Dockerfile
        build-args: APP=${{ matrix.app }}
