name: Linux - Level-Zero Go bindings

on:
  push:
    branches:
      - main
      - dev
      - v2*
  pull_request:
    paths:
      - 'xpumd/**'
      - '.github/workflows/xpumd-ci-checks-go-bindings.yml'

permissions:
  contents: read

jobs:
  checks:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    strategy:
      matrix:
        app:
          - list-sysman
          - events-sysman
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Build examples
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        context: ./xpumd/level-zero-go
        file: ./xpumd/level-zero-go/examples/Dockerfile
        build-args: APP=${{ matrix.app }}
