name: Linux - Level-Zero Go bindings

on:
  push:
    branches:
      - main
      - dev
      - v2*
  pull_request:
    paths:
      - 'xpumd/**'
      - '.github/workflows/xpumd-ci-checks-go-bindings.yml'

permissions:
  contents: read

jobs:
  checks:
    runs-on: ${{ fromJson(vars.RUNS_ON) }}
    strategy:
      matrix:
        app:
          - list-sysman
          - list-sysman-exp
          - events-sysman
          - events-sysman-exp
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Build examples
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
      with:
        context: ./xpumd/level-zero-go
        file: ./xpumd/level-zero-go/examples/Dockerfile
        build-args: APP=${{ matrix.app }}
